#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PNR_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MPTDC_DIR="$(cd "$PNR_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MPTDC_DIR/.." && pwd)"

OUT=""
LEF_FILES=()
LIB_FILES=()
SEARCH_ROOTS=()

usage() {
  cat <<'USAGE'
Usage:
  discover_xh018_physical_cells.sh [options]

Options:
  --lef <file>       Add a LEF file to scan. Repeatable.
  --lib <file>       Add a Liberty file to scan. Repeatable.
  --root <dir>       Add a directory to search for *.lef/*.lib. Repeatable.
  --out <file>       Write a Tcl candidate file.
  -h, --help         Show this help.

The script only reports candidates found in real LEF/Liberty inputs. It does
not invent or hard-code XH018 tap, endcap, filler, antenna, decap, or tie names.
USAGE
}

abs_path() {
  local path="$1"
  case "$path" in
    /*) printf '%s\n' "$path" ;;
    *) printf '%s/%s\n' "$REPO_ROOT" "$path" ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --lef)
      LEF_FILES+=("$(abs_path "${2:?missing --lef value}")")
      shift 2
      ;;
    --lib)
      LIB_FILES+=("$(abs_path "${2:?missing --lib value}")")
      shift 2
      ;;
    --root)
      SEARCH_ROOTS+=("$(abs_path "${2:?missing --root value}")")
      shift 2
      ;;
    --out)
      OUT="$(abs_path "${2:?missing --out value}")"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "ERROR: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      echo "ERROR: unexpected argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

for env_name in MPTDC_XH018_ROOT MPTDC_TECH_ROOT MPTDC_PDK_ROOT XFAB_PDK_ROOT PDK_ROOT; do
  if [[ -n "${!env_name:-}" && -d "${!env_name}" ]]; then
    SEARCH_ROOTS+=("${!env_name}")
  fi
done

if [[ "${#SEARCH_ROOTS[@]}" -gt 0 ]]; then
  while IFS= read -r file; do LEF_FILES+=("$file"); done < <(
    find "${SEARCH_ROOTS[@]}" -type f \( -iname '*.lef' -o -iname '*.tlef' \) 2>/dev/null | sort -u
  )
  while IFS= read -r file; do LIB_FILES+=("$file"); done < <(
    find "${SEARCH_ROOTS[@]}" -type f \( -iname '*.lib' -o -iname '*.lib.gz' \) 2>/dev/null | sort -u
  )
fi

if [[ "${#LEF_FILES[@]}" -eq 0 && "${#LIB_FILES[@]}" -eq 0 ]]; then
  echo "ERROR: no LEF/Liberty inputs found. Pass --lef/--lib/--root or set a PDK root environment variable." >&2
  exit 3
fi

TMP_NAMES="$(mktemp)"
trap 'rm -f "$TMP_NAMES"' EXIT

if [[ "${#LEF_FILES[@]}" -gt 0 ]]; then
  awk '
    /^[[:space:]]*MACRO[[:space:]]+/ {print $2}
  ' "${LEF_FILES[@]}" >> "$TMP_NAMES"
fi

if [[ "${#LIB_FILES[@]}" -gt 0 ]]; then
  for lib in "${LIB_FILES[@]}"; do
    if [[ "$lib" == *.gz ]]; then
      gzip -cd "$lib"
    else
      sed -n '1,$p' "$lib"
    fi
  done | awk '
    /^[[:space:]]*cell[[:space:]]*\(/ {
      line=$0
      sub(/^[^(]*\(/, "", line)
      sub(/\).*/, "", line)
      gsub(/[[:space:]"]/, "", line)
      if (line != "") print line
    }
  ' >> "$TMP_NAMES"
fi

sort -u "$TMP_NAMES" -o "$TMP_NAMES"

classify() {
  local pattern="$1"
  awk -v pat="$pattern" '
    {
      low=tolower($0)
      if (low ~ pat) print $0
    }
  ' "$TMP_NAMES" | paste -sd' ' -
}

TAP="$(classify '(^|_)(tap|welltap|wtap)')"
ENDCAP="$(classify '(endcap|^end|_end)')"
FILLER="$(classify '(fill|filler)')"
DECAP="$(classify '(decap|dcap)')"
ANTENNA="$(classify '(antenna|ant)')"
TIE_HIGH="$(classify '(tiehi|tieh|tie1|tie_high|tieone)')"
TIE_LOW="$(classify '(tielo|tiel|tie0|tie_low|tiezero)')"

emit_report() {
  echo "# XH018 physical-cell candidate discovery"
  echo "status=UNCONFIRMED_CANDIDATES"
  echo "lef_count=${#LEF_FILES[@]}"
  echo "lib_count=${#LIB_FILES[@]}"
  echo "tap_candidates=${TAP:-}"
  echo "endcap_candidates=${ENDCAP:-}"
  echo "filler_candidates=${FILLER:-}"
  echo "decap_candidates=${DECAP:-}"
  echo "antenna_candidates=${ANTENNA:-}"
  echo "tie_high_candidates=${TIE_HIGH:-}"
  echo "tie_low_candidates=${TIE_LOW:-}"
}

emit_tcl() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  {
    echo "# Generated by discover_xh018_physical_cells.sh"
    echo "# Review before changing confirmed to 1 or selecting insertion cells."
    echo "array set mptdc_xh018_cells {"
    echo "    status              UNCONFIRMED_CANDIDATES"
    echo "    confirmed           0"
    echo "    tap                 {}"
    echo "    endcap_left         {}"
    echo "    endcap_right        {}"
    echo "    filler              {}"
    echo "    decap               {}"
    echo "    antenna             {}"
    echo "    tie_high            {}"
    echo "    tie_low             {}"
    echo "    source              {discover_xh018_physical_cells.sh}"
    echo "    tap_candidates      {${TAP:-}}"
    echo "    endcap_candidates   {${ENDCAP:-}}"
    echo "    filler_candidates   {${FILLER:-}}"
    echo "    decap_candidates    {${DECAP:-}}"
    echo "    antenna_candidates  {${ANTENNA:-}}"
    echo "    tie_high_candidates {${TIE_HIGH:-}}"
    echo "    tie_low_candidates  {${TIE_LOW:-}}"
    echo "}"
  } > "$path"
}

emit_report
if [[ -n "$OUT" ]]; then
  emit_tcl "$OUT"
  echo "wrote_tcl=$OUT"
fi
