#!/usr/bin/env bash
# Run and evidence-gate one MPTDC RO6 physical recovery stage.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
REPO_ROOT="${MPTDC_RECOVERY_REPO_ROOT:-$DEFAULT_REPO_ROOT}"
LAUNCHER="${MPTDC_RECOVERY_LAUNCHER:-$SCRIPT_DIR/server_run_mptdc_ro6_latestlef_simplepg.sh}"
SWEEP_LAUNCHER="${MPTDC_RECOVERY_SWEEP_LAUNCHER:-$SCRIPT_DIR/server_sweep_mptdc_pg_sroute_candidates.sh}"
REPAIR_LAUNCHER="${MPTDC_RECOVERY_REPAIR_LAUNCHER:-$SCRIPT_DIR/server_repair_mptdc_route_checkpoint.sh}"
PUBLISHER="${MPTDC_RECOVERY_PUBLISHER:-$REPO_ROOT/MPTDC/ci/publish_mptdc_server_snapshot.sh}"
INNOVUS_WORK="${MPTDC_INNOVUS_WORK:-/sim/ksabra/SPADMIC_work/innovus}"
WORK_ROOT="${MPTDC_WORK_ROOT:-/sim/ksabra/SPADMIC_work}"
DEFAULT_GENUS_RUN="MPTDC_TC_BufferedROTap0Pins_Genus_20260709_155623"
DEFAULT_ACCEPTED_PG_RUN="20260824_mptdc_bufftap0_simplepg_pgproof_135116"
DEFAULT_HALO_PNR_LEF="/sim/ksabra/SPADMIC_work/lef/RO_tune6_pnr_pin_access_tempblk_met3_20260824_151753.lef"
DEFAULT_HALO_PNR_LEF_SHA256="6788f856561a3e8c002dc7f2536ac338b16fc76b56aaae9d2062f4dccfec8469"

STAGE=""
RUN_ID=""
PG_RUN_ID=""
SOURCE_PG_RUN_ID="${MPTDC_SOURCE_PG_RUN_ID:-}"
SOURCE_PNR_RUN_ID="${MPTDC_SOURCE_PNR_RUN_ID:-}"
EXPECTED_HEAD_VALUE="${EXPECTED_HEAD:-}"
GENUS_RUN_ID="${MPTDC_GENUS_RUN_ID:-$DEFAULT_GENUS_RUN}"
HANDOFF_DIR="${MPTDC_GENUS_HANDOFF_DIR:-}"
SOURCE_LEF=""
PNR_LEF=""
PNR_LEF_SUMMARY=""
PNR_LEF_SUMMARY_BINDING_STATUS=NOT_REQUESTED
PRE_ROUTE_DANGLING_MAX=34
PRE_ROUTE_DANGLING_MAX_EXPLICIT=0
PRE_ROUTE_DANGLING_MODE=BASELINE_34
RO_HALOS=0
ALLOW_EXACT_PG_PVS_CANDIDATE=0
EXPECTED_HALO_GENUS_RUN_ID="${MPTDC_RECOVERY_EXPECTED_HALO_GENUS_RUN_ID:-$DEFAULT_GENUS_RUN}"
EXPECTED_HALO_PG_RUN_ID="${MPTDC_RECOVERY_EXPECTED_HALO_PG_RUN_ID:-$DEFAULT_ACCEPTED_PG_RUN}"
EXPECTED_HALO_PNR_LEF="${MPTDC_RECOVERY_EXPECTED_HALO_PNR_LEF:-$DEFAULT_HALO_PNR_LEF}"
EXPECTED_HALO_PNR_LEF_SHA256="${MPTDC_RECOVERY_EXPECTED_HALO_PNR_LEF_SHA256:-$DEFAULT_HALO_PNR_LEF_SHA256}"

usage() {
  cat <<'USAGE'
Usage:
  server_run_mptdc_ro6_recovery_stage.sh --stage <pg-proof|pg-sweep|physical-pnr|route-minarea-probe|route-minarea-repair|route-geometry-probe|route-geometry-repair> [options]

Options:
  --run-id <id>          Explicit result directory name. A unique id is generated by default.
  --pg-run-id <id>       Required for physical-pnr; identifies the published accepted PG proof.
  --source-pg-run-id <id>
                         Required for pg-sweep; identifies the published failed PG proof.
  --source-pnr-run-id <id>
                         Required for route-minarea-probe,
                         route-minarea-repair, route-geometry-probe, and
                         route-geometry-repair;
                         identifies the published failed physical PnR source.
  --expected-head <sha>  Require the checked-out repository HEAD.
  --genus-run-id <id>    Buffered-tap Genus run id.
  --handoff-dir <path>   PnR-compatible Genus handoff directory.
  --innovus-work <path>  Innovus result root.
  --work-root <path>     SPADMIC server work root.
  --source-lef <path>    Override the RO_tune6 LEF passed to the launcher.
  --pnr-lef <path>       PnR-only RO_tune6 LEF for physical-pnr. The imported
                         path and copied evidence hash must match exactly.
  --pre-route-dangling-max <34|35>
                         Physical-pnr pre-route continuation bound. Value 35 is
                         allowed only with the audited 13+13 marker-derived PnR
                         LEF.
  --ro-halos             Require audited 10 um hard placement halos around both
                         fixed RO macros. Required for physical-pnr.
  --allow-exact-pg-pvs-candidate
                         If geometry, timing, regular connectivity, halo, and
                         pin gates pass, allow only the exact audited 15
                         IMPVFC-94 VDD/VSS guarded-halo wire ends to proceed to
                         PVS. This is not an Innovus special-connectivity-clean
                         result.
  -h, --help             Show this help.

The stage runs in the foreground, writes an operator_gate report, and publishes
one bounded text-evidence snapshot. A failed physical gate is still published,
but the script returns nonzero and never launches the next stage.
USAGE
}

geometry_repair_source_signature_passes() {
  local marker_report="$1"
  local rel geometry_count min_area_count spacing_count short_count

  rel="${marker_report#"$REPO_ROOT"/}"
  git -C "$REPO_ROOT" ls-files --error-unmatch "$rel" >/dev/null 2>&1 || return 1
  [[ -s "$marker_report" ]] || return 1

  geometry_count="$(awk -F '\t' 'NR > 1 && $5 == "Geometry" {count++} END {print count + 0}' "$marker_report")"
  min_area_count="$(awk -F '\t' '
    NR > 1 && $3 == "{364.65 328.3 365.03 328.58}" && $4 == "MET1" &&
      $5 == "Geometry" && $6 == "Minimal_Area" &&
      $7 ~ /Regular Wire of Net u_core_n_57563/ {count++}
    END {print count + 0}
  ' "$marker_report")"
  spacing_count="$(awk -F '\t' '
    NR > 1 && $3 == "{219.94 223.775 219.96 224.505}" && $4 == "MET2" &&
      $5 == "Geometry" && $6 == "Parallel_Run_Length_Spacing" &&
      $7 ~ /Regular Wire of Net u_core_n_67240/ && $7 ~ /Special Wire of Net VDD/ {count++}
    END {print count + 0}
  ' "$marker_report")"
  short_count="$(awk -F '\t' '
    NR > 1 && $3 == "{220.5 179.29 220.76 180.015}" && $4 == "MET2" &&
      $5 == "Geometry" && $6 == "Metal_Short" &&
      $7 ~ /Regular Wire of Net u_core_n_66687/ && $7 ~ /Special Wire of Net VSS/ {count++}
    END {print count + 0}
  ' "$marker_report")"

  [[ "$geometry_count" == 5 && "$min_area_count" == 1 && \
     "$spacing_count" == 2 && "$short_count" == 2 ]]
}

min_area_probe_source_signature_passes() {
  local marker_report="$1"
  local rel geometry_count n57960_count n57556_count

  rel="${marker_report#"$REPO_ROOT"/}"
  git -C "$REPO_ROOT" ls-files --error-unmatch "$rel" >/dev/null 2>&1 || return 1
  [[ -s "$marker_report" ]] || return 1

  geometry_count="$(awk -F '\t' 'NR > 1 && $5 == "Geometry" {count++} END {print count + 0}' "$marker_report")"
  n57960_count="$(awk -F '\t' '
    NR > 1 && $3 == "{363.53 357.98 363.91 358.26}" && $4 == "MET1" &&
      $5 == "Geometry" && $6 == "Minimal_Area" &&
      $7 ~ /Regular Wire of Net u_core_n_57960/ &&
      $7 ~ /Actual: 0.10640000 Required: 0.20200000/ {count++}
    END {print count + 0}
  ' "$marker_report")"
  n57556_count="$(awk -F '\t' '
    NR > 1 && $3 == "{385.37 328.3 385.75 328.58}" && $4 == "MET1" &&
      $5 == "Geometry" && $6 == "Minimal_Area" &&
      $7 ~ /Regular Wire of Net u_core_n_57556/ &&
      $7 ~ /Actual: 0.10640000 Required: 0.20200000/ {count++}
    END {print count + 0}
  ' "$marker_report")"

  [[ "$geometry_count" == 2 && "$n57960_count" == 1 && "$n57556_count" == 1 ]]
}

special_dangling_count() {
  local report="$1"
  local count
  count="$(sed -nE 's/^[[:space:]]*([0-9]+) Problem\(s\) \(IMPVFC-94\):.*/\1/p' \
    "$report" 2>/dev/null | tail -1)"
  if [[ "$count" =~ ^[0-9]+$ ]]; then
    printf '%s\n' "$count"
  else
    printf 'MISSING\n'
  fi
}

special_connectivity_detail_report() {
  local report="$1"
  local detailed="${report%.rpt}_detailed.rpt"

  if grep -Eq '^Net (VDD|VSS): dangling Wire at ' "$report" 2>/dev/null; then
    printf '%s\n' "$report"
  elif [[ -s "$detailed" ]] && \
       grep -Eq '^Net (VDD|VSS): dangling Wire at ' "$detailed" 2>/dev/null; then
    printf '%s\n' "$detailed"
  else
    printf '%s\n' "$report"
  fi
}

special_dangling_only_report_passes() {
  local report="$1"
  local detail_report summary_count detail_count other_count

  [[ -s "$report" ]] || return 1
  detail_report="$(special_connectivity_detail_report "$report")"
  [[ -s "$detail_report" ]] || return 1
  summary_count="$(special_dangling_count "$report")"
  detail_count="$(grep -Ec '^Net (VDD|VSS): dangling Wire at ' "$detail_report" 2>/dev/null || true)"
  other_count="$(grep -E '^Net (VDD|VSS):' "$detail_report" 2>/dev/null \
    | grep -Evc ': dangling Wire at ' || true)"
  [[ "$summary_count" =~ ^[0-9]+$ && "$summary_count" -gt 0 && \
     "$detail_count" == "$summary_count" && "$other_count" == 0 ]]
}

run_route_geometry_probe_stage() {
  local source_checkpoint="$1"
  local probe_kind="${2:-legacy}"
  local probe_slug probe_step probe_stage probe_publish_label probe_next_stage
  local probe_method command_payload expected_drc expected_shorts expected_dangling
  local expected_target_count require_pin_geometry require_nearby_pg
  local commands_file commands_evidence probe_log operator_report
  local status_report="$RUN_DIR/reports/checkpoint_repair_status.rpt"
  local probe_report
  local probe_rc=99 decision=FAIL_STOP gate_mode=FAIL
  local initial_drc initial_shorts initial_regular initial_special initial_special_raw
  local initial_special_non_ro initial_special_report initial_dangling_count
  local final_drc final_shorts final_regular final_special final_special_raw
  local final_special_non_ro final_special_report final_dangling_count final_status
  local final_checkpoint_exists final_def command_status
  local probe_status target_net_count target_with_instterms target_with_pin_geometry
  local target_instterms target_instterm_pin_geometry
  local target_wires target_vias nearby_pg help_status help_pass_count
  local schema_status schema_pass_count
  local profile_geometry_ok=0 special_signature_ok=0
  local profile_geometry_status=FAIL special_signature_status=FAIL
  local tap_slow=0 tap_fast=0 tap_total=0 publish_rc=99 next_head

  case "$probe_kind" in
    legacy)
      probe_slug=route_geometry
      probe_step=ROUTE_GEOMETRY_PROBE
      probe_stage=ROUTE_GEOMETRY_PROBE
      probe_publish_label=ROUTE_GEOMETRY_PROBE
      probe_next_stage=REVIEW_ROUTE_GEOMETRY_PROBE
      probe_method=READ_ONLY_TARGET_NET_PIN_WIRE_VIA_PG_GEOMETRY
      command_payload='mptdc_ckpt_probe_target_geometry {u_core_n_66687 u_core_n_67240 u_core_n_57563}'
      expected_drc=3
      expected_shorts=1
      expected_dangling=12
      expected_target_count=3
      require_pin_geometry=1
      require_nearby_pg=1
      ;;
    minarea)
      probe_slug=route_min_area
      probe_step=ROUTE_MIN_AREA_PROBE
      probe_stage=ROUTE_MIN_AREA_PROBE
      probe_publish_label=ROUTE_MIN_AREA_PROBE
      probe_next_stage=REVIEW_ROUTE_MIN_AREA_PROBE
      probe_method=READ_ONLY_TWO_MET1_MIN_AREA_LANDING_GEOMETRY
      command_payload='mptdc_ckpt_probe_target_geometry {u_core_n_57960 u_core_n_57556}'
      expected_drc=2
      expected_shorts=0
      expected_dangling=15
      expected_target_count=2
      require_pin_geometry=0
      require_nearby_pg=0
      ;;
    *)
      echo "STOP: unsupported route geometry probe kind: $probe_kind"
      return 2
      ;;
  esac

  commands_file="$RUN_DIR/manifests/${probe_slug}_probe.commands.tcl"
  commands_evidence="$RUN_DIR/manifests/${probe_slug}_probe_commands.rpt"
  probe_log="$RUN_DIR/logs/${probe_slug}_probe_driver.log"
  probe_report="$RUN_DIR/reports/${probe_slug}_target_probe.rpt"
  operator_report="$RUN_DIR/reports/operator_gate_${probe_slug}_probe.rpt"

  mkdir -p "$RUN_DIR/reports" "$RUN_DIR/logs" "$RUN_DIR/manifests"
  printf '%s\n' "$command_payload" > "$commands_file"
  {
    echo "# Exact read-only command payload supplied to Innovus"
    echo "SOURCE_PNR_RUN_ID=$SOURCE_PNR_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "PROBE_METHOD=$probe_method"
    cat "$commands_file"
  } > "$commands_evidence"

  set +e
  bash "$REPAIR_LAUNCHER" \
    --run-id "$RUN_ID" \
    --checkpoint "$source_checkpoint" \
    --commands-file "$commands_file" \
    --expected-head "$EXPECTED_HEAD_VALUE" \
    --innovus-work "$INNOVUS_WORK" \
    2>&1 | tee "$probe_log"
  probe_rc=${PIPESTATUS[0]}
  set +e

  initial_drc="$(report_value "$status_report" INITIAL_DRC)"
  initial_shorts="$(report_value "$status_report" INITIAL_SHORTS)"
  initial_regular="$(report_value "$status_report" INITIAL_REGULAR_CONNECTIVITY_BAD)"
  initial_special="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_BAD)"
  initial_special_raw="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD)"
  initial_special_non_ro="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  initial_special_report="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_REPORT)"
  initial_dangling_count="$(special_dangling_count "$initial_special_report")"

  final_drc="$(report_value "$status_report" FINAL_DRC)"
  final_shorts="$(report_value "$status_report" FINAL_SHORTS)"
  final_regular="$(report_value "$status_report" FINAL_REGULAR_CONNECTIVITY_BAD)"
  final_special="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_BAD)"
  final_special_raw="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_RAW_BAD)"
  final_special_non_ro="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  final_special_report="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_REPORT)"
  final_dangling_count="$(special_dangling_count "$final_special_report")"
  final_status="$(report_value "$status_report" CHECKPOINT_REPAIR_STATUS)"
  final_checkpoint_exists="$(report_value "$status_report" FINAL_CHECKPOINT_DAT_EXISTS)"
  final_def="$(report_value "$status_report" FINAL_DEF)"
  command_status="$(report_value "$status_report" COMMAND_1_STATUS)"

  probe_status="$(report_value "$probe_report" PROBE_STATUS)"
  target_net_count="$(report_value "$probe_report" TARGET_NET_COUNT)"
  target_with_instterms="$(report_value "$probe_report" TARGET_NET_WITH_INSTTERMS_COUNT)"
  target_with_pin_geometry="$(report_value "$probe_report" TARGET_NET_WITH_PIN_GEOMETRY_COUNT)"
  target_instterms="$(report_value "$probe_report" TARGET_INSTTERM_COUNT)"
  target_instterm_pin_geometry="$(report_value "$probe_report" TARGET_INSTTERM_PIN_GEOMETRY_COUNT)"
  target_wires="$(report_value "$probe_report" TARGET_WIRE_COUNT)"
  target_vias="$(report_value "$probe_report" TARGET_VIA_COUNT)"
  nearby_pg="$(report_value "$probe_report" NEARBY_PG_SHAPE_COUNT)"
  help_status="$(report_value "$probe_report" HELP_CAPTURE_STATUS)"
  help_pass_count="$(report_value "$probe_report" HELP_CAPTURE_PASS_COUNT)"
  schema_status="$(report_value "$probe_report" SCHEMA_CAPTURE_STATUS)"
  schema_pass_count="$(report_value "$probe_report" SCHEMA_CAPTURE_PASS_COUNT)"

  if [[ -s "$final_def" ]]; then
    tap_slow="$(tap_def_count "$final_def" ro_slow_tap0_o)"
    tap_fast="$(tap_def_count "$final_def" ro_fast_tap0_o)"
    tap_total="$(tap_def_total "$final_def")"
    write_tap_excerpt "$final_def" "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
  else
    printf 'ROUTE_DEF=MISSING\nRO_TAP_OBSERVABILITY_PIN_COUNT=0\n' \
      > "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
  fi

  if [[ "$target_net_count" == "$expected_target_count" && \
        "$target_with_instterms" == "$expected_target_count" && \
        "$target_instterms" =~ ^[0-9]+$ && "$target_instterms" -gt 0 && \
        "$target_wires" =~ ^[0-9]+$ && "$target_wires" -gt 0 && \
        "$target_vias" =~ ^[0-9]+$ && \
        "$target_instterm_pin_geometry" =~ ^[0-9]+$ && \
        "$nearby_pg" =~ ^[0-9]+$ ]]; then
    if [[ "$require_pin_geometry" == 0 || \
          "$target_with_pin_geometry" == "$expected_target_count" ]]; then
      if [[ "$require_nearby_pg" == 0 || "$nearby_pg" -gt 0 ]]; then
        profile_geometry_ok=1
      fi
    fi
  fi

  if [[ "$probe_kind" == minarea ]]; then
    if exact_pg_wire_end_report_passes "$initial_special_report" && \
       exact_pg_wire_end_report_passes "$final_special_report"; then
      special_signature_ok=1
    fi
  elif special_dangling_only_report_passes "$initial_special_report" && \
       special_dangling_only_report_passes "$final_special_report"; then
    special_signature_ok=1
  fi
  [[ "$profile_geometry_ok" == 1 ]] && profile_geometry_status=PASS
  [[ "$special_signature_ok" == 1 ]] && special_signature_status=PASS

  if [[ "$probe_rc" -eq 0 && "$command_status" == PASS && \
        "$initial_drc" == "$expected_drc" && "$initial_shorts" == "$expected_shorts" && \
        "$initial_regular" == 0 && "$initial_special" == 1 && \
        "$initial_special_raw" == 1 && "$initial_special_non_ro" == 0 && \
        "$initial_dangling_count" == "$expected_dangling" && \
        "$final_drc" == "$expected_drc" && "$final_shorts" == "$expected_shorts" && \
        "$final_regular" == 0 && "$final_special" == 1 && \
        "$final_special_raw" == 1 && "$final_special_non_ro" == 0 && \
        "$final_dangling_count" == "$expected_dangling" && \
        "$final_status" == REVIEW_REQUIRED && "$final_checkpoint_exists" == 1 && \
        "$probe_status" == PASS && "$profile_geometry_ok" == 1 && \
        "$special_signature_ok" == 1 && "$help_status" == PASS && \
        "$help_pass_count" =~ ^[0-9]+$ && "$help_pass_count" -gt 0 && \
        "$schema_status" == PASS && "$schema_pass_count" =~ ^[0-9]+$ && \
        "$schema_pass_count" -gt 0 && "$tap_slow" == 1 && \
        "$tap_fast" == 1 && "$tap_total" == 2 ]]; then
    gate_mode=READ_ONLY_BASELINE_PRESERVED
    decision=PASS_CONTINUE
  fi

  {
    echo "STEP=$probe_step"
    echo "SOURCE_PNR_RUN_ID=$SOURCE_PNR_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "PROBE_RC=$probe_rc"
    echo "PROBE_METHOD=$probe_method"
    echo "COMMAND_1_STATUS=$command_status"
    echo "INITIAL_DRC=$initial_drc"
    echo "INITIAL_SHORTS=$initial_shorts"
    echo "INITIAL_REGULAR_CONNECTIVITY_BAD=$initial_regular"
    echo "INITIAL_SPECIAL_CONNECTIVITY_BAD=$initial_special"
    echo "INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD=$initial_special_raw"
    echo "INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$initial_special_non_ro"
    echo "INITIAL_SPECIAL_DANGLING_COUNT=$initial_dangling_count"
    echo "FINAL_DRC=$final_drc"
    echo "FINAL_SHORTS=$final_shorts"
    echo "FINAL_REGULAR_CONNECTIVITY_BAD=$final_regular"
    echo "FINAL_SPECIAL_CONNECTIVITY_BAD=$final_special"
    echo "FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=$final_special_raw"
    echo "FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$final_special_non_ro"
    echo "FINAL_SPECIAL_DANGLING_COUNT=$final_dangling_count"
    echo "CHECKPOINT_REPAIR_STATUS=$final_status"
    echo "FINAL_CHECKPOINT_DAT_EXISTS=$final_checkpoint_exists"
    echo "PROBE_STATUS=$probe_status"
    echo "TARGET_NET_COUNT=$target_net_count"
    echo "TARGET_NET_WITH_INSTTERMS_COUNT=$target_with_instterms"
    echo "TARGET_NET_WITH_PIN_GEOMETRY_COUNT=$target_with_pin_geometry"
    echo "TARGET_INSTTERM_COUNT=$target_instterms"
    echo "TARGET_INSTTERM_PIN_GEOMETRY_COUNT=$target_instterm_pin_geometry"
    echo "TARGET_WIRE_COUNT=$target_wires"
    echo "TARGET_VIA_COUNT=$target_vias"
    echo "NEARBY_PG_SHAPE_COUNT=$nearby_pg"
    echo "HELP_CAPTURE_STATUS=$help_status"
    echo "HELP_CAPTURE_PASS_COUNT=$help_pass_count"
    echo "SCHEMA_CAPTURE_STATUS=$schema_status"
    echo "SCHEMA_CAPTURE_PASS_COUNT=$schema_pass_count"
    echo "PROFILE_GEOMETRY_STATUS=$profile_geometry_status"
    echo "SPECIAL_SIGNATURE_STATUS=$special_signature_status"
    echo "ro_slow_tap0_o_COUNT=$tap_slow"
    echo "ro_fast_tap0_o_COUNT=$tap_fast"
    echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$tap_total"
    echo "PROBE_GATE_MODE=$gate_mode"
    echo "DECISION=$decision"
  } | tee "$operator_report"

  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" "$probe_publish_label"
  publish_rc=$?
  next_head="$(git rev-parse HEAD 2>/dev/null)"

  echo "RECOVERY_STAGE=$probe_stage"
  echo "RECOVERY_RUN_ID=$RUN_ID"
  echo "TOOL_RC=$probe_rc"
  echo "DECISION=$decision"
  echo "PUBLISH_RC=$publish_rc"
  echo "NEXT_EXPECTED_HEAD=$next_head"
  if [[ "$decision" == PASS_CONTINUE && "$publish_rc" -eq 0 ]]; then
    echo "NEXT_STAGE=$probe_next_stage"
    echo "NEXT_REQUIRED_PROBE_RUN_ID=$RUN_ID"
    return 0
  fi
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
  return 1
}

run_route_minarea_repair_stage() {
  local source_checkpoint="$1"
  local commands_file="$RUN_DIR/manifests/route_minarea_repair.commands.tcl"
  local commands_evidence="$RUN_DIR/manifests/route_minarea_repair_commands.rpt"
  local repair_log="$RUN_DIR/logs/route_minarea_repair_driver.log"
  local status_report="$RUN_DIR/reports/checkpoint_repair_status.rpt"
  local manual_eco_report="$RUN_DIR/reports/min_area_landing_patch_v1.rpt"
  local timing_report="$RUN_DIR/reports/extracted_timing_status.rpt"
  local drv_report="$RUN_DIR/reports/drv_status.rpt"
  local power_report="$RUN_DIR/reports/power_status.rpt"
  local repair_rc=99 decision=FAIL_STOP gate_mode=FAIL
  local initial_drc initial_shorts initial_regular initial_special initial_special_raw
  local initial_special_non_ro initial_special_report initial_dangling_count
  local final_drc final_shorts final_regular final_special final_special_raw
  local final_special_non_ro final_unrouted final_route_gate final_status
  local final_special_report final_dangling_count final_checkpoint_exists final_def
  local command_1_status command_2_status manual_eco_status
  local manual_pre_drc manual_pre_shorts manual_post_drc manual_post_shorts
  local setup_status hold_status drv_status power_status
  local special_signature_status=FAIL timing_gate_status=FAIL
  local tap_slow=0 tap_fast=0 tap_total=0 publish_rc=99 next_head

  mkdir -p "$RUN_DIR/reports" "$RUN_DIR/logs" "$RUN_DIR/manifests"
  cat > "$commands_file" <<'COMMANDS'
mptdc_ckpt_manual_two_minarea_landing_patch_v1
mptdc_signoff_extract_and_sta
COMMANDS
  {
    echo "# Exact bounded command payload supplied to Innovus"
    echo "SOURCE_PNR_RUN_ID=$SOURCE_PNR_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "REPAIR_METHOD=EXACT_TWO_VIA_LANDING_MIN_AREA_STUBS_V1"
    echo "REPAIR_STUB_POLICY=u_core_n_57960:MET1:363.72,358.12->364.56,358.12;u_core_n_57556:MET1:385.56,328.44->384.72,328.44;width=0.28"
    echo "TARGET_VIA_POLICY=u_core_n_57960:VIA1_o@363.72,358.12;u_core_n_57556:VIA1_o@385.56,328.44"
    echo "VIA_EDIT_POLICY=NO_VIAS_MODIFIED"
    echo "PG_EDIT_POLICY=NO_PG_SHAPES_MODIFIED"
    echo "PLACEMENT_EDIT_POLICY=NO_INSTANCES_MOVED"
    echo "POST_REPAIR_ANALYSIS=EXTRACT_RC_TC_SETUP_TC_HOLD_DRV_POWER"
    cat "$commands_file"
  } > "$commands_evidence"

  set +e
  bash "$REPAIR_LAUNCHER" \
    --run-id "$RUN_ID" \
    --checkpoint "$source_checkpoint" \
    --commands-file "$commands_file" \
    --expected-head "$EXPECTED_HEAD_VALUE" \
    --innovus-work "$INNOVUS_WORK" \
    2>&1 | tee "$repair_log"
  repair_rc=${PIPESTATUS[0]}
  set +e

  initial_drc="$(report_value "$status_report" INITIAL_DRC)"
  initial_shorts="$(report_value "$status_report" INITIAL_SHORTS)"
  initial_regular="$(report_value "$status_report" INITIAL_REGULAR_CONNECTIVITY_BAD)"
  initial_special="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_BAD)"
  initial_special_raw="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD)"
  initial_special_non_ro="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  initial_special_report="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_REPORT)"
  initial_dangling_count="$(special_dangling_count "$initial_special_report")"

  final_drc="$(report_value "$status_report" FINAL_DRC)"
  final_shorts="$(report_value "$status_report" FINAL_SHORTS)"
  final_regular="$(report_value "$status_report" FINAL_REGULAR_CONNECTIVITY_BAD)"
  final_special="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_BAD)"
  final_special_raw="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_RAW_BAD)"
  final_special_non_ro="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  final_unrouted="$(report_value "$status_report" FINAL_UNROUTED_NETS)"
  final_route_gate="$(report_value "$status_report" FINAL_ROUTE_GATE_PASS)"
  final_status="$(report_value "$status_report" CHECKPOINT_REPAIR_STATUS)"
  final_special_report="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_REPORT)"
  final_dangling_count="$(special_dangling_count "$final_special_report")"
  final_checkpoint_exists="$(report_value "$status_report" FINAL_CHECKPOINT_DAT_EXISTS)"
  final_def="$(report_value "$status_report" FINAL_DEF)"
  command_1_status="$(report_value "$status_report" COMMAND_1_STATUS)"
  command_2_status="$(report_value "$status_report" COMMAND_2_STATUS)"

  manual_eco_status="$(report_value "$manual_eco_report" MANUAL_ECO_STATUS)"
  manual_pre_drc="$(report_value "$manual_eco_report" PRE_DRC)"
  manual_pre_shorts="$(report_value "$manual_eco_report" PRE_SHORTS)"
  manual_post_drc="$(report_value "$manual_eco_report" POST_DRC)"
  manual_post_shorts="$(report_value "$manual_eco_report" POST_SHORTS)"
  setup_status="$(report_value "$timing_report" SETUP_STATUS_TC)"
  hold_status="$(report_value "$timing_report" TC_HOLD_STATUS)"
  drv_status="$(report_value "$drv_report" DRV_STATUS)"
  power_status="$(report_value "$power_report" POWER_REPORT_CAPTURE_STATUS)"

  if exact_pg_wire_end_report_passes "$initial_special_report" && \
     exact_pg_wire_end_report_passes "$final_special_report"; then
    special_signature_status=PASS
  fi
  if [[ "$command_2_status" == PASS && "$setup_status" == PASS && \
        "$hold_status" == PASS && "$drv_status" == PASS && \
        "$power_status" == PASS ]]; then
    timing_gate_status=PASS
  fi

  if [[ -s "$final_def" ]]; then
    tap_slow="$(tap_def_count "$final_def" ro_slow_tap0_o)"
    tap_fast="$(tap_def_count "$final_def" ro_fast_tap0_o)"
    tap_total="$(tap_def_total "$final_def")"
    write_tap_excerpt "$final_def" "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
  else
    printf 'ROUTE_DEF=MISSING\nRO_TAP_OBSERVABILITY_PIN_COUNT=0\n' \
      > "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
  fi

  if [[ "$repair_rc" -eq 0 && "$command_1_status" == PASS && \
        "$manual_eco_status" == PASS && "$manual_pre_drc" == 2 && \
        "$manual_pre_shorts" == 0 && "$manual_post_drc" == 0 && \
        "$manual_post_shorts" == 0 && "$initial_drc" == 2 && \
        "$initial_shorts" == 0 && "$initial_regular" == 0 && \
        "$initial_special" == 1 && "$initial_special_raw" == 1 && \
        "$initial_special_non_ro" == 0 && "$initial_dangling_count" == 15 && \
        "$final_drc" == 0 && "$final_shorts" == 0 && "$final_regular" == 0 && \
        "$final_special" == 1 && "$final_special_raw" == 1 && \
        "$final_special_non_ro" == 0 && "$final_dangling_count" == 15 && \
        "$final_route_gate" == 0 && \
        "$final_status" == PASS_GEOMETRY_REVIEW_CONNECTIVITY && \
        "$final_checkpoint_exists" == 1 && \
        "$special_signature_status" == PASS && "$timing_gate_status" == PASS && \
        "$tap_slow" == 1 && "$tap_fast" == 1 && "$tap_total" == 2 ]]; then
    gate_mode=PVS_CANDIDATE_EXACT_PG_WIRE_ENDS
    decision=PVS_CANDIDATE_CONTINUE
  fi

  {
    echo "STEP=ROUTE_MIN_AREA_REPAIR"
    echo "SOURCE_PNR_RUN_ID=$SOURCE_PNR_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "REPAIR_RC=$repair_rc"
    echo "REPAIR_METHOD=EXACT_TWO_VIA_LANDING_MIN_AREA_STUBS_V1"
    echo "REPAIR_STUB_POLICY=u_core_n_57960:MET1:363.72,358.12->364.56,358.12;u_core_n_57556:MET1:385.56,328.44->384.72,328.44;width=0.28"
    echo "TARGET_VIA_POLICY=u_core_n_57960:VIA1_o@363.72,358.12;u_core_n_57556:VIA1_o@385.56,328.44"
    echo "VIA_EDIT_POLICY=NO_VIAS_MODIFIED"
    echo "PG_EDIT_POLICY=NO_PG_SHAPES_MODIFIED"
    echo "PLACEMENT_EDIT_POLICY=NO_INSTANCES_MOVED"
    echo "COMMAND_1_STATUS=$command_1_status"
    echo "COMMAND_2_STATUS=$command_2_status"
    echo "MANUAL_ECO_STATUS=$manual_eco_status"
    echo "MANUAL_ECO_REPORT=$manual_eco_report"
    echo "INITIAL_DRC=$initial_drc"
    echo "INITIAL_SHORTS=$initial_shorts"
    echo "INITIAL_REGULAR_CONNECTIVITY_BAD=$initial_regular"
    echo "INITIAL_SPECIAL_CONNECTIVITY_BAD=$initial_special"
    echo "INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD=$initial_special_raw"
    echo "INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$initial_special_non_ro"
    echo "INITIAL_SPECIAL_DANGLING_COUNT=$initial_dangling_count"
    echo "FINAL_DRC=$final_drc"
    echo "FINAL_SHORTS=$final_shorts"
    echo "FINAL_REGULAR_CONNECTIVITY_BAD=$final_regular"
    echo "FINAL_SPECIAL_CONNECTIVITY_BAD=$final_special"
    echo "FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=$final_special_raw"
    echo "FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$final_special_non_ro"
    echo "FINAL_SPECIAL_DANGLING_COUNT=$final_dangling_count"
    echo "FINAL_UNROUTED_NETS=$final_unrouted"
    echo "FINAL_ROUTE_GATE_PASS=$final_route_gate"
    echo "CHECKPOINT_REPAIR_STATUS=$final_status"
    echo "FINAL_CHECKPOINT_DAT_EXISTS=$final_checkpoint_exists"
    echo "SPECIAL_SIGNATURE_STATUS=$special_signature_status"
    echo "SETUP_STATUS_TC=$setup_status"
    echo "TC_HOLD_STATUS=$hold_status"
    echo "DRV_STATUS=$drv_status"
    echo "POWER_REPORT_CAPTURE_STATUS=$power_status"
    echo "TIMING_GATE_STATUS=$timing_gate_status"
    echo "ro_slow_tap0_o_COUNT=$tap_slow"
    echo "ro_fast_tap0_o_COUNT=$tap_fast"
    echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$tap_total"
    echo "MINAREA_REPAIR_GATE_MODE=$gate_mode"
    echo "DECISION=$decision"
  } | tee "$RUN_DIR/reports/operator_gate_route_min_area_repair.rpt"

  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" ROUTE_MIN_AREA_REPAIR
  publish_rc=$?
  next_head="$(git rev-parse HEAD 2>/dev/null)"

  echo "RECOVERY_STAGE=ROUTE_MIN_AREA_REPAIR"
  echo "RECOVERY_RUN_ID=$RUN_ID"
  echo "TOOL_RC=$repair_rc"
  echo "DECISION=$decision"
  echo "PUBLISH_RC=$publish_rc"
  echo "NEXT_EXPECTED_HEAD=$next_head"
  echo "MINAREA_REPAIR_GATE_MODE=$gate_mode"
  if [[ "$decision" == PVS_CANDIDATE_CONTINUE && "$publish_rc" -eq 0 ]]; then
    echo "NEXT_STAGE=PVS"
    echo "NEXT_REQUIRED_PNR_RUN_ID=$RUN_ID"
    return 0
  fi
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
  return 1
}

run_route_geometry_repair_stage() {
  local source_checkpoint="$1"
  local commands_file="$RUN_DIR/manifests/route_geometry_repair.commands.tcl"
  local commands_evidence="$RUN_DIR/manifests/route_geometry_repair_commands.rpt"
  local repair_log="$RUN_DIR/logs/route_geometry_repair_driver.log"
  local status_report="$RUN_DIR/reports/checkpoint_repair_status.rpt"
  local repair_rc=99 decision=FAIL_STOP gate_mode=FAIL
  local initial_drc initial_shorts initial_regular initial_special initial_special_raw
  local initial_special_non_ro initial_special_report initial_dangling_count
  local final_drc final_shorts final_regular final_special final_special_raw
  local final_special_non_ro final_unrouted final_route_gate final_status
  local final_special_report final_dangling_count final_checkpoint_exists final_def
  local manual_eco_report="$RUN_DIR/reports/manual_geometry_eco_v7.rpt"
  local manual_eco_status=UNKNOWN
  local tap_slow=0 tap_fast=0 tap_total=0 publish_rc=99 next_head

  mkdir -p "$RUN_DIR/reports" "$RUN_DIR/logs" "$RUN_DIR/manifests"
  cat > "$commands_file" <<'COMMANDS'
mptdc_ckpt_manual_three_marker_eco_v7
COMMANDS
  {
    echo "# Exact bounded command payload supplied to Innovus"
    echo "SOURCE_PNR_RUN_ID=$SOURCE_PNR_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "REPAIR_METHOD=STAGED_BOUNDED_DRC_WIRE_DELETE_AND_MET2_TRUNK_SPLICE_V7"
    echo "VIA_DELETE_MODE=FULL_GEOMETRY_BOX_AND_EXACT_VIA_CELL"
    echo "OLD_MET2_LANDING_DELETE_MODE=BOUNDED_REGULAR_WIRE_WITH_DRC"
    echo "OBSOLETE_MET3_DELETE_MODE=BOUNDED_REGULAR_WIRE_ONLY"
    echo "VIA_INSERT_MODE=SINGLE_VIA1_ONLY"
    echo "STAGED_TUPLE_GATES=ENABLED"
    echo "REPAIR_VIA_ESCAPE_POLICY=u_core_n_66687:220.64,179.48->221.20,178.92;u_core_n_67240:219.80,224.14->221.20,223.58"
    echo "REPAIR_MET2_REMOTE_BRIDGE_POLICY=u_core_n_66687:221.20,178.92->224.84,179.48;u_core_n_67240:221.20,223.58->229.32,225.40"
    echo "REMOTE_VIA2_DELETE=u_core_n_66687:VIA2_o@224.84,179.48;u_core_n_67240:VIA2_o@229.32,225.40"
    echo "REMOTE_MET2_TRUNK_SPLICE=u_core_n_66687:224.84,179.48;u_core_n_67240:229.32,225.40"
    echo "REPAIR_MIN_AREA_PATCH_POLICY=u_core_n_57563:MET1:364.84,328.44->365.40,328.44:width=0.28"
    echo "PG_EDIT_POLICY=NO_PG_SHAPES_MODIFIED"
    echo "PLACEMENT_EDIT_POLICY=NO_INSTANCES_MOVED"
    cat "$commands_file"
  } > "$commands_evidence"

  set +e
  bash "$REPAIR_LAUNCHER" \
    --run-id "$RUN_ID" \
    --checkpoint "$source_checkpoint" \
    --commands-file "$commands_file" \
    --expected-head "$EXPECTED_HEAD_VALUE" \
    --innovus-work "$INNOVUS_WORK" \
    2>&1 | tee "$repair_log"
  repair_rc=${PIPESTATUS[0]}
  set +e

  initial_drc="$(report_value "$status_report" INITIAL_DRC)"
  initial_shorts="$(report_value "$status_report" INITIAL_SHORTS)"
  initial_regular="$(report_value "$status_report" INITIAL_REGULAR_CONNECTIVITY_BAD)"
  initial_special="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_BAD)"
  initial_special_raw="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD)"
  initial_special_non_ro="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  initial_special_report="$(report_value "$status_report" INITIAL_SPECIAL_CONNECTIVITY_REPORT)"
  initial_dangling_count="$(special_dangling_count "$initial_special_report")"

  final_drc="$(report_value "$status_report" FINAL_DRC)"
  final_shorts="$(report_value "$status_report" FINAL_SHORTS)"
  final_regular="$(report_value "$status_report" FINAL_REGULAR_CONNECTIVITY_BAD)"
  final_special="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_BAD)"
  final_special_raw="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_RAW_BAD)"
  final_special_non_ro="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  final_unrouted="$(report_value "$status_report" FINAL_UNROUTED_NETS)"
  final_route_gate="$(report_value "$status_report" FINAL_ROUTE_GATE_PASS)"
  final_status="$(report_value "$status_report" CHECKPOINT_REPAIR_STATUS)"
  final_special_report="$(report_value "$status_report" FINAL_SPECIAL_CONNECTIVITY_REPORT)"
  final_dangling_count="$(special_dangling_count "$final_special_report")"
  final_checkpoint_exists="$(report_value "$status_report" FINAL_CHECKPOINT_DAT_EXISTS)"
  final_def="$(report_value "$status_report" FINAL_DEF)"
  manual_eco_status="$(report_value "$manual_eco_report" MANUAL_ECO_STATUS)"

  if [[ -s "$final_def" ]]; then
    tap_slow="$(tap_def_count "$final_def" ro_slow_tap0_o)"
    tap_fast="$(tap_def_count "$final_def" ro_fast_tap0_o)"
    tap_total="$(tap_def_total "$final_def")"
    write_tap_excerpt "$final_def" "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
  else
    printf 'ROUTE_DEF=MISSING\nRO_TAP_OBSERVABILITY_PIN_COUNT=0\n' \
      > "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
  fi

  if [[ "$repair_rc" -eq 0 && "$manual_eco_status" == PASS && \
        "$initial_drc" == 3 && "$initial_shorts" == 1 && \
        "$initial_regular" == 0 && "$initial_special" == 1 && \
        "$initial_special_raw" == 1 && "$initial_special_non_ro" == 0 && \
        "$initial_dangling_count" == 12 && \
        "$final_drc" == 0 && "$final_shorts" == 0 && "$final_regular" == 0 && \
        "$final_special" == 0 && "$final_special_raw" == 0 && \
        "$final_special_non_ro" == 0 && "$final_unrouted" == 0 && \
        "$final_route_gate" == 1 && "$final_status" == PASS_ROUTE_GATE && \
        "$final_checkpoint_exists" == 1 && "$tap_slow" == 1 && \
        "$tap_fast" == 1 && "$tap_total" == 2 ]]; then
    gate_mode=FULL_ROUTE_GATE_CLEAN
    decision=PASS_CONTINUE
  elif [[ "$repair_rc" -eq 0 && "$manual_eco_status" == PASS && \
          "$initial_drc" == 3 && "$initial_shorts" == 1 && \
          "$initial_regular" == 0 && "$initial_special" == 1 && \
          "$initial_special_raw" == 1 && "$initial_special_non_ro" == 0 && \
          "$initial_dangling_count" == 12 && \
          "$final_drc" == 0 && "$final_shorts" == 0 && "$final_regular" == 0 && \
          "$final_special" == 1 && "$final_special_raw" == 1 && \
          "$final_special_non_ro" == 0 && "$final_dangling_count" =~ ^[0-9]+$ && \
          "$final_dangling_count" -gt 0 && "$final_dangling_count" -le 12 && \
          "$final_status" == PASS_GEOMETRY_REVIEW_CONNECTIVITY && \
          "$final_checkpoint_exists" == 1 && "$tap_slow" == 1 && \
          "$tap_fast" == 1 && "$tap_total" == 2 ]] && \
          special_dangling_only_report_passes "$initial_special_report" && \
          special_dangling_only_report_passes "$final_special_report"; then
    gate_mode=GEOMETRY_REGULAR_CLEAN_PG_DANGLING_REVIEW
    decision=PASS_CONTINUE
  fi

  {
    echo "STEP=ROUTE_GEOMETRY_REPAIR"
    echo "SOURCE_PNR_RUN_ID=$SOURCE_PNR_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "REPAIR_RC=$repair_rc"
    echo "MANUAL_ECO_STATUS=$manual_eco_status"
    echo "MANUAL_ECO_REPORT=$manual_eco_report"
    echo "REPAIR_METHOD=STAGED_BOUNDED_DRC_WIRE_DELETE_AND_MET2_TRUNK_SPLICE_V7"
    echo "VIA_DELETE_MODE=FULL_GEOMETRY_BOX_AND_EXACT_VIA_CELL"
    echo "OLD_MET2_LANDING_DELETE_MODE=BOUNDED_REGULAR_WIRE_WITH_DRC"
    echo "OBSOLETE_MET3_DELETE_MODE=BOUNDED_REGULAR_WIRE_ONLY"
    echo "VIA_INSERT_MODE=SINGLE_VIA1_ONLY"
    echo "STAGED_TUPLE_GATES=ENABLED"
    echo "REPAIR_VIA_ESCAPE_POLICY=u_core_n_66687:220.64,179.48->221.20,178.92;u_core_n_67240:219.80,224.14->221.20,223.58"
    echo "REPAIR_MET2_REMOTE_BRIDGE_POLICY=u_core_n_66687:221.20,178.92->224.84,179.48;u_core_n_67240:221.20,223.58->229.32,225.40"
    echo "REMOTE_VIA2_DELETE=u_core_n_66687:VIA2_o@224.84,179.48;u_core_n_67240:VIA2_o@229.32,225.40"
    echo "REMOTE_MET2_TRUNK_SPLICE=u_core_n_66687:224.84,179.48;u_core_n_67240:229.32,225.40"
    echo "REPAIR_MIN_AREA_PATCH_POLICY=u_core_n_57563:MET1:364.84,328.44->365.40,328.44:width=0.28"
    echo "PG_EDIT_POLICY=NO_PG_SHAPES_MODIFIED"
    echo "PLACEMENT_EDIT_POLICY=NO_INSTANCES_MOVED"
    echo "REPAIR_NETS=u_core_n_66687,u_core_n_67240,u_core_n_57563"
    echo "INITIAL_DRC=$initial_drc"
    echo "INITIAL_SHORTS=$initial_shorts"
    echo "INITIAL_REGULAR_CONNECTIVITY_BAD=$initial_regular"
    echo "INITIAL_SPECIAL_CONNECTIVITY_BAD=$initial_special"
    echo "INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD=$initial_special_raw"
    echo "INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$initial_special_non_ro"
    echo "INITIAL_SPECIAL_DANGLING_COUNT=$initial_dangling_count"
    echo "FINAL_DRC=$final_drc"
    echo "FINAL_SHORTS=$final_shorts"
    echo "FINAL_REGULAR_CONNECTIVITY_BAD=$final_regular"
    echo "FINAL_SPECIAL_CONNECTIVITY_BAD=$final_special"
    echo "FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=$final_special_raw"
    echo "FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$final_special_non_ro"
    echo "FINAL_SPECIAL_DANGLING_COUNT=$final_dangling_count"
    echo "FINAL_UNROUTED_NETS=$final_unrouted"
    echo "FINAL_ROUTE_GATE_PASS=$final_route_gate"
    echo "CHECKPOINT_REPAIR_STATUS=$final_status"
    echo "FINAL_CHECKPOINT_DAT_EXISTS=$final_checkpoint_exists"
    echo "ro_slow_tap0_o_COUNT=$tap_slow"
    echo "ro_fast_tap0_o_COUNT=$tap_fast"
    echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$tap_total"
    echo "GEOMETRY_REPAIR_GATE_MODE=$gate_mode"
    echo "DECISION=$decision"
  } | tee "$RUN_DIR/reports/operator_gate_route_geometry_repair.rpt"

  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" ROUTE_GEOMETRY_REPAIR
  publish_rc=$?
  next_head="$(git rev-parse HEAD 2>/dev/null)"

  echo "RECOVERY_STAGE=ROUTE_GEOMETRY_REPAIR"
  echo "RECOVERY_RUN_ID=$RUN_ID"
  echo "TOOL_RC=$repair_rc"
  echo "DECISION=$decision"
  echo "PUBLISH_RC=$publish_rc"
  echo "NEXT_EXPECTED_HEAD=$next_head"
  if [[ "$decision" == PASS_CONTINUE && "$publish_rc" -eq 0 ]]; then
    if [[ "$gate_mode" == FULL_ROUTE_GATE_CLEAN ]]; then
      echo "NEXT_STAGE=PVS"
      echo "NEXT_REQUIRED_PNR_RUN_ID=$RUN_ID"
    else
      echo "NEXT_STAGE=PG_DANGLING_REPAIR_REVIEW"
      echo "NEXT_REQUIRED_REPAIR_RUN_ID=$RUN_ID"
    fi
    return 0
  fi
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
  return 1
}

copy_sweep_candidate_evidence() {
  local summary_csv="$1"
  local candidate candidate_run_id rc strict_pg_clean strict_reasons
  local drc shorts regular_bad special_bad special_raw filter_status
  local filtered_ro non_ro unrouted route_gate checkpoint status_report
  local source_dir dest_dir file log

  while IFS=, read -r candidate candidate_run_id rc strict_pg_clean strict_reasons \
      drc shorts regular_bad special_bad special_raw filter_status filtered_ro \
      non_ro unrouted route_gate checkpoint status_report; do
    [[ "$candidate" == "candidate" || -z "$candidate" ]] && continue
    source_dir="$INNOVUS_WORK/$candidate_run_id"
    dest_dir="$RUN_DIR/reports/candidates/$candidate"
    mkdir -p "$dest_dir"

    for file in \
      "$source_dir/reports/checkpoint_repair_status.rpt" \
      "$source_dir"/reports/pg_candidate_*.rpt \
      "$source_dir"/reports/00_initial_verify_*.rpt \
      "$source_dir"/reports/00_initial_verify_drc_markers.tsv \
      "$source_dir"/reports/01_after_command_verify_*.rpt \
      "$source_dir"/reports/01_after_command_verify_drc_markers.tsv \
      "$source_dir"/reports/01_command_*.rpt; do
      [[ -f "$file" ]] && cp "$file" "$dest_dir/"
    done

    for log in \
      "$source_dir/logs/checkpoint_repair_wrapper.log" \
      "$source_dir/logs/innovus_route_checkpoint_repair.log"; do
      if [[ -f "$log" ]]; then
        grep -E '(^\*\*(WARN|ERROR|INFO)|\b(ERROR|WARN|FATAL|PASS|FAIL|STATUS|VIOL|short|SHORT)\b)' \
          "$log" | tail -n 320 \
          > "$RUN_DIR/logs/${candidate}_$(basename "$log").messages.tail" || true
      fi
    done
  done < "$summary_csv"
}

run_pg_sweep_stage() {
  local source_checkpoint="$1"
  local summary_csv="$INNOVUS_WORK/${RUN_ID}_summary.csv"
  local summary_md="$INNOVUS_WORK/${RUN_ID}_summary.md"
  local sweep_log candidate_count pass_count pass_candidates
  local sweep_rc decision sweep_status publish_rc next_head

  mkdir -p "$RUN_DIR/reports" "$RUN_DIR/logs" "$RUN_DIR/manifests"
  sweep_log="$RUN_DIR/logs/pg_sroute_sweep_driver.log"

  set +e
  bash "$SWEEP_LAUNCHER" \
    --checkpoint "$source_checkpoint" \
    --base-run-id "$RUN_ID" \
    --expected-head "$EXPECTED_HEAD_VALUE" \
    --innovus-work "$INNOVUS_WORK" \
    2>&1 | tee "$sweep_log"
  sweep_rc=${PIPESTATUS[0]}
  set +e

  if [[ -s "$summary_csv" ]]; then
    cp "$summary_csv" "$RUN_DIR/reports/pg_sroute_candidate_summary.csv"
    copy_sweep_candidate_evidence "$summary_csv"
    candidate_count="$(awk -F, 'NR > 1 && $1 != "" {count++} END {print count + 0}' "$summary_csv")"
    pass_count="$(awk -F, 'NR > 1 && $4 == "PASS" {count++} END {print count + 0}' "$summary_csv")"
    pass_candidates="$(awk -F, 'NR > 1 && $4 == "PASS" {print $1}' "$summary_csv" | paste -sd, -)"
  else
    candidate_count=0
    pass_count=0
    pass_candidates=""
  fi
  [[ -s "$summary_md" ]] && cp "$summary_md" "$RUN_DIR/reports/pg_sroute_candidate_summary.md"
  [[ -n "$pass_candidates" ]] || pass_candidates=NONE

  decision=FAIL_STOP
  sweep_status=FAIL_INCOMPLETE_OR_NO_STRICT_CANDIDATE
  if [[ "$sweep_rc" -eq 0 && "$candidate_count" -eq 10 && "$pass_count" -gt 0 ]]; then
    decision=PASS_CONTINUE
    sweep_status=PASS_STRICT_CANDIDATE_FOUND
  fi

  {
    echo "STEP=PG_SROUTE_SWEEP"
    echo "SOURCE_PG_RUN_ID=$SOURCE_PG_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "SWEEP_RC=$sweep_rc"
    echo "EXPECTED_CANDIDATE_COUNT=10"
    echo "CANDIDATE_COUNT=$candidate_count"
    echo "STRICT_PASS_COUNT=$pass_count"
    echo "STRICT_PASS_CANDIDATES=$pass_candidates"
    echo "PG_SROUTE_SWEEP_STATUS=$sweep_status"
    echo "DECISION=$decision"
  } | tee "$RUN_DIR/reports/operator_gate_pg_sroute_sweep.rpt"
  {
    echo "source_pg_run_id: $SOURCE_PG_RUN_ID"
    echo "source_checkpoint: $source_checkpoint"
    echo "head: $EXPECTED_HEAD_VALUE"
    echo "candidate_process_isolation: one fresh Innovus restore per candidate"
  } > "$RUN_DIR/manifests/pg_sroute_sweep_manifest.txt"

  publish_rc=99
  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" PG_SROUTE_SWEEP
  publish_rc=$?
  next_head="$(git rev-parse HEAD 2>/dev/null)"

  echo "RECOVERY_STAGE=PG_SROUTE_SWEEP"
  echo "RECOVERY_RUN_ID=$RUN_ID"
  echo "TOOL_RC=$sweep_rc"
  echo "CANDIDATE_COUNT=$candidate_count"
  echo "STRICT_PASS_COUNT=$pass_count"
  echo "STRICT_PASS_CANDIDATES=$pass_candidates"
  echo "DECISION=$decision"
  echo "PUBLISH_RC=$publish_rc"
  echo "NEXT_EXPECTED_HEAD=$next_head"
  if [[ "$decision" == PASS_CONTINUE && "$publish_rc" -eq 0 ]]; then
    echo "NEXT_STAGE=REVIEW_AND_REPLAY_PG_CANDIDATE"
    return 0
  fi
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
  return 1
}

report_value() {
  local report="$1"
  local key="$2"
  local value
  value="$(sed -n "s/^${key}=//p" "$report" 2>/dev/null | tail -1)"
  if [[ -n "$value" ]]; then
    printf '%s\n' "$value"
  else
    printf 'MISSING\n'
  fi
}

numeric_ge() {
  local actual="$1"
  local minimum="$2"
  awk -v actual="$actual" -v minimum="$minimum" \
    'BEGIN {exit !(actual ~ /^[-+]?[0-9]+([.][0-9]+)?$/ && actual + 0 >= minimum + 0)}'
}

expected_pg_wire_end_fingerprint() {
  printf '%s\n' \
    'VDD|MET3|221.750|681.160' \
    'VDD|MET3|48.000|681.160' \
    'VDD|MET3|221.750|201.160' \
    'VDD|MET3|48.000|201.160' \
    'VDD|METTP|121.160|233.620' \
    'VDD|METTP|121.160|648.320' \
    'VSS|MET3|221.750|685.160' \
    'VSS|MET3|48.000|685.160' \
    'VSS|MET3|221.750|205.160' \
    'VSS|MET3|48.000|205.160' \
    'VSS|METTP|205.160|158.320' \
    'VSS|METTP|125.160|721.750' \
    'VSS|METTP|125.160|648.320' \
    'VSS|METTP|125.160|233.620' \
    'VSS|METTP|125.160|158.320' | sort
}

actual_pg_wire_end_fingerprint() {
  local report="$1"
  awk '
    /^Net (VDD|VSS): dangling Wire at / {
      net=$2; sub(/:$/, "", net)
      x1=$6; y1=$7; x2=$8; y2=$9
      gsub(/[(),]/, "", x1); gsub(/[(),]/, "", y1)
      gsub(/[(),]/, "", x2); gsub(/[(),]/, "", y2)
      if ((x1 + 0) != (x2 + 0) || (y1 + 0) != (y2 + 0)) {
        print "INVALID_NON_POINT_WIRE_END"
      } else {
        printf "%s|%s|%.3f|%.3f\n", net, $12, x1, y1
      }
    }
  ' "$report" 2>/dev/null | sort
}

exact_pg_wire_end_report_passes() {
  local report="$1"
  local detail_report expected actual other_problem_count
  special_dangling_only_report_passes "$report" || return 1
  [[ "$(special_dangling_count "$report")" == 15 ]] || return 1
  detail_report="$(special_connectivity_detail_report "$report")"
  other_problem_count="$(grep -E 'Problem\(s\).*\(IMPVFC-' "$report" 2>/dev/null \
    | grep -Evc '\(IMPVFC-94\):[[:space:]]+The net has dangling wire\(s\)' || true)"
  [[ "$other_problem_count" == 0 ]] || return 1
  expected="$(expected_pg_wire_end_fingerprint)"
  actual="$(actual_pg_wire_end_fingerprint "$detail_report")"
  [[ "$actual" == "$expected" ]]
}

file_sha256() {
  local path="$1"
  if [[ -r "$path" ]]; then
    sha256sum "$path" | awk '{print $1}'
  else
    printf 'MISSING\n'
  fi
}

copy_pnr_lef_evidence() {
  local lef="$1"
  local summary="$2"
  local summary_sha=MISSING

  [[ -r "$lef" && -r "$summary" && -d "$RUN_DIR" ]] || return 1

  mkdir -p "$RUN_DIR/outputs"
  cp "$lef" "$RUN_DIR/outputs/RO_tune6_pnr_lef_used.txt" || return 1
  cp "$summary" "$RUN_DIR/outputs/RO_tune6_pnr_lef_summary.txt" || return 1
  summary_sha="$(file_sha256 "$summary")"
  {
    echo "PNR_LEF=$lef"
    echo "PNR_LEF_SHA256=$(file_sha256 "$lef")"
    echo "PNR_LEF_SUMMARY=$summary"
    echo "PNR_LEF_SUMMARY_SHA256=$summary_sha"
  } > "$RUN_DIR/outputs/RO_tune6_pnr_lef_evidence_manifest.txt"
}

load_cadence_env() {
  local env_file="$1"
  local source_rc=0

  echo "CADENCE_ENV=$env_file"
  if [[ ! -r "$env_file" ]]; then
    echo "CADENCE_ENV_RC=0"
    echo "CADENCE_ENV_STATUS=SKIPPED_NOT_READABLE"
    return 0
  fi

  # Site setup files are written for interactive shells and may read unset
  # variables. Keep the recovery driver's nounset policy outside this boundary.
  set +u
  set +e
  # shellcheck disable=SC1090
  source "$env_file" >/dev/null 2>&1
  source_rc=$?
  set +e
  set -u
  set -o pipefail

  echo "CADENCE_ENV_RC=$source_rc"
  if [[ "$source_rc" -eq 0 ]]; then
    echo "CADENCE_ENV_STATUS=PASS"
    return 0
  fi

  echo "CADENCE_ENV_STATUS=FAIL"
  return "$source_rc"
}

tracked_report_passes() {
  local report="$1"
  shift
  local rel key expected actual

  rel="${report#"$REPO_ROOT"/}"
  git -C "$REPO_ROOT" ls-files --error-unmatch "$rel" >/dev/null 2>&1 || return 1
  [[ -s "$report" ]] || return 1
  while [[ $# -gt 0 ]]; do
    key="$1"
    expected="$2"
    shift 2
    actual="$(report_value "$report" "$key")"
    [[ "$actual" == "$expected" ]] || return 1
  done
}

tracked_pg_report_passes() {
  local report="$1"
  local mode bad raw_bad dangling_status dangling_reason dangling_count
  local dangling_max dangling_fatal dangling_override

  if ! tracked_report_passes "$report" \
      STEP PG_PROOF PG_RC 0 \
      POSTPLACE_PRE_ROUTE_SROUTE_STATUS PASS \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES 0 \
      POSTPLACE_PRE_ROUTE_PG_DRC_CAPTURE_STATUS PASS \
      POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_STATUS PASS \
      POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT 0 \
      BLOCK_PG_PIN_STATUS PASS \
      BLOCK_PG_PIN_STYLE ring_aligned_vdd_vss_pair \
      BLOCK_PG_PIN_REQUESTED_COUNT 2 \
      DECISION PASS_CONTINUE; then
    return 1
  fi

  mode="$(report_value "$report" PG_GATE_MODE)"
  bad="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD)"
  raw_bad="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD)"
  if [[ "$mode" == RAW_CLEAN && "$bad" == 0 && "$raw_bad" == 0 ]]; then
    return 0
  fi
  [[ "$mode" == BOUNDED_DANGLING_CONTINUATION && "$bad" == 1 && "$raw_bad" == 1 ]] || return 1

  dangling_status="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_STATUS)"
  dangling_reason="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_REASON)"
  dangling_count="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_COUNT)"
  dangling_max="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_MAX)"
  dangling_fatal="$(report_value "$report" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_FATAL_COUNT)"
  dangling_override="$(report_value "$report" POSTPLACE_PRE_ROUTE_SROUTE_DANGLING_ONLY_OVERRIDE)"
  [[ "$dangling_status" == DANGLING_ONLY ]] || return 1
  [[ "$dangling_reason" == only_impvfc_94_dangling ]] || return 1
  [[ "$dangling_count" =~ ^[0-9]+$ && "$dangling_count" -gt 0 && "$dangling_count" -le 34 ]] || return 1
  [[ "$dangling_max" == 34 && "$dangling_fatal" == 0 && "$dangling_override" == 1 ]]
}

tap_plan_count() {
  local csv="$1"
  local wanted="$2"
  if [[ ! -s "$csv" ]]; then
    printf 'MISSING\n'
    return 0
  fi
  awk -F, -v wanted="$wanted" '
    NR > 1 {
      name=$1
      gsub(/^"|"$/, "", name)
      if (name == wanted && $3 == "SOUTH" && $4 == "MET3" && $5 == "REQUESTED") count++
    }
    END {print count + 0}
  ' "$csv" 2>/dev/null
}

tap_def_count() {
  local def="$1"
  local wanted="$2"
  awk -v wanted="$wanted" '
    /^PINS[[:space:]]/ {in_pins=1; next}
    /^END PINS/ {in_pins=0}
    in_pins && /^-[[:space:]]/ && $2 == wanted {count++}
    END {print count + 0}
  ' "$def" 2>/dev/null
}

tap_def_total() {
  local def="$1"
  awk '
    /^PINS[[:space:]]/ {in_pins=1; next}
    /^END PINS/ {in_pins=0}
    in_pins && /^-[[:space:]]/ && $2 ~ /^ro_(slow|fast)_tap[0-9]+_o$/ {count++}
    END {print count + 0}
  ' "$def" 2>/dev/null
}

write_tap_excerpt() {
  local def="$1"
  local out="$2"
  {
    echo "ROUTE_DEF=$def"
    echo "ro_slow_tap0_o_COUNT=$(tap_def_count "$def" ro_slow_tap0_o)"
    echo "ro_fast_tap0_o_COUNT=$(tap_def_count "$def" ro_fast_tap0_o)"
    echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$(tap_def_total "$def")"
    awk '
      /^PINS[[:space:]]/ {in_pins=1; next}
      /^END PINS/ {in_pins=0}
      in_pins && /^-[[:space:]]/ {
        if (active) print record
        active=($2 == "ro_slow_tap0_o" || $2 == "ro_fast_tap0_o")
        record=$0
        next
      }
      in_pins && active {record=record " " $0}
      END {if (active) print record}
    ' "$def"
  } > "$out"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage) STAGE="${2:?missing --stage value}"; shift 2 ;;
    --run-id) RUN_ID="${2:?missing --run-id value}"; shift 2 ;;
    --pg-run-id) PG_RUN_ID="${2:?missing --pg-run-id value}"; shift 2 ;;
    --source-pg-run-id) SOURCE_PG_RUN_ID="${2:?missing --source-pg-run-id value}"; shift 2 ;;
    --source-pnr-run-id) SOURCE_PNR_RUN_ID="${2:?missing --source-pnr-run-id value}"; shift 2 ;;
    --expected-head) EXPECTED_HEAD_VALUE="${2:?missing --expected-head value}"; shift 2 ;;
    --genus-run-id) GENUS_RUN_ID="${2:?missing --genus-run-id value}"; shift 2 ;;
    --handoff-dir) HANDOFF_DIR="${2:?missing --handoff-dir value}"; shift 2 ;;
    --innovus-work) INNOVUS_WORK="${2:?missing --innovus-work value}"; shift 2 ;;
    --work-root) WORK_ROOT="${2:?missing --work-root value}"; shift 2 ;;
    --source-lef) SOURCE_LEF="${2:?missing --source-lef value}"; shift 2 ;;
    --pnr-lef) PNR_LEF="${2:?missing --pnr-lef value}"; shift 2 ;;
    --pre-route-dangling-max)
      PRE_ROUTE_DANGLING_MAX="${2:?missing --pre-route-dangling-max value}"
      PRE_ROUTE_DANGLING_MAX_EXPLICIT=1
      shift 2
      ;;
    --ro-halos) RO_HALOS=1; shift ;;
    --allow-exact-pg-pvs-candidate) ALLOW_EXACT_PG_PVS_CANDIDATE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

case "$STAGE" in
  pg-proof|pg-sweep|physical-pnr|route-minarea-probe|route-minarea-repair|route-geometry-probe|route-geometry-repair) ;;
  *) echo "ERROR: --stage must be pg-proof, pg-sweep, physical-pnr, route-minarea-probe, route-minarea-repair, route-geometry-probe, or route-geometry-repair" >&2; usage >&2; exit 2 ;;
esac

if [[ -z "$HANDOFF_DIR" ]]; then
  HANDOFF_DIR="$WORK_ROOT/handoff/genus_typical_pnrcompat/$GENUS_RUN_ID"
fi

if [[ -z "$RUN_ID" ]]; then
  if [[ "$STAGE" == "pg-proof" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_simplepg_pgproof_$(date +%H%M%S)"
  elif [[ "$STAGE" == "pg-sweep" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_pgsweep_$(date +%H%M%S)"
  elif [[ "$STAGE" == "route-geometry-probe" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_route_geometry_probe_$(date +%H%M%S)"
  elif [[ "$STAGE" == "route-minarea-probe" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_route_minarea_probe_$(date +%H%M%S)"
  elif [[ "$STAGE" == "route-minarea-repair" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_route_minarea_repair_v1_$(date +%H%M%S)"
  elif [[ "$STAGE" == "route-geometry-repair" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_manual_geometry_repair_v7_$(date +%H%M%S)"
  else
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_halo10_physical_$(date +%H%M%S)"
  fi
fi
RUN_DIR="$INNOVUS_WORK/$RUN_ID"

if [[ -n "$PNR_LEF" && -r "$PNR_LEF" ]]; then
  PNR_LEF="$(readlink -f "$PNR_LEF" 2>/dev/null || printf '%s' "$PNR_LEF")"
  if [[ "$PNR_LEF" == *.lef ]]; then
    PNR_LEF_SUMMARY="${PNR_LEF%.lef}.summary.txt"
  else
    PNR_LEF_SUMMARY="${PNR_LEF}.summary.txt"
  fi
  if [[ -r "$PNR_LEF_SUMMARY" ]]; then
    SUMMARY_OUTPUT_LEF="$(report_value "$PNR_LEF_SUMMARY" OUTPUT_LEF)"
    SUMMARY_OUTPUT_SHA256="$(report_value "$PNR_LEF_SUMMARY" OUTPUT_LEF_SHA256)"
    if [[ -r "$SUMMARY_OUTPUT_LEF" ]]; then
      SUMMARY_OUTPUT_LEF="$(readlink -f "$SUMMARY_OUTPUT_LEF" 2>/dev/null || printf '%s' "$SUMMARY_OUTPUT_LEF")"
    fi
    if [[ "$(report_value "$PNR_LEF_SUMMARY" PNR_LEF_PREP_STATUS)" == PASS && \
          "$SUMMARY_OUTPUT_LEF" == "$PNR_LEF" && \
          "$SUMMARY_OUTPUT_SHA256" == "$(file_sha256 "$PNR_LEF")" ]]; then
      PNR_LEF_SUMMARY_BINDING_STATUS=PASS
    else
      PNR_LEF_SUMMARY_BINDING_STATUS=FAIL
    fi
  else
    PNR_LEF_SUMMARY_BINDING_STATUS=FAIL
  fi
fi
if [[ -r "$EXPECTED_HALO_PNR_LEF" ]]; then
  EXPECTED_HALO_PNR_LEF="$(readlink -f "$EXPECTED_HALO_PNR_LEF" 2>/dev/null || printf '%s' "$EXPECTED_HALO_PNR_LEF")"
fi

cd "$REPO_ROOT" || exit 3
ACTUAL_HEAD="$(git rev-parse HEAD 2>/dev/null)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
ORIGIN_HEAD="$(git rev-parse refs/remotes/origin/SPADMIC_test 2>/dev/null || true)"
EXPECTED_HEAD_VALUE="${EXPECTED_HEAD_VALUE:-${ORIGIN_HEAD:-$ACTUAL_HEAD}}"
TRACKED_STATUS="$(git status --short --untracked-files=no 2>/dev/null)"

echo "RECOVERY_STAGE=$STAGE"
echo "RUN_ID=$RUN_ID"
echo "RUN_DIR=$RUN_DIR"
echo "GENUS_RUN_ID=$GENUS_RUN_ID"
echo "HANDOFF_DIR=$HANDOFF_DIR"
echo "SOURCE_PG_RUN_ID=${SOURCE_PG_RUN_ID:-NONE}"
echo "SOURCE_PNR_RUN_ID=${SOURCE_PNR_RUN_ID:-NONE}"
echo "PNR_LEF=${PNR_LEF:-NOT_REQUESTED}"
echo "PNR_LEF_SUMMARY=${PNR_LEF_SUMMARY:-NOT_REQUESTED}"
echo "PNR_LEF_SUMMARY_BINDING_STATUS=$PNR_LEF_SUMMARY_BINDING_STATUS"
echo "PRE_ROUTE_DANGLING_MAX=$PRE_ROUTE_DANGLING_MAX"
echo "RO_HALOS=$RO_HALOS"
echo "ALLOW_EXACT_PG_PVS_CANDIDATE=$ALLOW_EXACT_PG_PVS_CANDIDATE"
echo "EXPECTED_HALO_GENUS_RUN_ID=$EXPECTED_HALO_GENUS_RUN_ID"
echo "EXPECTED_HALO_PG_RUN_ID=$EXPECTED_HALO_PG_RUN_ID"
echo "EXPECTED_HALO_PNR_LEF=$EXPECTED_HALO_PNR_LEF"
echo "EXPECTED_HALO_PNR_LEF_SHA256=$EXPECTED_HALO_PNR_LEF_SHA256"
echo "BRANCH=$BRANCH"
echo "ACTUAL_HEAD=$ACTUAL_HEAD"
echo "ORIGIN_HEAD=${ORIGIN_HEAD:-MISSING}"
echo "EXPECTED_HEAD=$EXPECTED_HEAD_VALUE"

PREFLIGHT=PASS
[[ "$BRANCH" == "SPADMIC_test" ]] || { echo "STOP: branch must be SPADMIC_test"; PREFLIGHT=FAIL; }
[[ "$ACTUAL_HEAD" == "$EXPECTED_HEAD_VALUE" ]] || { echo "STOP: HEAD mismatch"; PREFLIGHT=FAIL; }
[[ -z "$TRACKED_STATUS" ]] || { echo "$TRACKED_STATUS"; echo "STOP: tracked working tree is dirty"; PREFLIGHT=FAIL; }
[[ -f "$PUBLISHER" ]] || { echo "STOP: publisher missing: $PUBLISHER"; PREFLIGHT=FAIL; }
[[ ! -e "$RUN_DIR" ]] || { echo "STOP: run directory already exists: $RUN_DIR"; PREFLIGHT=FAIL; }
[[ "$RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "STOP: unsafe run id: $RUN_ID"; PREFLIGHT=FAIL; }
case "$STAGE" in
  pg-sweep)
    [[ -f "$SWEEP_LAUNCHER" ]] || { echo "STOP: sweep launcher missing: $SWEEP_LAUNCHER"; PREFLIGHT=FAIL; }
    ;;
  route-minarea-probe|route-minarea-repair|route-geometry-probe|route-geometry-repair)
    [[ -f "$REPAIR_LAUNCHER" ]] || { echo "STOP: checkpoint repair launcher missing: $REPAIR_LAUNCHER"; PREFLIGHT=FAIL; }
    ;;
  *)
    [[ -f "$LAUNCHER" ]] || { echo "STOP: launcher missing: $LAUNCHER"; PREFLIGHT=FAIL; }
    [[ -d "$HANDOFF_DIR" ]] || { echo "STOP: handoff missing: $HANDOFF_DIR"; PREFLIGHT=FAIL; }
    ;;
esac

PRE_PNR_REPORT=""
if [[ "$STAGE" == "pg-proof" ]]; then
  PRE_PNR_REPORT="$(find "$REPO_ROOT/MPTDC/docs/server_snapshots/genus" \
    -path "*/${GENUS_RUN_ID}_prepnr_*/reports/operator_gate_pre_pnr.rpt" \
    -type f 2>/dev/null | sort | tail -1)"
  if [[ -z "$PRE_PNR_REPORT" ]] || ! tracked_report_passes "$PRE_PNR_REPORT" \
      PACKAGE_RC 0 PRE_PNR_RC 0 PRE_PNR_GATE PASS DECISION PASS_CONTINUE; then
    echo "STOP: no tracked passing pre-PnR snapshot for $GENUS_RUN_ID"
    PREFLIGHT=FAIL
  fi
elif [[ "$STAGE" == "pg-sweep" ]]; then
  [[ -n "$SOURCE_PG_RUN_ID" ]] || { echo "STOP: --source-pg-run-id is required for pg-sweep"; PREFLIGHT=FAIL; }
  [[ "$SOURCE_PG_RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "STOP: unsafe source PG run id"; PREFLIGHT=FAIL; }
  SOURCE_PG_GATE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PG_RUN_ID/reports/operator_gate_pg_proof.rpt"
  SOURCE_PG_CHECKPOINT="$INNOVUS_WORK/$SOURCE_PG_RUN_ID/checkpoints/03_cts.enc.dat"
  if [[ -z "$SOURCE_PG_RUN_ID" ]] || ! tracked_report_passes "$SOURCE_PG_GATE" \
      STEP STRICT_PG_PROOF PG_RC 1 \
      POSTPLACE_PRE_ROUTE_SROUTE_STATUS FAIL \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD 1 \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD 1 \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES 0 \
      DECISION FAIL_STOP; then
    echo "STOP: tracked failed PG proof snapshot is missing or does not match: $SOURCE_PG_RUN_ID"
    PREFLIGHT=FAIL
  fi
  [[ -d "$SOURCE_PG_CHECKPOINT" ]] || { echo "STOP: clean pre-sroute checkpoint missing: $SOURCE_PG_CHECKPOINT"; PREFLIGHT=FAIL; }
elif [[ "$STAGE" == "physical-pnr" ]]; then
  [[ -n "$PG_RUN_ID" ]] || { echo "STOP: --pg-run-id is required for physical-pnr"; PREFLIGHT=FAIL; }
  PG_GATE_REPORT="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$PG_RUN_ID/reports/operator_gate_pg_proof.rpt"
  if [[ -z "$PG_RUN_ID" ]] || ! tracked_pg_report_passes "$PG_GATE_REPORT"; then
    echo "STOP: tracked accepted PG proof snapshot is missing or failed: $PG_RUN_ID"
    PREFLIGHT=FAIL
  fi
  if [[ -n "$PNR_LEF" ]]; then
    [[ -r "$PNR_LEF" ]] || { echo "STOP: PnR LEF is not readable: $PNR_LEF"; PREFLIGHT=FAIL; }
    [[ -r "$PNR_LEF_SUMMARY" ]] || { echo "STOP: PnR LEF summary is not readable: $PNR_LEF_SUMMARY"; PREFLIGHT=FAIL; }
    if [[ "$PNR_LEF_SUMMARY_BINDING_STATUS" != PASS ]]; then
      echo "STOP: PnR LEF summary does not bind PASS status to the requested path and hash"
      PREFLIGHT=FAIL
    fi
  fi
  if [[ "$RO_HALOS" != 1 ]]; then
    echo "STOP: physical-pnr requires --ro-halos"
    PREFLIGHT=FAIL
  fi
  if [[ "$GENUS_RUN_ID" != "$EXPECTED_HALO_GENUS_RUN_ID" ]]; then
    echo "STOP: halo recovery requires buffered Genus run $EXPECTED_HALO_GENUS_RUN_ID"
    PREFLIGHT=FAIL
  fi
  EXPECTED_HALO_HANDOFF="$WORK_ROOT/handoff/genus_typical_pnrcompat/$EXPECTED_HALO_GENUS_RUN_ID"
  if [[ -d "$HANDOFF_DIR" ]]; then
    HANDOFF_DIR_REAL="$(readlink -f "$HANDOFF_DIR" 2>/dev/null || printf '%s' "$HANDOFF_DIR")"
  else
    HANDOFF_DIR_REAL="$HANDOFF_DIR"
  fi
  if [[ -d "$EXPECTED_HALO_HANDOFF" ]]; then
    EXPECTED_HALO_HANDOFF="$(readlink -f "$EXPECTED_HALO_HANDOFF" 2>/dev/null || printf '%s' "$EXPECTED_HALO_HANDOFF")"
  fi
  if [[ "$HANDOFF_DIR_REAL" != "$EXPECTED_HALO_HANDOFF" ]]; then
    echo "STOP: halo recovery requires exact PnR-compatible handoff: $EXPECTED_HALO_HANDOFF"
    PREFLIGHT=FAIL
  fi
  if [[ "$PG_RUN_ID" != "$EXPECTED_HALO_PG_RUN_ID" ]]; then
    echo "STOP: halo recovery requires accepted PG proof $EXPECTED_HALO_PG_RUN_ID"
    PREFLIGHT=FAIL
  fi
  if [[ -z "$PNR_LEF" || "$PNR_LEF" != "$EXPECTED_HALO_PNR_LEF" || \
        "$(file_sha256 "$PNR_LEF")" != "$EXPECTED_HALO_PNR_LEF_SHA256" ]]; then
    echo "STOP: halo recovery requires the exact audited marker-access PnR LEF path and hash"
    PREFLIGHT=FAIL
  fi
elif [[ "$STAGE" == "route-minarea-probe" || "$STAGE" == "route-minarea-repair" ]]; then
  [[ -n "$SOURCE_PNR_RUN_ID" ]] || { echo "STOP: --source-pnr-run-id is required for $STAGE"; PREFLIGHT=FAIL; }
  [[ "$SOURCE_PNR_RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "STOP: unsafe source PnR run id"; PREFLIGHT=FAIL; }
  SOURCE_PNR_GATE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/operator_gate_physical_pnr.rpt"
  SOURCE_PNR_ROUTE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/route_status.rpt"
  SOURCE_PNR_MARKERS="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/route_drc_markers.tsv"
  SOURCE_PNR_SPECIAL_DETAIL="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/route_connectivity_special_detailed.rpt"
  SOURCE_PNR_CHECKPOINT="$INNOVUS_WORK/$SOURCE_PNR_RUN_ID/checkpoints/04_route_failed.enc.dat"
  if [[ -z "$SOURCE_PNR_RUN_ID" ]] || ! tracked_report_passes "$SOURCE_PNR_GATE" \
      STEP PHYSICAL_PNR PNR_RC 1 ROUTE_STATUS FAIL \
      INNOVUS_VERIFY_DRC_STATUS FAIL GEOMETRY_DRC_VIOLATIONS 2 SHORTS 0 \
      REGULAR_NET_CONNECTIVITY_BAD 0 SPECIAL_NET_CONNECTIVITY_BAD 1 \
      SPECIAL_NET_CONNECTIVITY_RAW_BAD 1 SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES 0 \
      RO_HALO_STATUS PASS RO_HALO_OCCUPANCY_STATUS PASS \
      RO_HALO_TOTAL_INTRUSION_COUNT 0 ro_slow_tap0_o_COUNT 1 \
      ro_fast_tap0_o_COUNT 1 RO_TAP_OBSERVABILITY_PIN_COUNT 2 DECISION FAIL_STOP; then
    echo "STOP: tracked 2-minarea/0-short halo physical gate is missing or does not match: $SOURCE_PNR_RUN_ID"
    PREFLIGHT=FAIL
  fi
  if [[ -z "$SOURCE_PNR_RUN_ID" ]] || ! tracked_report_passes "$SOURCE_PNR_ROUTE" \
      ROUTE_STATUS FAIL INNOVUS_VERIFY_DRC_STATUS FAIL \
      GEOMETRY_DRC_VIOLATIONS 2 SHORTS 0 REGULAR_NET_CONNECTIVITY_BAD 0 \
      SPECIAL_NET_CONNECTIVITY_BAD 1 SPECIAL_NET_CONNECTIVITY_RAW_BAD 1 \
      SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES 0 \
      ROUTE_GATE_FAILURE_CHECKPOINT_DAT_EXISTS 1; then
    echo "STOP: tracked two-minarea route status is missing or does not match: $SOURCE_PNR_RUN_ID"
    PREFLIGHT=FAIL
  fi
  if ! min_area_probe_source_signature_passes "$SOURCE_PNR_MARKERS"; then
    echo "STOP: source marker signature is not the exact two MET1 minimum-area set"
    PREFLIGHT=FAIL
  fi
  if ! exact_pg_wire_end_report_passes "$SOURCE_PNR_SPECIAL_DETAIL"; then
    echo "STOP: source special-connectivity report is not the exact 15-endpoint guarded profile"
    PREFLIGHT=FAIL
  fi
  [[ -d "$SOURCE_PNR_CHECKPOINT" ]] || { echo "STOP: failed-route checkpoint missing: $SOURCE_PNR_CHECKPOINT"; PREFLIGHT=FAIL; }
else
  [[ -n "$SOURCE_PNR_RUN_ID" ]] || { echo "STOP: --source-pnr-run-id is required for $STAGE"; PREFLIGHT=FAIL; }
  [[ "$SOURCE_PNR_RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "STOP: unsafe source PnR run id"; PREFLIGHT=FAIL; }
  SOURCE_PNR_GATE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/operator_gate_physical_pnr.rpt"
  SOURCE_PNR_ROUTE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/route_status.rpt"
  SOURCE_PNR_MARKERS="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PNR_RUN_ID/reports/route_drc_markers.tsv"
  SOURCE_PNR_CHECKPOINT="$INNOVUS_WORK/$SOURCE_PNR_RUN_ID/checkpoints/04_route_failed.enc.dat"
  if [[ -z "$SOURCE_PNR_RUN_ID" ]] || ! tracked_report_passes "$SOURCE_PNR_GATE" \
      STEP PHYSICAL_PNR PNR_RC 1 ROUTE_STATUS FAIL \
      INNOVUS_VERIFY_DRC_STATUS FAIL GEOMETRY_DRC_VIOLATIONS 3 SHORTS 1 \
      REGULAR_NET_CONNECTIVITY_BAD 0 SPECIAL_NET_CONNECTIVITY_BAD 1 \
      SPECIAL_NET_CONNECTIVITY_RAW_BAD 1 SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES 0 \
      ro_slow_tap0_o_COUNT 1 ro_fast_tap0_o_COUNT 1 \
      RO_TAP_OBSERVABILITY_PIN_COUNT 2 DECISION FAIL_STOP; then
    echo "STOP: tracked 3-DRC/1-short physical gate is missing or does not match: $SOURCE_PNR_RUN_ID"
    PREFLIGHT=FAIL
  fi
  if [[ -z "$SOURCE_PNR_RUN_ID" ]] || ! tracked_report_passes "$SOURCE_PNR_ROUTE" \
      ROUTE_STATUS FAIL INNOVUS_VERIFY_DRC_STATUS FAIL \
      GEOMETRY_DRC_VIOLATIONS 3 SHORTS 1 REGULAR_NET_CONNECTIVITY_BAD 0 \
      SPECIAL_NET_CONNECTIVITY_BAD 1 SPECIAL_NET_CONNECTIVITY_RAW_BAD 1 \
      SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES 0 \
      ROUTE_GATE_FAILURE_CHECKPOINT_DAT_EXISTS 1; then
    echo "STOP: tracked source route status is missing or does not match: $SOURCE_PNR_RUN_ID"
    PREFLIGHT=FAIL
  fi
  if ! geometry_repair_source_signature_passes "$SOURCE_PNR_MARKERS"; then
    echo "STOP: source geometry marker signature is not the exact 1+2+2 bounded set"
    PREFLIGHT=FAIL
  fi
  [[ -d "$SOURCE_PNR_CHECKPOINT" ]] || { echo "STOP: failed-route checkpoint missing: $SOURCE_PNR_CHECKPOINT"; PREFLIGHT=FAIL; }
fi
if [[ -n "$PNR_LEF" && "$STAGE" != "physical-pnr" ]]; then
  echo "STOP: --pnr-lef is only valid for physical-pnr"
  PREFLIGHT=FAIL
fi
if [[ -n "$SOURCE_PNR_RUN_ID" && "$STAGE" != "route-minarea-probe" && \
      "$STAGE" != "route-minarea-repair" && \
      "$STAGE" != "route-geometry-probe" && \
      "$STAGE" != "route-geometry-repair" ]]; then
  echo "STOP: --source-pnr-run-id is only valid for route-minarea-probe, route-minarea-repair, route-geometry-probe, or route-geometry-repair"
  PREFLIGHT=FAIL
fi
if [[ "$PRE_ROUTE_DANGLING_MAX" != 34 && "$PRE_ROUTE_DANGLING_MAX" != 35 ]]; then
  echo "STOP: --pre-route-dangling-max must be 34 or 35"
  PREFLIGHT=FAIL
fi
if [[ "$PRE_ROUTE_DANGLING_MAX_EXPLICIT" -eq 1 && "$STAGE" != "physical-pnr" ]]; then
  echo "STOP: --pre-route-dangling-max is only valid for physical-pnr"
  PREFLIGHT=FAIL
fi
if [[ "$RO_HALOS" -eq 1 && "$STAGE" != "physical-pnr" ]]; then
  echo "STOP: --ro-halos is only valid for physical-pnr"
  PREFLIGHT=FAIL
fi
if [[ "$ALLOW_EXACT_PG_PVS_CANDIDATE" -eq 1 && "$STAGE" != "physical-pnr" ]]; then
  echo "STOP: --allow-exact-pg-pvs-candidate is only valid for physical-pnr"
  PREFLIGHT=FAIL
fi
if [[ "$ALLOW_EXACT_PG_PVS_CANDIDATE" -eq 1 && "$RO_HALOS" != 1 ]]; then
  echo "STOP: exact PG PVS candidate mode requires --ro-halos"
  PREFLIGHT=FAIL
fi
if [[ "$STAGE" == "physical-pnr" && "$PRE_ROUTE_DANGLING_MAX" != 35 ]]; then
  echo "STOP: halo physical-pnr requires --pre-route-dangling-max 35"
  PREFLIGHT=FAIL
fi
if [[ "$PRE_ROUTE_DANGLING_MAX" == 35 ]]; then
  PRE_ROUTE_DANGLING_MODE=PNR_LEF_ONE_MARKER_CONTINUATION
  if [[ -z "$PNR_LEF" || "$PNR_LEF_SUMMARY_BINDING_STATUS" != PASS || \
        "$(report_value "$PNR_LEF_SUMMARY" REQUIRED_ACCESS_PIN_SET_STATUS)" != PASS || \
        "$(report_value "$PNR_LEF_SUMMARY" UNEXPECTED_ACCESS_PIN_COUNT)" != 0 || \
        "$(report_value "$PNR_LEF_SUMMARY" MET2_ACCESS_WINDOW_COUNT)" != 13 || \
        "$(report_value "$PNR_LEF_SUMMARY" MET3_ACCESS_WINDOW_COUNT)" != 13 ]]; then
    echo "STOP: dangling bound 35 requires the audited 13+13 marker-derived PnR LEF"
    PREFLIGHT=FAIL
  fi
fi
echo "PRE_ROUTE_DANGLING_MODE=$PRE_ROUTE_DANGLING_MODE"

echo "RECOVERY_PREFLIGHT=$PREFLIGHT"
if [[ "$PREFLIGHT" != "PASS" ]]; then
  echo "DECISION=FAIL_STOP"
  exit 4
fi

CADENCE_ENV="${MPTDC_CADENCE_ENV:-/eda/cadence/eda_2023-2024}"
if ! load_cadence_env "$CADENCE_ENV"; then
  echo "STOP: failed to source Cadence environment: $CADENCE_ENV"
  echo "DECISION=FAIL_STOP"
  exit 5
fi

if [[ "$STAGE" == "pg-sweep" ]]; then
  run_pg_sweep_stage "$SOURCE_PG_CHECKPOINT"
  exit $?
fi
if [[ "$STAGE" == "route-geometry-probe" ]]; then
  run_route_geometry_probe_stage "$SOURCE_PNR_CHECKPOINT" legacy
  exit $?
fi
if [[ "$STAGE" == "route-minarea-probe" ]]; then
  run_route_geometry_probe_stage "$SOURCE_PNR_CHECKPOINT" minarea
  exit $?
fi
if [[ "$STAGE" == "route-minarea-repair" ]]; then
  run_route_minarea_repair_stage "$SOURCE_PNR_CHECKPOINT"
  exit $?
fi
if [[ "$STAGE" == "route-geometry-repair" ]]; then
  run_route_geometry_repair_stage "$SOURCE_PNR_CHECKPOINT"
  exit $?
fi

LAUNCH_ARGS=(
  --run-id "$RUN_ID"
  --expected-head "$EXPECTED_HEAD_VALUE"
  --handoff-dir "$HANDOFF_DIR"
  --genus-run-id "$GENUS_RUN_ID"
  --innovus-work "$INNOVUS_WORK"
  --work-root "$WORK_ROOT"
  --no-free-all
  --local-phase-preplace
  --dangling-only-max "$PRE_ROUTE_DANGLING_MAX"
)
if [[ -n "$SOURCE_LEF" ]]; then
  LAUNCH_ARGS+=(--source-lef "$SOURCE_LEF")
fi
if [[ -n "$PNR_LEF" ]]; then
  LAUNCH_ARGS+=(--pnr-lef "$PNR_LEF")
fi
if [[ "$STAGE" == "pg-proof" ]]; then
  LAUNCH_ARGS+=(--stage pg_proof --no-signal-top-route-blockage)
else
  LAUNCH_ARGS+=(--stage full_closure --physical-first --post-filler-sroute \
    --temporary-signal-top-route-blockage)
  if [[ "$RO_HALOS" -eq 1 ]]; then
    LAUNCH_ARGS+=(--ro-halos)
  fi
  if [[ "$ALLOW_EXACT_PG_PVS_CANDIDATE" -eq 1 ]]; then
    LAUNCH_ARGS+=(--allow-exact-pg-pvs-candidate)
  fi
fi

set +e
bash "$LAUNCHER" "${LAUNCH_ARGS[@]}"
TOOL_RC=$?
set +e

PNR_LEF_EVIDENCE_STATUS=NOT_REQUESTED
PNR_LEF_REQUESTED_SHA256=NOT_REQUESTED
if [[ "$STAGE" == "physical-pnr" && -n "$PNR_LEF" ]]; then
  PNR_LEF_REQUESTED_SHA256="$(file_sha256 "$PNR_LEF")"
  if copy_pnr_lef_evidence "$PNR_LEF" "$PNR_LEF_SUMMARY"; then
    PNR_LEF_EVIDENCE_STATUS=PASS
  else
    PNR_LEF_EVIDENCE_STATUS=FAIL
  fi
fi

DECISION=FAIL_STOP
STEP_LABEL=UNKNOWN
if [[ "$STAGE" == "pg-proof" ]]; then
  STEP_LABEL=PG_PROOF
  STATUS_REPORT="$RUN_DIR/reports/postplace_pre_route_sroute_status.rpt"
  PG_SROUTE_STATUS="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SROUTE_STATUS)"
  PG_BAD="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD)"
  PG_RAW_BAD="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD)"
  PG_NON_RO_BAD="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  PG_DANGLING_STATUS="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_STATUS)"
  PG_DANGLING_REASON="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_REASON)"
  PG_DANGLING_COUNT="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_COUNT)"
  PG_DANGLING_MAX="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_MAX)"
  PG_DANGLING_FATAL="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_FATAL_COUNT)"
  PG_DANGLING_OVERRIDE="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SROUTE_DANGLING_ONLY_OVERRIDE)"
  PG_DRC_CAPTURE="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_PG_DRC_CAPTURE_STATUS)"
  PG_CROSS_SHORT_STATUS="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_STATUS)"
  PG_CROSS_SHORT_COUNT="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT)"
  BLOCK_PG_REPORT="$RUN_DIR/reports/block_pg_pin_status.rpt"
  BLOCK_PG_STATUS="$(report_value "$BLOCK_PG_REPORT" BLOCK_PG_PIN_STATUS)"
  BLOCK_PG_STYLE="$(report_value "$BLOCK_PG_REPORT" BLOCK_PG_PIN_STYLE)"
  BLOCK_PG_COUNT="$(report_value "$BLOCK_PG_REPORT" BLOCK_PG_PIN_REQUESTED_COUNT)"
  PG_GATE_MODE=FAIL
  if [[ "$TOOL_RC" -eq 0 && "$PG_SROUTE_STATUS" == PASS && "$PG_NON_RO_BAD" == 0 && \
        "$PG_DRC_CAPTURE" == PASS && "$PG_CROSS_SHORT_STATUS" == PASS && \
        "$PG_CROSS_SHORT_COUNT" == 0 && "$BLOCK_PG_STATUS" == PASS && \
        "$BLOCK_PG_STYLE" == ring_aligned_vdd_vss_pair && "$BLOCK_PG_COUNT" == 2 && \
        "$PG_BAD" == 0 && "$PG_RAW_BAD" == 0 ]]; then
    PG_GATE_MODE=RAW_CLEAN
    DECISION=PASS_CONTINUE
  elif [[ "$TOOL_RC" -eq 0 && "$PG_SROUTE_STATUS" == PASS && "$PG_NON_RO_BAD" == 0 && \
          "$PG_DRC_CAPTURE" == PASS && "$PG_CROSS_SHORT_STATUS" == PASS && \
          "$PG_CROSS_SHORT_COUNT" == 0 && "$BLOCK_PG_STATUS" == PASS && \
          "$BLOCK_PG_STYLE" == ring_aligned_vdd_vss_pair && "$BLOCK_PG_COUNT" == 2 && \
          "$PG_BAD" == 1 && "$PG_RAW_BAD" == 1 && \
          "$PG_DANGLING_STATUS" == DANGLING_ONLY && \
          "$PG_DANGLING_REASON" == only_impvfc_94_dangling && \
          "$PG_DANGLING_COUNT" =~ ^[0-9]+$ && "$PG_DANGLING_COUNT" -gt 0 && \
          "$PG_DANGLING_COUNT" -le 34 && "$PG_DANGLING_MAX" == 34 && \
          "$PG_DANGLING_FATAL" == 0 && "$PG_DANGLING_OVERRIDE" == 1 ]]; then
    PG_GATE_MODE=BOUNDED_DANGLING_CONTINUATION
    DECISION=PASS_CONTINUE
  fi
  if [[ -d "$RUN_DIR" ]]; then
    mkdir -p "$RUN_DIR/reports"
    {
      echo "STEP=$STEP_LABEL"
      echo "PG_RC=$TOOL_RC"
      echo "POSTPLACE_PRE_ROUTE_SROUTE_STATUS=$PG_SROUTE_STATUS"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD=$PG_BAD"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD=$PG_RAW_BAD"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$PG_NON_RO_BAD"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_STATUS=$PG_DANGLING_STATUS"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_REASON=$PG_DANGLING_REASON"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_COUNT=$PG_DANGLING_COUNT"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_MAX=$PG_DANGLING_MAX"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_FATAL_COUNT=$PG_DANGLING_FATAL"
      echo "POSTPLACE_PRE_ROUTE_SROUTE_DANGLING_ONLY_OVERRIDE=$PG_DANGLING_OVERRIDE"
      echo "POSTPLACE_PRE_ROUTE_PG_DRC_CAPTURE_STATUS=$PG_DRC_CAPTURE"
      echo "POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_STATUS=$PG_CROSS_SHORT_STATUS"
      echo "POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT=$PG_CROSS_SHORT_COUNT"
      echo "BLOCK_PG_PIN_STATUS=$BLOCK_PG_STATUS"
      echo "BLOCK_PG_PIN_STYLE=$BLOCK_PG_STYLE"
      echo "BLOCK_PG_PIN_REQUESTED_COUNT=$BLOCK_PG_COUNT"
      echo "PG_GATE_MODE=$PG_GATE_MODE"
      echo "DECISION=$DECISION"
    } | tee "$RUN_DIR/reports/operator_gate_pg_proof.rpt"
  fi
else
  STEP_LABEL=PHYSICAL_PNR
  ROUTE_REPORT="$RUN_DIR/reports/route_status.rpt"
  ROUTE_INTENT_REPORT="$RUN_DIR/reports/route_layer_intent.rpt"
  ROUTE_COMMAND_REPORT="$RUN_DIR/reports/route_command_status.rpt"
  SIGNAL_TOP_BLOCKAGE_REPORT="$RUN_DIR/reports/signal_top_route_blockage_status.rpt"
  PRE_ROUTE_REPORT="$RUN_DIR/reports/postplace_pre_route_sroute_status.rpt"
  RO_IMPORT_REPORT="$RUN_DIR/reports/ro_import_source_gate.rpt"
  RO_HALO_REPORT="$RUN_DIR/reports/ro_halo_status.rpt"
  RO_HALO_OCCUPANCY_REPORT="$RUN_DIR/reports/ro_halo_occupancy.rpt"
  RO_PHASE_REPORT="$RUN_DIR/reports/ro_phase_overlap_audit.rpt"
  PG_CANDIDATE_REPORT="$RUN_DIR/reports/route_pg_pvs_candidate_status.rpt"
  PG_CANDIDATE_DETAIL_REPORT="$RUN_DIR/reports/route_connectivity_special_detailed.rpt"
  EXTRACTED_TIMING_REPORT="$RUN_DIR/reports/extracted_timing_status.rpt"
  DRV_REPORT="$RUN_DIR/reports/drv_status.rpt"
  POWER_REPORT="$RUN_DIR/reports/power_status.rpt"
  DIGITAL_STATUS_REPORT="$RUN_DIR/reports/digital_pnr_signoff_status.rpt"
  IO_PIN_SUMMARY="$RUN_DIR/reports/io_pin_placement_summary.md"
  IO_PIN_CSV="$RUN_DIR/reports/io_pin_placement.csv"
  ROUTE_STATUS="$(report_value "$ROUTE_REPORT" ROUTE_STATUS)"
  DRC_STATUS="$(report_value "$ROUTE_REPORT" INNOVUS_VERIFY_DRC_STATUS)"
  GEOMETRY_DRC="$(report_value "$ROUTE_REPORT" GEOMETRY_DRC_VIOLATIONS)"
  SHORTS="$(report_value "$ROUTE_REPORT" SHORTS)"
  REGULAR_BAD="$(report_value "$ROUTE_REPORT" REGULAR_NET_CONNECTIVITY_BAD)"
  SPECIAL_BAD="$(report_value "$ROUTE_REPORT" SPECIAL_NET_CONNECTIVITY_BAD)"
  SPECIAL_RAW_BAD="$(report_value "$ROUTE_REPORT" SPECIAL_NET_CONNECTIVITY_RAW_BAD)"
  SPECIAL_NON_RO_BAD="$(report_value "$ROUTE_REPORT" SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES)"
  UNROUTED="$(report_value "$ROUTE_REPORT" UNROUTED_NETS)"
  ROUTER_TOP="$(report_value "$ROUTE_INTENT_REPORT" router_command_top_layer)"
  SIGNAL_TOP="$(report_value "$ROUTE_INTENT_REPORT" signal_top_layer)"
  ROUTE_COMMAND_STATUS="$(report_value "$ROUTE_COMMAND_REPORT" ROUTE_COMMAND_STATUS)"
  SIGNAL_TOP_BLOCKAGE_TEMPORARY="$(report_value "$SIGNAL_TOP_BLOCKAGE_REPORT" SIGNAL_TOP_ROUTE_BLOCKAGE_TEMPORARY)"
  SIGNAL_TOP_BLOCKAGE_CREATE="$(report_value "$SIGNAL_TOP_BLOCKAGE_REPORT" SIGNAL_TOP_ROUTE_BLOCKAGE_CREATE_STATUS)"
  SIGNAL_TOP_BLOCKAGE_REMOVE="$(report_value "$SIGNAL_TOP_BLOCKAGE_REPORT" SIGNAL_TOP_ROUTE_BLOCKAGE_REMOVE_STATUS)"
  SIGNAL_TOP_BLOCKAGE_STATUS="$(report_value "$SIGNAL_TOP_BLOCKAGE_REPORT" SIGNAL_TOP_ROUTE_BLOCKAGE_STATUS)"
  PRE_ROUTE_SROUTE_STATUS="$(report_value "$PRE_ROUTE_REPORT" POSTPLACE_PRE_ROUTE_SROUTE_STATUS)"
  PRE_ROUTE_DANGLING_STATUS="$(report_value "$PRE_ROUTE_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_ONLY_STATUS)"
  PRE_ROUTE_DANGLING_COUNT="$(report_value "$PRE_ROUTE_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_COUNT)"
  PRE_ROUTE_DANGLING_ACTUAL_MAX="$(report_value "$PRE_ROUTE_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_MAX)"
  PRE_ROUTE_DANGLING_FATAL="$(report_value "$PRE_ROUTE_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_DANGLING_FATAL_COUNT)"
  PRE_ROUTE_CROSS_SHORT_COUNT="$(report_value "$PRE_ROUTE_REPORT" POSTPLACE_PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT)"
  RO_HALO_ENABLED="$(report_value "$RO_HALO_REPORT" RO_HALO_ENABLED)"
  RO_HALO_STATUS="$(report_value "$RO_HALO_REPORT" RO_HALO_STATUS)"
  RO_HALO_COUNT="$(report_value "$RO_HALO_REPORT" RO_HALO_COUNT)"
  RO_HALO_CLEARANCE="$(report_value "$RO_HALO_REPORT" RO_PHASE_MIN_CLEARANCE_UM)"
  RO_HALO_GUARD_X="$(report_value "$RO_HALO_REPORT" RO_HALO_PLACER_GUARD_X_UM)"
  RO_HALO_GUARD_Y="$(report_value "$RO_HALO_REPORT" RO_HALO_PLACER_GUARD_Y_UM)"
  RO_HALO_PLACEMENT_CLEARANCE_X="$(report_value "$RO_HALO_REPORT" RO_HALO_PLACEMENT_CLEARANCE_X_UM)"
  RO_HALO_PLACEMENT_CLEARANCE_Y="$(report_value "$RO_HALO_REPORT" RO_HALO_PLACEMENT_CLEARANCE_Y_UM)"
  SLOW_HALO_STATUS="$(report_value "$RO_HALO_REPORT" SLOW_HALO_STATUS)"
  FAST_HALO_STATUS="$(report_value "$RO_HALO_REPORT" FAST_HALO_STATUS)"
  RO_HALO_OCCUPANCY_STATUS="$(report_value "$RO_HALO_OCCUPANCY_REPORT" RO_HALO_OCCUPANCY_STATUS)"
  RO_HALO_TOTAL_INTRUSIONS="$(report_value "$RO_HALO_OCCUPANCY_REPORT" RO_HALO_TOTAL_INTRUSION_COUNT)"
  RO_HALO_INVALID_BBOXES="$(report_value "$RO_HALO_OCCUPANCY_REPORT" RO_HALO_INVALID_INSTANCE_BBOX_COUNT)"
  RO_HALO_AUDITED_RO_COUNT="$(report_value "$RO_HALO_OCCUPANCY_REPORT" RO_TUNE6_COUNT)"
  RO_PHASE_STATUS="$(report_value "$RO_PHASE_REPORT" RO_PHASE_PLACEMENT_STATUS)"
  RO_PHASE_MIN_CLEARANCE="$(report_value "$RO_PHASE_REPORT" RO_PHASE_MIN_CLEARANCE_UM)"
  PG_CANDIDATE_STATUS="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_STATUS)"
  PG_CANDIDATE_PROFILE="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_PROFILE)"
  PG_CANDIDATE_EXPECTED_COUNT="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_EXPECTED_COUNT)"
  PG_CANDIDATE_ACTUAL_COUNT="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_ACTUAL_COUNT)"
  PG_CANDIDATE_SUMMARY_COUNT="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_SUMMARY_COUNT)"
  PG_CANDIDATE_EXACT_MATCH="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_EXACT_MATCH)"
  PG_CANDIDATE_OTHER_NET_LINES="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_OTHER_NET_LINE_COUNT)"
  PG_CANDIDATE_OTHER_PROBLEM_LINES="$(report_value "$PG_CANDIDATE_REPORT" ROUTE_PG_PVS_CANDIDATE_OTHER_PROBLEM_LINE_COUNT)"
  SETUP_STATUS_TC="$(report_value "$EXTRACTED_TIMING_REPORT" SETUP_STATUS_TC)"
  TC_HOLD_STATUS="$(report_value "$EXTRACTED_TIMING_REPORT" TC_HOLD_STATUS)"
  DRV_STATUS="$(report_value "$DRV_REPORT" DRV_STATUS)"
  POWER_REPORT_CAPTURE_STATUS="$(report_value "$POWER_REPORT" POWER_REPORT_CAPTURE_STATUS)"
  EXTRACTION_STATUS="$(report_value "$DIGITAL_STATUS_REPORT" EXTRACTION_STATUS)"
  ACTUAL_PNR_LEF="$(report_value "$RO_IMPORT_REPORT" O1_RO_LEF_PATH)"
  PNR_LEF_PATH_MATCH_STATUS=NOT_REQUESTED
  PNR_LEF_ACTUAL_SHA256=NOT_REQUESTED
  PNR_LEF_GATE_STATUS=PASS
  if [[ -n "$PNR_LEF" ]]; then
    if [[ -r "$ACTUAL_PNR_LEF" ]]; then
      ACTUAL_PNR_LEF="$(readlink -f "$ACTUAL_PNR_LEF" 2>/dev/null || printf '%s' "$ACTUAL_PNR_LEF")"
      PNR_LEF_ACTUAL_SHA256="$(file_sha256 "$ACTUAL_PNR_LEF")"
    else
      PNR_LEF_ACTUAL_SHA256=MISSING
    fi
    if [[ "$ACTUAL_PNR_LEF" == "$PNR_LEF" && \
          "$PNR_LEF_ACTUAL_SHA256" == "$PNR_LEF_REQUESTED_SHA256" ]]; then
      PNR_LEF_PATH_MATCH_STATUS=PASS
    else
      PNR_LEF_PATH_MATCH_STATUS=FAIL
    fi
    if [[ "$PNR_LEF_SUMMARY_BINDING_STATUS" != PASS || \
          "$PNR_LEF_PATH_MATCH_STATUS" != PASS || "$PNR_LEF_EVIDENCE_STATUS" != PASS ]]; then
      PNR_LEF_GATE_STATUS=FAIL
    fi
  fi
  IO_PIN_STATUS="$(report_value "$IO_PIN_SUMMARY" REPORT_STATUS)"
  TAP_SLOW_PLAN="$(tap_plan_count "$IO_PIN_CSV" ro_slow_tap0_o)"
  TAP_FAST_PLAN="$(tap_plan_count "$IO_PIN_CSV" ro_fast_tap0_o)"
  ROUTE_DEF=""
  for candidate in "$RUN_DIR/def/04_route.def" "$RUN_DIR/def/04_route_failed.def"; do
    if [[ -s "$candidate" ]]; then ROUTE_DEF="$candidate"; break; fi
  done
  TAP_SLOW_COUNT=0
  TAP_FAST_COUNT=0
  TAP_TOTAL_COUNT=0
  if [[ -n "$ROUTE_DEF" ]]; then
    TAP_SLOW_COUNT="$(tap_def_count "$ROUTE_DEF" ro_slow_tap0_o)"
    TAP_FAST_COUNT="$(tap_def_count "$ROUTE_DEF" ro_fast_tap0_o)"
    TAP_TOTAL_COUNT="$(tap_def_total "$ROUTE_DEF")"
  fi
  PHYSICAL_GATE_MODE=FAIL
  COMMON_PHYSICAL_GATE=0
  if [[ "$TOOL_RC" -eq 0 && "$DRC_STATUS" == PASS && \
        "$GEOMETRY_DRC" == 0 && "$SHORTS" == 0 && "$REGULAR_BAD" == 0 && \
        "$SPECIAL_NON_RO_BAD" == 0 && "$UNROUTED" == 0 && \
        "$SIGNAL_TOP" == MET3 && "$ROUTER_TOP" == METTP && \
        "$ROUTE_COMMAND_STATUS" == PASS && "$SIGNAL_TOP_BLOCKAGE_TEMPORARY" == 1 && \
        "$SIGNAL_TOP_BLOCKAGE_CREATE" == PASS && "$SIGNAL_TOP_BLOCKAGE_REMOVE" == PASS && \
        "$SIGNAL_TOP_BLOCKAGE_STATUS" == REMOVED && "$PRE_ROUTE_SROUTE_STATUS" == PASS && \
        "$PRE_ROUTE_DANGLING_ACTUAL_MAX" == "$PRE_ROUTE_DANGLING_MAX" && \
        "$PRE_ROUTE_DANGLING_FATAL" == 0 && "$PRE_ROUTE_CROSS_SHORT_COUNT" == 0 && \
        "$PNR_LEF_GATE_STATUS" == PASS && "$IO_PIN_STATUS" == OK && \
        "$TAP_SLOW_PLAN" == 1 && "$TAP_FAST_PLAN" == 1 && "$TAP_SLOW_COUNT" == 1 && \
        "$TAP_FAST_COUNT" == 1 && "$TAP_TOTAL_COUNT" == 2 && \
        "$RO_HALO_ENABLED" == 1 && "$RO_HALO_STATUS" == PASS && "$RO_HALO_COUNT" == 2 && \
        "$SLOW_HALO_STATUS" == PASS && "$FAST_HALO_STATUS" == PASS && \
        "$RO_HALO_OCCUPANCY_STATUS" == PASS && "$RO_HALO_TOTAL_INTRUSIONS" == 0 && \
        "$RO_HALO_INVALID_BBOXES" == 0 && "$RO_HALO_AUDITED_RO_COUNT" == 2 && \
        "$RO_PHASE_STATUS" == PASS && "$EXTRACTION_STATUS" == PASS && \
        "$SETUP_STATUS_TC" == PASS && "$TC_HOLD_STATUS" == PASS && \
        "$DRV_STATUS" == PASS && "$POWER_REPORT_CAPTURE_STATUS" == PASS ]] && \
        numeric_ge "$RO_HALO_CLEARANCE" 10.0 && \
        numeric_ge "$RO_HALO_GUARD_X" 11.2 && \
        numeric_ge "$RO_HALO_GUARD_Y" 4.48 && \
        numeric_ge "$RO_HALO_PLACEMENT_CLEARANCE_X" 21.2 && \
        numeric_ge "$RO_HALO_PLACEMENT_CLEARANCE_Y" 14.48 && \
        numeric_ge "$RO_PHASE_MIN_CLEARANCE" 10.0; then
    COMMON_PHYSICAL_GATE=1
  fi
  if [[ "$COMMON_PHYSICAL_GATE" == 1 && "$ROUTE_STATUS" == PASS && \
        "$SPECIAL_BAD" == 0 && "$SPECIAL_RAW_BAD" == 0 ]]; then
    PHYSICAL_GATE_MODE=STRICT_CLEAN
    DECISION=PASS_CONTINUE
  elif [[ "$COMMON_PHYSICAL_GATE" == 1 && "$ALLOW_EXACT_PG_PVS_CANDIDATE" == 1 && \
          "$ROUTE_STATUS" == PVS_CANDIDATE && "$SPECIAL_BAD" == 1 && \
          "$SPECIAL_RAW_BAD" == 1 && "$PG_CANDIDATE_STATUS" == PASS && \
          "$PG_CANDIDATE_PROFILE" == HALO10_PNRLEF_15 && \
          "$PG_CANDIDATE_EXPECTED_COUNT" == 15 && "$PG_CANDIDATE_ACTUAL_COUNT" == 15 && \
          "$PG_CANDIDATE_SUMMARY_COUNT" == 15 && "$PG_CANDIDATE_EXACT_MATCH" == 1 && \
          "$PG_CANDIDATE_OTHER_NET_LINES" == 0 && "$PG_CANDIDATE_OTHER_PROBLEM_LINES" == 0 ]] && \
          exact_pg_wire_end_report_passes "$PG_CANDIDATE_DETAIL_REPORT"; then
    PHYSICAL_GATE_MODE=PVS_CANDIDATE_EXACT_PG_WIRE_ENDS
    DECISION=PVS_CANDIDATE_CONTINUE
  fi
  if [[ -d "$RUN_DIR" ]]; then
    mkdir -p "$RUN_DIR/reports"
    if [[ -n "$ROUTE_DEF" ]]; then
      write_tap_excerpt "$ROUTE_DEF" "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
    else
      printf 'ROUTE_DEF=MISSING\nRO_TAP_OBSERVABILITY_PIN_COUNT=0\n' \
        > "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
    fi
    {
      echo "STEP=$STEP_LABEL"
      echo "PNR_RC=$TOOL_RC"
      echo "ROUTE_STATUS=$ROUTE_STATUS"
      echo "INNOVUS_VERIFY_DRC_STATUS=$DRC_STATUS"
      echo "GEOMETRY_DRC_VIOLATIONS=$GEOMETRY_DRC"
      echo "SHORTS=$SHORTS"
      echo "REGULAR_NET_CONNECTIVITY_BAD=$REGULAR_BAD"
      echo "SPECIAL_NET_CONNECTIVITY_BAD=$SPECIAL_BAD"
      echo "SPECIAL_NET_CONNECTIVITY_RAW_BAD=$SPECIAL_RAW_BAD"
      echo "SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES=$SPECIAL_NON_RO_BAD"
      echo "UNROUTED_NETS=$UNROUTED"
      echo "signal_top_layer=$SIGNAL_TOP"
      echo "router_command_top_layer=$ROUTER_TOP"
      echo "ROUTE_COMMAND_STATUS=$ROUTE_COMMAND_STATUS"
      echo "SIGNAL_TOP_ROUTE_BLOCKAGE_TEMPORARY=$SIGNAL_TOP_BLOCKAGE_TEMPORARY"
      echo "SIGNAL_TOP_ROUTE_BLOCKAGE_CREATE_STATUS=$SIGNAL_TOP_BLOCKAGE_CREATE"
      echo "SIGNAL_TOP_ROUTE_BLOCKAGE_REMOVE_STATUS=$SIGNAL_TOP_BLOCKAGE_REMOVE"
      echo "SIGNAL_TOP_ROUTE_BLOCKAGE_STATUS=$SIGNAL_TOP_BLOCKAGE_STATUS"
      echo "PRE_ROUTE_SROUTE_STATUS=$PRE_ROUTE_SROUTE_STATUS"
      echo "PRE_ROUTE_DANGLING_MODE=$PRE_ROUTE_DANGLING_MODE"
      echo "PRE_ROUTE_DANGLING_ONLY_STATUS=$PRE_ROUTE_DANGLING_STATUS"
      echo "PRE_ROUTE_DANGLING_COUNT=$PRE_ROUTE_DANGLING_COUNT"
      echo "PRE_ROUTE_DANGLING_MAX=$PRE_ROUTE_DANGLING_ACTUAL_MAX"
      echo "PRE_ROUTE_DANGLING_FATAL_COUNT=$PRE_ROUTE_DANGLING_FATAL"
      echo "PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT=$PRE_ROUTE_CROSS_SHORT_COUNT"
      echo "PNR_LEF_REQUESTED=${PNR_LEF:-NOT_REQUESTED}"
      echo "PNR_LEF_SUMMARY=${PNR_LEF_SUMMARY:-NOT_REQUESTED}"
      echo "PNR_LEF_SUMMARY_BINDING_STATUS=$PNR_LEF_SUMMARY_BINDING_STATUS"
      echo "PNR_LEF_ACTUAL=$ACTUAL_PNR_LEF"
      echo "PNR_LEF_PATH_MATCH_STATUS=$PNR_LEF_PATH_MATCH_STATUS"
      echo "PNR_LEF_EVIDENCE_STATUS=$PNR_LEF_EVIDENCE_STATUS"
      echo "PNR_LEF_REQUESTED_SHA256=$PNR_LEF_REQUESTED_SHA256"
      echo "PNR_LEF_ACTUAL_SHA256=$PNR_LEF_ACTUAL_SHA256"
      echo "PNR_LEF_EXPECTED_SHA256=$EXPECTED_HALO_PNR_LEF_SHA256"
      echo "PNR_LEF_GATE_STATUS=$PNR_LEF_GATE_STATUS"
      echo "RO_HALOS_REQUESTED=$RO_HALOS"
      echo "RO_HALO_ENABLED=$RO_HALO_ENABLED"
      echo "RO_HALO_STATUS=$RO_HALO_STATUS"
      echo "RO_HALO_COUNT=$RO_HALO_COUNT"
      echo "RO_HALO_CLEARANCE_UM=$RO_HALO_CLEARANCE"
      echo "RO_HALO_PLACER_GUARD_X_UM=$RO_HALO_GUARD_X"
      echo "RO_HALO_PLACER_GUARD_Y_UM=$RO_HALO_GUARD_Y"
      echo "RO_HALO_PLACEMENT_CLEARANCE_X_UM=$RO_HALO_PLACEMENT_CLEARANCE_X"
      echo "RO_HALO_PLACEMENT_CLEARANCE_Y_UM=$RO_HALO_PLACEMENT_CLEARANCE_Y"
      echo "SLOW_HALO_STATUS=$SLOW_HALO_STATUS"
      echo "FAST_HALO_STATUS=$FAST_HALO_STATUS"
      echo "RO_HALO_OCCUPANCY_STATUS=$RO_HALO_OCCUPANCY_STATUS"
      echo "RO_HALO_TOTAL_INTRUSION_COUNT=$RO_HALO_TOTAL_INTRUSIONS"
      echo "RO_HALO_INVALID_INSTANCE_BBOX_COUNT=$RO_HALO_INVALID_BBOXES"
      echo "RO_HALO_AUDITED_RO_COUNT=$RO_HALO_AUDITED_RO_COUNT"
      echo "RO_PHASE_PLACEMENT_STATUS=$RO_PHASE_STATUS"
      echo "RO_PHASE_MIN_CLEARANCE_UM=$RO_PHASE_MIN_CLEARANCE"
      echo "ALLOW_EXACT_PG_PVS_CANDIDATE=$ALLOW_EXACT_PG_PVS_CANDIDATE"
      echo "ROUTE_PG_PVS_CANDIDATE_STATUS=$PG_CANDIDATE_STATUS"
      echo "ROUTE_PG_PVS_CANDIDATE_PROFILE=$PG_CANDIDATE_PROFILE"
      echo "ROUTE_PG_PVS_CANDIDATE_EXPECTED_COUNT=$PG_CANDIDATE_EXPECTED_COUNT"
      echo "ROUTE_PG_PVS_CANDIDATE_ACTUAL_COUNT=$PG_CANDIDATE_ACTUAL_COUNT"
      echo "ROUTE_PG_PVS_CANDIDATE_SUMMARY_COUNT=$PG_CANDIDATE_SUMMARY_COUNT"
      echo "ROUTE_PG_PVS_CANDIDATE_EXACT_MATCH=$PG_CANDIDATE_EXACT_MATCH"
      echo "ROUTE_PG_PVS_CANDIDATE_OTHER_NET_LINE_COUNT=$PG_CANDIDATE_OTHER_NET_LINES"
      echo "ROUTE_PG_PVS_CANDIDATE_OTHER_PROBLEM_LINE_COUNT=$PG_CANDIDATE_OTHER_PROBLEM_LINES"
      echo "EXTRACTION_STATUS=$EXTRACTION_STATUS"
      echo "SETUP_STATUS_TC=$SETUP_STATUS_TC"
      echo "TC_HOLD_STATUS=$TC_HOLD_STATUS"
      echo "DRV_STATUS=$DRV_STATUS"
      echo "POWER_REPORT_CAPTURE_STATUS=$POWER_REPORT_CAPTURE_STATUS"
      echo "IO_PIN_PLACEMENT_STATUS=$IO_PIN_STATUS"
      echo "ro_slow_tap0_o_SOUTH_MET3_PLAN_COUNT=$TAP_SLOW_PLAN"
      echo "ro_fast_tap0_o_SOUTH_MET3_PLAN_COUNT=$TAP_FAST_PLAN"
      echo "ro_slow_tap0_o_COUNT=$TAP_SLOW_COUNT"
      echo "ro_fast_tap0_o_COUNT=$TAP_FAST_COUNT"
      echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$TAP_TOTAL_COUNT"
      echo "COMMON_PHYSICAL_GATE=$COMMON_PHYSICAL_GATE"
      echo "PHYSICAL_GATE_MODE=$PHYSICAL_GATE_MODE"
      echo "DECISION=$DECISION"
    } | tee "$RUN_DIR/reports/operator_gate_physical_pnr.rpt"
  fi
fi

PUBLISH_RC=99
if [[ -d "$RUN_DIR" ]]; then
  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" "$STEP_LABEL"
  PUBLISH_RC=$?
else
  echo "ERROR: no run directory exists; there is no evidence snapshot to publish"
fi

NEXT_HEAD="$(git rev-parse HEAD 2>/dev/null)"
echo "RECOVERY_STAGE=$STEP_LABEL"
echo "RECOVERY_RUN_ID=$RUN_ID"
echo "TOOL_RC=$TOOL_RC"
echo "DECISION=$DECISION"
echo "PUBLISH_RC=$PUBLISH_RC"
echo "NEXT_EXPECTED_HEAD=$NEXT_HEAD"
if [[ "$STAGE" == "physical-pnr" ]]; then
  echo "PHYSICAL_GATE_MODE=$PHYSICAL_GATE_MODE"
  echo "ROUTE_PG_PVS_CANDIDATE_STATUS=$PG_CANDIDATE_STATUS"
fi
if [[ "$STAGE" == "pg-proof" && "$DECISION" == PASS_CONTINUE && "$PUBLISH_RC" -eq 0 ]]; then
  echo "NEXT_STAGE=PHYSICAL_PNR"
  echo "NEXT_REQUIRED_PG_RUN_ID=$RUN_ID"
elif [[ "$STAGE" == "physical-pnr" && \
        ( "$DECISION" == PASS_CONTINUE || "$DECISION" == PVS_CANDIDATE_CONTINUE ) && \
        "$PUBLISH_RC" -eq 0 ]]; then
  echo "NEXT_STAGE=PVS"
  echo "NEXT_REQUIRED_PNR_RUN_ID=$RUN_ID"
else
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
fi

if [[ ( "$DECISION" == PASS_CONTINUE || "$DECISION" == PVS_CANDIDATE_CONTINUE ) && \
      "$PUBLISH_RC" -eq 0 ]]; then
  exit 0
fi
exit 1
