#!/usr/bin/env bash
# Run and evidence-gate one MPTDC RO6 physical recovery stage.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
REPO_ROOT="${MPTDC_RECOVERY_REPO_ROOT:-$DEFAULT_REPO_ROOT}"
LAUNCHER="${MPTDC_RECOVERY_LAUNCHER:-$SCRIPT_DIR/server_run_mptdc_ro6_latestlef_simplepg.sh}"
SWEEP_LAUNCHER="${MPTDC_RECOVERY_SWEEP_LAUNCHER:-$SCRIPT_DIR/server_sweep_mptdc_pg_sroute_candidates.sh}"
PUBLISHER="${MPTDC_RECOVERY_PUBLISHER:-$REPO_ROOT/MPTDC/ci/publish_mptdc_server_snapshot.sh}"
INNOVUS_WORK="${MPTDC_INNOVUS_WORK:-/sim/ksabra/SPADMIC_work/innovus}"
WORK_ROOT="${MPTDC_WORK_ROOT:-/sim/ksabra/SPADMIC_work}"
DEFAULT_GENUS_RUN="MPTDC_TC_BufferedROTap0Pins_Genus_20260709_155623"

STAGE=""
RUN_ID=""
PG_RUN_ID=""
SOURCE_PG_RUN_ID="${MPTDC_SOURCE_PG_RUN_ID:-}"
EXPECTED_HEAD_VALUE="${EXPECTED_HEAD:-}"
GENUS_RUN_ID="${MPTDC_GENUS_RUN_ID:-$DEFAULT_GENUS_RUN}"
HANDOFF_DIR="${MPTDC_GENUS_HANDOFF_DIR:-}"
SOURCE_LEF=""

usage() {
  cat <<'USAGE'
Usage:
  server_run_mptdc_ro6_recovery_stage.sh --stage <pg-proof|pg-sweep|physical-pnr> [options]

Options:
  --run-id <id>          Explicit result directory name. A unique id is generated by default.
  --pg-run-id <id>       Required for physical-pnr; identifies the published clean PG proof.
  --source-pg-run-id <id>
                         Required for pg-sweep; identifies the published failed PG proof.
  --expected-head <sha>  Require the checked-out repository HEAD.
  --genus-run-id <id>    Buffered-tap Genus run id.
  --handoff-dir <path>   PnR-compatible Genus handoff directory.
  --innovus-work <path>  Innovus result root.
  --work-root <path>     SPADMIC server work root.
  --source-lef <path>    Override the RO_tune6 LEF passed to the launcher.
  -h, --help             Show this help.

The stage runs in the foreground, writes an operator_gate report, and publishes
one bounded text-evidence snapshot. A failed physical gate is still published,
but the script returns nonzero and never launches the next stage.
USAGE
}

copy_sweep_candidate_evidence() {
  local summary_csv="$1"
  local candidate candidate_run_id rc strict_pg_clean strict_reasons
  local drc shorts regular_bad special_bad special_raw filter_status
  local filtered_ro non_ro unrouted route_gate checkpoint status_report
  local source_dir dest_dir file log

  while IFS=, read -r candidate candidate_run_id rc strict_pg_clean strict_reasons \
      drc shorts regular_bad special_bad special_raw filter_status filtered_ro \
      non_ro unrouted route_gate checkpoint status_report; do
    [[ "$candidate" == "candidate" || -z "$candidate" ]] && continue
    source_dir="$INNOVUS_WORK/$candidate_run_id"
    dest_dir="$RUN_DIR/reports/candidates/$candidate"
    mkdir -p "$dest_dir"

    for file in \
      "$source_dir/reports/checkpoint_repair_status.rpt" \
      "$source_dir"/reports/pg_candidate_*.rpt \
      "$source_dir"/reports/00_initial_verify_*.rpt \
      "$source_dir"/reports/00_initial_verify_drc_markers.tsv \
      "$source_dir"/reports/01_after_command_verify_*.rpt \
      "$source_dir"/reports/01_after_command_verify_drc_markers.tsv \
      "$source_dir"/reports/01_command_*.rpt; do
      [[ -f "$file" ]] && cp "$file" "$dest_dir/"
    done

    for log in \
      "$source_dir/logs/checkpoint_repair_wrapper.log" \
      "$source_dir/logs/innovus_route_checkpoint_repair.log"; do
      if [[ -f "$log" ]]; then
        grep -E '(^\*\*(WARN|ERROR|INFO)|\b(ERROR|WARN|FATAL|PASS|FAIL|STATUS|VIOL|short|SHORT)\b)' \
          "$log" | tail -n 320 \
          > "$RUN_DIR/logs/${candidate}_$(basename "$log").messages.tail" || true
      fi
    done
  done < "$summary_csv"
}

run_pg_sweep_stage() {
  local source_checkpoint="$1"
  local summary_csv="$INNOVUS_WORK/${RUN_ID}_summary.csv"
  local summary_md="$INNOVUS_WORK/${RUN_ID}_summary.md"
  local sweep_log candidate_count pass_count pass_candidates
  local sweep_rc decision sweep_status publish_rc next_head

  mkdir -p "$RUN_DIR/reports" "$RUN_DIR/logs" "$RUN_DIR/manifests"
  sweep_log="$RUN_DIR/logs/pg_sroute_sweep_driver.log"

  set +e
  bash "$SWEEP_LAUNCHER" \
    --checkpoint "$source_checkpoint" \
    --base-run-id "$RUN_ID" \
    --expected-head "$EXPECTED_HEAD_VALUE" \
    --innovus-work "$INNOVUS_WORK" \
    2>&1 | tee "$sweep_log"
  sweep_rc=${PIPESTATUS[0]}
  set +e

  if [[ -s "$summary_csv" ]]; then
    cp "$summary_csv" "$RUN_DIR/reports/pg_sroute_candidate_summary.csv"
    copy_sweep_candidate_evidence "$summary_csv"
    candidate_count="$(awk -F, 'NR > 1 && $1 != "" {count++} END {print count + 0}' "$summary_csv")"
    pass_count="$(awk -F, 'NR > 1 && $4 == "PASS" {count++} END {print count + 0}' "$summary_csv")"
    pass_candidates="$(awk -F, 'NR > 1 && $4 == "PASS" {print $1}' "$summary_csv" | paste -sd, -)"
  else
    candidate_count=0
    pass_count=0
    pass_candidates=""
  fi
  [[ -s "$summary_md" ]] && cp "$summary_md" "$RUN_DIR/reports/pg_sroute_candidate_summary.md"
  [[ -n "$pass_candidates" ]] || pass_candidates=NONE

  decision=FAIL_STOP
  sweep_status=FAIL_INCOMPLETE_OR_NO_STRICT_CANDIDATE
  if [[ "$sweep_rc" -eq 0 && "$candidate_count" -eq 10 && "$pass_count" -gt 0 ]]; then
    decision=PASS_CONTINUE
    sweep_status=PASS_STRICT_CANDIDATE_FOUND
  fi

  {
    echo "STEP=PG_SROUTE_SWEEP"
    echo "SOURCE_PG_RUN_ID=$SOURCE_PG_RUN_ID"
    echo "SOURCE_CHECKPOINT=$source_checkpoint"
    echo "SWEEP_RC=$sweep_rc"
    echo "EXPECTED_CANDIDATE_COUNT=10"
    echo "CANDIDATE_COUNT=$candidate_count"
    echo "STRICT_PASS_COUNT=$pass_count"
    echo "STRICT_PASS_CANDIDATES=$pass_candidates"
    echo "PG_SROUTE_SWEEP_STATUS=$sweep_status"
    echo "DECISION=$decision"
  } | tee "$RUN_DIR/reports/operator_gate_pg_sroute_sweep.rpt"
  {
    echo "source_pg_run_id: $SOURCE_PG_RUN_ID"
    echo "source_checkpoint: $source_checkpoint"
    echo "head: $EXPECTED_HEAD_VALUE"
    echo "candidate_process_isolation: one fresh Innovus restore per candidate"
  } > "$RUN_DIR/manifests/pg_sroute_sweep_manifest.txt"

  publish_rc=99
  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" PG_SROUTE_SWEEP
  publish_rc=$?
  next_head="$(git rev-parse HEAD 2>/dev/null)"

  echo "RECOVERY_STAGE=PG_SROUTE_SWEEP"
  echo "RECOVERY_RUN_ID=$RUN_ID"
  echo "TOOL_RC=$sweep_rc"
  echo "CANDIDATE_COUNT=$candidate_count"
  echo "STRICT_PASS_COUNT=$pass_count"
  echo "STRICT_PASS_CANDIDATES=$pass_candidates"
  echo "DECISION=$decision"
  echo "PUBLISH_RC=$publish_rc"
  echo "NEXT_EXPECTED_HEAD=$next_head"
  if [[ "$decision" == PASS_CONTINUE && "$publish_rc" -eq 0 ]]; then
    echo "NEXT_STAGE=REVIEW_AND_REPLAY_PG_CANDIDATE"
    return 0
  fi
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
  return 1
}

report_value() {
  local report="$1"
  local key="$2"
  local value
  value="$(sed -n "s/^${key}=//p" "$report" 2>/dev/null | tail -1)"
  if [[ -n "$value" ]]; then
    printf '%s\n' "$value"
  else
    printf 'MISSING\n'
  fi
}

load_cadence_env() {
  local env_file="$1"
  local source_rc=0

  echo "CADENCE_ENV=$env_file"
  if [[ ! -r "$env_file" ]]; then
    echo "CADENCE_ENV_RC=0"
    echo "CADENCE_ENV_STATUS=SKIPPED_NOT_READABLE"
    return 0
  fi

  # Site setup files are written for interactive shells and may read unset
  # variables. Keep the recovery driver's nounset policy outside this boundary.
  set +u
  set +e
  # shellcheck disable=SC1090
  source "$env_file" >/dev/null 2>&1
  source_rc=$?
  set +e
  set -u
  set -o pipefail

  echo "CADENCE_ENV_RC=$source_rc"
  if [[ "$source_rc" -eq 0 ]]; then
    echo "CADENCE_ENV_STATUS=PASS"
    return 0
  fi

  echo "CADENCE_ENV_STATUS=FAIL"
  return "$source_rc"
}

tracked_report_passes() {
  local report="$1"
  shift
  local rel key expected actual

  rel="${report#"$REPO_ROOT"/}"
  git -C "$REPO_ROOT" ls-files --error-unmatch "$rel" >/dev/null 2>&1 || return 1
  [[ -s "$report" ]] || return 1
  while [[ $# -gt 0 ]]; do
    key="$1"
    expected="$2"
    shift 2
    actual="$(report_value "$report" "$key")"
    [[ "$actual" == "$expected" ]] || return 1
  done
}

tap_plan_count() {
  local csv="$1"
  local wanted="$2"
  if [[ ! -s "$csv" ]]; then
    printf 'MISSING\n'
    return 0
  fi
  awk -F, -v wanted="$wanted" '
    NR > 1 {
      name=$1
      gsub(/^"|"$/, "", name)
      if (name == wanted && $3 == "SOUTH" && $4 == "MET3" && $5 == "REQUESTED") count++
    }
    END {print count + 0}
  ' "$csv" 2>/dev/null
}

tap_def_count() {
  local def="$1"
  local wanted="$2"
  awk -v wanted="$wanted" '
    /^PINS[[:space:]]/ {in_pins=1; next}
    /^END PINS/ {in_pins=0}
    in_pins && /^-[[:space:]]/ && $2 == wanted {count++}
    END {print count + 0}
  ' "$def" 2>/dev/null
}

tap_def_total() {
  local def="$1"
  awk '
    /^PINS[[:space:]]/ {in_pins=1; next}
    /^END PINS/ {in_pins=0}
    in_pins && /^-[[:space:]]/ && $2 ~ /^ro_(slow|fast)_tap[0-9]+_o$/ {count++}
    END {print count + 0}
  ' "$def" 2>/dev/null
}

write_tap_excerpt() {
  local def="$1"
  local out="$2"
  {
    echo "ROUTE_DEF=$def"
    echo "ro_slow_tap0_o_COUNT=$(tap_def_count "$def" ro_slow_tap0_o)"
    echo "ro_fast_tap0_o_COUNT=$(tap_def_count "$def" ro_fast_tap0_o)"
    echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$(tap_def_total "$def")"
    awk '
      /^PINS[[:space:]]/ {in_pins=1; next}
      /^END PINS/ {in_pins=0}
      in_pins && /^-[[:space:]]/ {
        if (active) print record
        active=($2 == "ro_slow_tap0_o" || $2 == "ro_fast_tap0_o")
        record=$0
        next
      }
      in_pins && active {record=record " " $0}
      END {if (active) print record}
    ' "$def"
  } > "$out"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage) STAGE="${2:?missing --stage value}"; shift 2 ;;
    --run-id) RUN_ID="${2:?missing --run-id value}"; shift 2 ;;
    --pg-run-id) PG_RUN_ID="${2:?missing --pg-run-id value}"; shift 2 ;;
    --source-pg-run-id) SOURCE_PG_RUN_ID="${2:?missing --source-pg-run-id value}"; shift 2 ;;
    --expected-head) EXPECTED_HEAD_VALUE="${2:?missing --expected-head value}"; shift 2 ;;
    --genus-run-id) GENUS_RUN_ID="${2:?missing --genus-run-id value}"; shift 2 ;;
    --handoff-dir) HANDOFF_DIR="${2:?missing --handoff-dir value}"; shift 2 ;;
    --innovus-work) INNOVUS_WORK="${2:?missing --innovus-work value}"; shift 2 ;;
    --work-root) WORK_ROOT="${2:?missing --work-root value}"; shift 2 ;;
    --source-lef) SOURCE_LEF="${2:?missing --source-lef value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

case "$STAGE" in
  pg-proof|pg-sweep|physical-pnr) ;;
  *) echo "ERROR: --stage must be pg-proof, pg-sweep, or physical-pnr" >&2; usage >&2; exit 2 ;;
esac

if [[ -z "$HANDOFF_DIR" ]]; then
  HANDOFF_DIR="$WORK_ROOT/handoff/genus_typical_pnrcompat/$GENUS_RUN_ID"
fi

if [[ -z "$RUN_ID" ]]; then
  if [[ "$STAGE" == "pg-proof" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_simplepg_pgproof_$(date +%H%M%S)"
  elif [[ "$STAGE" == "pg-sweep" ]]; then
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_pgsweep_$(date +%H%M%S)"
  else
    RUN_ID="$(date +%Y%m%d)_mptdc_bufftap0_mettpfix_physical_$(date +%H%M%S)"
  fi
fi
RUN_DIR="$INNOVUS_WORK/$RUN_ID"

cd "$REPO_ROOT" || exit 3
ACTUAL_HEAD="$(git rev-parse HEAD 2>/dev/null)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
ORIGIN_HEAD="$(git rev-parse refs/remotes/origin/SPADMIC_test 2>/dev/null || true)"
EXPECTED_HEAD_VALUE="${EXPECTED_HEAD_VALUE:-${ORIGIN_HEAD:-$ACTUAL_HEAD}}"
TRACKED_STATUS="$(git status --short --untracked-files=no 2>/dev/null)"

echo "RECOVERY_STAGE=$STAGE"
echo "RUN_ID=$RUN_ID"
echo "RUN_DIR=$RUN_DIR"
echo "GENUS_RUN_ID=$GENUS_RUN_ID"
echo "HANDOFF_DIR=$HANDOFF_DIR"
echo "SOURCE_PG_RUN_ID=${SOURCE_PG_RUN_ID:-NONE}"
echo "BRANCH=$BRANCH"
echo "ACTUAL_HEAD=$ACTUAL_HEAD"
echo "ORIGIN_HEAD=${ORIGIN_HEAD:-MISSING}"
echo "EXPECTED_HEAD=$EXPECTED_HEAD_VALUE"

PREFLIGHT=PASS
[[ "$BRANCH" == "SPADMIC_test" ]] || { echo "STOP: branch must be SPADMIC_test"; PREFLIGHT=FAIL; }
[[ "$ACTUAL_HEAD" == "$EXPECTED_HEAD_VALUE" ]] || { echo "STOP: HEAD mismatch"; PREFLIGHT=FAIL; }
[[ -z "$TRACKED_STATUS" ]] || { echo "$TRACKED_STATUS"; echo "STOP: tracked working tree is dirty"; PREFLIGHT=FAIL; }
[[ -f "$PUBLISHER" ]] || { echo "STOP: publisher missing: $PUBLISHER"; PREFLIGHT=FAIL; }
[[ ! -e "$RUN_DIR" ]] || { echo "STOP: run directory already exists: $RUN_DIR"; PREFLIGHT=FAIL; }
[[ "$RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "STOP: unsafe run id: $RUN_ID"; PREFLIGHT=FAIL; }
if [[ "$STAGE" == "pg-sweep" ]]; then
  [[ -f "$SWEEP_LAUNCHER" ]] || { echo "STOP: sweep launcher missing: $SWEEP_LAUNCHER"; PREFLIGHT=FAIL; }
else
  [[ -f "$LAUNCHER" ]] || { echo "STOP: launcher missing: $LAUNCHER"; PREFLIGHT=FAIL; }
  [[ -d "$HANDOFF_DIR" ]] || { echo "STOP: handoff missing: $HANDOFF_DIR"; PREFLIGHT=FAIL; }
fi

PRE_PNR_REPORT=""
if [[ "$STAGE" == "pg-proof" ]]; then
  PRE_PNR_REPORT="$(find "$REPO_ROOT/MPTDC/docs/server_snapshots/genus" \
    -path "*/${GENUS_RUN_ID}_prepnr_*/reports/operator_gate_pre_pnr.rpt" \
    -type f 2>/dev/null | sort | tail -1)"
  if [[ -z "$PRE_PNR_REPORT" ]] || ! tracked_report_passes "$PRE_PNR_REPORT" \
      PACKAGE_RC 0 PRE_PNR_RC 0 PRE_PNR_GATE PASS DECISION PASS_CONTINUE; then
    echo "STOP: no tracked passing pre-PnR snapshot for $GENUS_RUN_ID"
    PREFLIGHT=FAIL
  fi
elif [[ "$STAGE" == "pg-sweep" ]]; then
  [[ -n "$SOURCE_PG_RUN_ID" ]] || { echo "STOP: --source-pg-run-id is required for pg-sweep"; PREFLIGHT=FAIL; }
  [[ "$SOURCE_PG_RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "STOP: unsafe source PG run id"; PREFLIGHT=FAIL; }
  SOURCE_PG_GATE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$SOURCE_PG_RUN_ID/reports/operator_gate_pg_proof.rpt"
  SOURCE_PG_CHECKPOINT="$INNOVUS_WORK/$SOURCE_PG_RUN_ID/checkpoints/03_cts.enc.dat"
  if [[ -z "$SOURCE_PG_RUN_ID" ]] || ! tracked_report_passes "$SOURCE_PG_GATE" \
      STEP STRICT_PG_PROOF PG_RC 1 \
      POSTPLACE_PRE_ROUTE_SROUTE_STATUS FAIL \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD 1 \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD 1 \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES 0 \
      DECISION FAIL_STOP; then
    echo "STOP: tracked failed PG proof snapshot is missing or does not match: $SOURCE_PG_RUN_ID"
    PREFLIGHT=FAIL
  fi
  [[ -d "$SOURCE_PG_CHECKPOINT" ]] || { echo "STOP: clean pre-sroute checkpoint missing: $SOURCE_PG_CHECKPOINT"; PREFLIGHT=FAIL; }
else
  [[ -n "$PG_RUN_ID" ]] || { echo "STOP: --pg-run-id is required for physical-pnr"; PREFLIGHT=FAIL; }
  PG_GATE_REPORT="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$PG_RUN_ID/reports/operator_gate_pg_proof.rpt"
  if [[ -z "$PG_RUN_ID" ]] || ! tracked_report_passes "$PG_GATE_REPORT" \
      PG_RC 0 POSTPLACE_PRE_ROUTE_SROUTE_STATUS PASS \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD 0 \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD 0 \
      POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES 0 \
      DECISION PASS_CONTINUE; then
    echo "STOP: tracked clean PG proof snapshot is missing or failed: $PG_RUN_ID"
    PREFLIGHT=FAIL
  fi
fi

echo "RECOVERY_PREFLIGHT=$PREFLIGHT"
if [[ "$PREFLIGHT" != "PASS" ]]; then
  echo "DECISION=FAIL_STOP"
  exit 4
fi

CADENCE_ENV="${MPTDC_CADENCE_ENV:-/eda/cadence/eda_2023-2024}"
if ! load_cadence_env "$CADENCE_ENV"; then
  echo "STOP: failed to source Cadence environment: $CADENCE_ENV"
  echo "DECISION=FAIL_STOP"
  exit 5
fi

if [[ "$STAGE" == "pg-sweep" ]]; then
  run_pg_sweep_stage "$SOURCE_PG_CHECKPOINT"
  exit $?
fi

LAUNCH_ARGS=(
  --run-id "$RUN_ID"
  --expected-head "$EXPECTED_HEAD_VALUE"
  --handoff-dir "$HANDOFF_DIR"
  --genus-run-id "$GENUS_RUN_ID"
  --innovus-work "$INNOVUS_WORK"
  --work-root "$WORK_ROOT"
  --no-free-all
  --local-phase-preplace
  --strict-special-clean
  --no-signal-top-route-blockage
)
if [[ -n "$SOURCE_LEF" ]]; then
  LAUNCH_ARGS+=(--source-lef "$SOURCE_LEF")
fi
if [[ "$STAGE" == "pg-proof" ]]; then
  LAUNCH_ARGS+=(--stage pg_proof)
else
  LAUNCH_ARGS+=(--stage full_closure --physical-first --post-filler-sroute)
fi

set +e
bash "$LAUNCHER" "${LAUNCH_ARGS[@]}"
TOOL_RC=$?
set +e

DECISION=FAIL_STOP
STEP_LABEL=UNKNOWN
if [[ "$STAGE" == "pg-proof" ]]; then
  STEP_LABEL=STRICT_PG_PROOF
  STATUS_REPORT="$RUN_DIR/reports/postplace_pre_route_sroute_status.rpt"
  PG_SROUTE_STATUS="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SROUTE_STATUS)"
  PG_BAD="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD)"
  PG_RAW_BAD="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD)"
  PG_NON_RO_BAD="$(report_value "$STATUS_REPORT" POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES)"
  if [[ "$TOOL_RC" -eq 0 && "$PG_SROUTE_STATUS" == PASS && "$PG_BAD" == 0 && \
        "$PG_RAW_BAD" == 0 && "$PG_NON_RO_BAD" == 0 ]]; then
    DECISION=PASS_CONTINUE
  fi
  if [[ -d "$RUN_DIR" ]]; then
    mkdir -p "$RUN_DIR/reports"
    {
      echo "STEP=$STEP_LABEL"
      echo "PG_RC=$TOOL_RC"
      echo "POSTPLACE_PRE_ROUTE_SROUTE_STATUS=$PG_SROUTE_STATUS"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_BAD=$PG_BAD"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_RAW_BAD=$PG_RAW_BAD"
      echo "POSTPLACE_PRE_ROUTE_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=$PG_NON_RO_BAD"
      echo "DECISION=$DECISION"
    } | tee "$RUN_DIR/reports/operator_gate_pg_proof.rpt"
  fi
else
  STEP_LABEL=PHYSICAL_PNR
  ROUTE_REPORT="$RUN_DIR/reports/route_status.rpt"
  ROUTE_INTENT_REPORT="$RUN_DIR/reports/route_layer_intent.rpt"
  IO_PIN_SUMMARY="$RUN_DIR/reports/io_pin_placement_summary.md"
  IO_PIN_CSV="$RUN_DIR/reports/io_pin_placement.csv"
  ROUTE_STATUS="$(report_value "$ROUTE_REPORT" ROUTE_STATUS)"
  DRC_STATUS="$(report_value "$ROUTE_REPORT" INNOVUS_VERIFY_DRC_STATUS)"
  GEOMETRY_DRC="$(report_value "$ROUTE_REPORT" GEOMETRY_DRC_VIOLATIONS)"
  SHORTS="$(report_value "$ROUTE_REPORT" SHORTS)"
  REGULAR_BAD="$(report_value "$ROUTE_REPORT" REGULAR_NET_CONNECTIVITY_BAD)"
  SPECIAL_BAD="$(report_value "$ROUTE_REPORT" SPECIAL_NET_CONNECTIVITY_BAD)"
  SPECIAL_RAW_BAD="$(report_value "$ROUTE_REPORT" SPECIAL_NET_CONNECTIVITY_RAW_BAD)"
  SPECIAL_NON_RO_BAD="$(report_value "$ROUTE_REPORT" SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES)"
  UNROUTED="$(report_value "$ROUTE_REPORT" UNROUTED_NETS)"
  ROUTER_TOP="$(report_value "$ROUTE_INTENT_REPORT" router_command_top_layer)"
  IO_PIN_STATUS="$(report_value "$IO_PIN_SUMMARY" REPORT_STATUS)"
  TAP_SLOW_PLAN="$(tap_plan_count "$IO_PIN_CSV" ro_slow_tap0_o)"
  TAP_FAST_PLAN="$(tap_plan_count "$IO_PIN_CSV" ro_fast_tap0_o)"
  ROUTE_DEF=""
  for candidate in "$RUN_DIR/def/04_route.def" "$RUN_DIR/def/04_route_failed.def"; do
    if [[ -s "$candidate" ]]; then ROUTE_DEF="$candidate"; break; fi
  done
  TAP_SLOW_COUNT=0
  TAP_FAST_COUNT=0
  TAP_TOTAL_COUNT=0
  if [[ -n "$ROUTE_DEF" ]]; then
    TAP_SLOW_COUNT="$(tap_def_count "$ROUTE_DEF" ro_slow_tap0_o)"
    TAP_FAST_COUNT="$(tap_def_count "$ROUTE_DEF" ro_fast_tap0_o)"
    TAP_TOTAL_COUNT="$(tap_def_total "$ROUTE_DEF")"
  fi
  if [[ "$TOOL_RC" -eq 0 && "$ROUTE_STATUS" == PASS && "$DRC_STATUS" == PASS && \
        "$GEOMETRY_DRC" == 0 && "$SHORTS" == 0 && "$REGULAR_BAD" == 0 && \
        "$SPECIAL_BAD" == 0 && "$SPECIAL_RAW_BAD" == 0 && "$SPECIAL_NON_RO_BAD" == 0 && \
        "$UNROUTED" == 0 && "$ROUTER_TOP" == MET3 && "$IO_PIN_STATUS" == OK && \
        "$TAP_SLOW_PLAN" == 1 && "$TAP_FAST_PLAN" == 1 && "$TAP_SLOW_COUNT" == 1 && \
        "$TAP_FAST_COUNT" == 1 && "$TAP_TOTAL_COUNT" == 2 ]]; then
    DECISION=PASS_CONTINUE
  fi
  if [[ -d "$RUN_DIR" ]]; then
    mkdir -p "$RUN_DIR/reports"
    if [[ -n "$ROUTE_DEF" ]]; then
      write_tap_excerpt "$ROUTE_DEF" "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
    else
      printf 'ROUTE_DEF=MISSING\nRO_TAP_OBSERVABILITY_PIN_COUNT=0\n' \
        > "$RUN_DIR/reports/tap_pin_def_excerpt.rpt"
    fi
    {
      echo "STEP=$STEP_LABEL"
      echo "PNR_RC=$TOOL_RC"
      echo "ROUTE_STATUS=$ROUTE_STATUS"
      echo "INNOVUS_VERIFY_DRC_STATUS=$DRC_STATUS"
      echo "GEOMETRY_DRC_VIOLATIONS=$GEOMETRY_DRC"
      echo "SHORTS=$SHORTS"
      echo "REGULAR_NET_CONNECTIVITY_BAD=$REGULAR_BAD"
      echo "SPECIAL_NET_CONNECTIVITY_BAD=$SPECIAL_BAD"
      echo "SPECIAL_NET_CONNECTIVITY_RAW_BAD=$SPECIAL_RAW_BAD"
      echo "SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES=$SPECIAL_NON_RO_BAD"
      echo "UNROUTED_NETS=$UNROUTED"
      echo "router_command_top_layer=$ROUTER_TOP"
      echo "IO_PIN_PLACEMENT_STATUS=$IO_PIN_STATUS"
      echo "ro_slow_tap0_o_SOUTH_MET3_PLAN_COUNT=$TAP_SLOW_PLAN"
      echo "ro_fast_tap0_o_SOUTH_MET3_PLAN_COUNT=$TAP_FAST_PLAN"
      echo "ro_slow_tap0_o_COUNT=$TAP_SLOW_COUNT"
      echo "ro_fast_tap0_o_COUNT=$TAP_FAST_COUNT"
      echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$TAP_TOTAL_COUNT"
      echo "DECISION=$DECISION"
    } | tee "$RUN_DIR/reports/operator_gate_physical_pnr.rpt"
  fi
fi

PUBLISH_RC=99
if [[ -d "$RUN_DIR" ]]; then
  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" innovus "$RUN_ID" "$RUN_DIR" "$STEP_LABEL"
  PUBLISH_RC=$?
else
  echo "ERROR: no run directory exists; there is no evidence snapshot to publish"
fi

NEXT_HEAD="$(git rev-parse HEAD 2>/dev/null)"
echo "RECOVERY_STAGE=$STEP_LABEL"
echo "RECOVERY_RUN_ID=$RUN_ID"
echo "TOOL_RC=$TOOL_RC"
echo "DECISION=$DECISION"
echo "PUBLISH_RC=$PUBLISH_RC"
echo "NEXT_EXPECTED_HEAD=$NEXT_HEAD"
if [[ "$STAGE" == "pg-proof" && "$DECISION" == PASS_CONTINUE && "$PUBLISH_RC" -eq 0 ]]; then
  echo "NEXT_STAGE=PHYSICAL_PNR"
  echo "NEXT_REQUIRED_PG_RUN_ID=$RUN_ID"
elif [[ "$STAGE" == "physical-pnr" && "$DECISION" == PASS_CONTINUE && "$PUBLISH_RC" -eq 0 ]]; then
  echo "NEXT_STAGE=PVS"
  echo "NEXT_REQUIRED_PNR_RUN_ID=$RUN_ID"
else
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
fi

if [[ "$DECISION" == PASS_CONTINUE && "$PUBLISH_RC" -eq 0 ]]; then
  exit 0
fi
exit 1
