#!/usr/bin/env python3
"""Generate the connected TX egress fixed-leaf assembly package.

This package is the next gate after the fixed-leaf Innovus smoke.  It keeps the
small TX glue logic from spadmic_tx_egress_core, but treats the four hardened TX
leaves as black boxes so a later Genus/Innovus assembly step can preserve the
validated leaf abstracts.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import re
import subprocess
import sys
from pathlib import Path


TOP_MODULE = "spadmic_tx_egress_leaf_assembly"
SOURCE_TOP_MODULE = "spadmic_tx_egress_core"

LEAF_MODULES = {
    "event_bundle_tx": ("spadmic_event_bundle_tx", "TOP/rtl/spadmic_event_bundle_tx.sv"),
    "output_fifo": ("spadmic_output_fifo_topcfg", "TOP/rtl/spadmic_output_fifo_topcfg.sv"),
    "ddr16_pairer": ("spadmic_ddr16_tx_pairer", "TOP/rtl/spadmic_ddr16_tx_pairer.sv"),
    "ddrs2_adapter": ("spadmic_ddrs2_adapter", "TOP/rtl/spadmic_ddrs2_adapter.sv"),
}

LEAF_ORDER = ["event_bundle_tx", "output_fifo", "ddr16_pairer", "ddrs2_adapter"]


def repo_head(repo_root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "unknown"


def read_status(path: Path) -> dict[str, str]:
    status: dict[str, str] = {}
    if not path.is_file():
        return status
    for line in path.read_text(errors="replace").splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        status[key.strip()] = value.strip()
    return status


def require_file(path: Path, errors: list[str], label: str) -> None:
    if not path.is_file():
        errors.append(f"missing {label}: {path}")


def extract_module_header(source: Path, module_name: str) -> str:
    text = source.read_text(errors="replace")
    match = re.search(
        rf"\bmodule\s+{re.escape(module_name)}\b.*?\n\);",
        text,
        flags=re.DOTALL,
    )
    if not match:
        raise SystemExit(f"could not extract module header for {module_name} from {source}")
    return match.group(0)


def write_blackboxes(path: Path, repo_root: Path) -> None:
    with path.open("w") as fh:
        fh.write("// Auto-generated TX fixed-leaf black boxes.\n")
        fh.write("// Use with tx_egress_leaf_connected_assembly.sv for glue synthesis only.\n\n")
        for block in LEAF_ORDER:
            module_name, rel_source = LEAF_MODULES[block]
            header = extract_module_header(repo_root / rel_source, module_name)
            fh.write("(* black_box, syn_black_box, keep_hierarchy = \"yes\" *)\n")
            fh.write(header)
            fh.write("\nendmodule\n\n")


def write_assembly_rtl(path: Path, repo_root: Path) -> None:
    source = repo_root / "TOP/rtl/spadmic_tx_egress_core.sv"
    text = source.read_text(errors="replace")
    text = re.sub(
        rf"\bmodule\s+{SOURCE_TOP_MODULE}\b",
        f"module {TOP_MODULE}",
        text,
        count=1,
    )
    text = text.replace(
        "File     : spadmic_tx_egress_core.sv",
        "File     : tx_egress_leaf_connected_assembly.sv",
    )
    text = text.replace(
        "Physical TX egress island interface for DDRs2-facing hardening.",
        "Connected fixed-leaf TX egress assembly wrapper for glue synthesis.",
    )
    banner = (
        "// AUTO-GENERATED by gen_tx_egress_connected_assembly.py.\n"
        "// This preserves spadmic_tx_egress_core glue logic and instances the\n"
        "// four hardened TX leaves as black boxes via the companion file.\n"
        "// Do not treat this file as final signoff collateral by itself.\n\n"
    )
    path.write_text(banner + text)


def write_filelist(path: Path, repo_root: Path, blackboxes: Path, assembly_rtl: Path) -> None:
    with path.open("w") as fh:
        fh.write("// Auto-generated filelist for TX egress fixed-leaf connected assembly.\n")
        fh.write(f"{repo_root / 'MPTDC/rtl/pkg/mptdc_pkg.sv'}\n")
        fh.write(f"{repo_root / 'TOP/rtl/spadmic_pkg.sv'}\n")
        fh.write(f"{blackboxes}\n")
        fh.write(f"{assembly_rtl}\n")


def write_connection_manifest(path: Path) -> None:
    rows = [
        ("clock", "clk_sys", "top.clk_sys", "u_event_bundle_tx.clk_sys u_output_fifo.clk_sys u_ddr16_pairer.clk_sys", "shared system clock"),
        ("clock", "clk_160m_i", "top.clk_160m_i", "u_ddrs2_adapter.clk_160m_i", "DDRs2 forwarded-clock source"),
        ("reset", "rst_n", "top.rst_n", "all_leaf_rst_n", "shared active-low reset"),
        ("bundle_to_fifo", "bundle_word_valid", "u_event_bundle_tx.word_valid_o", "glue.output_fifo_push_valid", "muxed with flush token"),
        ("bundle_to_fifo", "bundle_word_ready", "glue.bundle_word_ready", "u_event_bundle_tx.word_ready_i", "held low while flush token is pending"),
        ("bundle_to_fifo", "bundle_word_data[15:0]", "u_event_bundle_tx.word_data_o", "u_output_fifo.push_data_i[15:0]", "payload path through flush-tag FIFO word"),
        ("bundle_to_fifo", "bundle_flush", "u_event_bundle_tx.flush_o", "glue.bundle_flush_pending_q", "one-bit glue flop creates ordered FIFO flush marker"),
        ("fifo_to_pairer", "ddr_word_valid", "u_output_fifo.pop_valid_o/glue.output_fifo_pop_is_flush", "u_ddr16_pairer.word_valid_i", "valid only for non-flush FIFO words"),
        ("fifo_to_pairer", "ddr_word_ready", "u_ddr16_pairer.word_ready_o", "glue.output_fifo_pop_ready", "flush words bypass pairer readiness"),
        ("fifo_to_pairer", "ddr_word_data[15:0]", "u_output_fifo.pop_data_o[15:0]", "u_ddr16_pairer.word_data_i", "payload to DDR16 pairer"),
        ("fifo_to_pairer", "ddr_flush", "u_output_fifo.pop_data_o[16]/pop_fire", "u_ddr16_pairer.flush_i", "flushes half-full pairer word"),
        ("pairer_to_adapter", "ddr_data_l[15:0]", "u_ddr16_pairer.ddr_data_l_o", "u_ddrs2_adapter.ddr_data_l_i", "low DDR phase"),
        ("pairer_to_adapter", "ddr_data_h[15:0]", "u_ddr16_pairer.ddr_data_h_o", "u_ddrs2_adapter.ddr_data_h_i", "high DDR phase"),
        ("pairer_to_adapter", "ddr_pair_valid_o", "u_ddr16_pairer.ddr_pair_valid_o", "u_ddrs2_adapter.ddr_pair_valid_i", "pair-valid lane driver"),
        ("adapter_to_ddrs2", "ddrs2_data_l_o[18:0]", "u_ddrs2_adapter.ddrs2_data_l_o", "top.ddrs2_data_l_o", "DDRs2 low-side output lanes"),
        ("adapter_to_ddrs2", "ddrs2_data_h_o[18:0]", "u_ddrs2_adapter.ddrs2_data_h_o", "top.ddrs2_data_h_o", "DDRs2 high-side output lanes"),
        ("adapter_to_ddrs2", "ddrs2_clk_160m_o", "u_ddrs2_adapter.ddrs2_clk_160m_o", "top.ddrs2_clk_160m_o", "forwarded DDRs2 clock"),
    ]
    with path.open("w", newline="") as fh:
        writer = csv.writer(fh, lineterminator="\n")
        writer.writerow(["class", "net", "source", "sink", "note"])
        writer.writerows(rows)


def write_status(
    path: Path,
    repo_root: Path,
    plan_root: Path,
    smoke_root: Path | None,
    filelist: Path,
    assembly_rtl: Path,
    blackboxes: Path,
    connection_manifest: Path,
    errors: list[str],
) -> None:
    plan_status = read_status(plan_root / "tx_egress_leaf_assembly_status.rpt")
    smoke_status = read_status(smoke_root / "reports/tx_egress_leaf_assembly_smoke_status.rpt") if smoke_root else {}

    if plan_status.get("STATUS") != "PASS":
        errors.append("plan status is not PASS")
    if plan_status.get("RESULT") != "FIXED_LEAF_ASSEMBLY_PLAN_READY_FOR_REVIEW":
        errors.append("plan result is not FIXED_LEAF_ASSEMBLY_PLAN_READY_FOR_REVIEW")
    if smoke_root and smoke_status.get("RESULT") != "FIXED_LEAF_ASSEMBLY_SMOKE_PLACED":
        errors.append("smoke result is not FIXED_LEAF_ASSEMBLY_SMOKE_PLACED")
    if smoke_root and smoke_status.get("CHECK_PLACE_STATUS") != "PASS":
        errors.append("smoke CHECK_PLACE_STATUS is not PASS")

    result = "CONNECTED_LEAF_ASSEMBLY_READY_FOR_GENUS_GLUE_SYNTH" if not errors else "CONNECTED_LEAF_ASSEMBLY_REVIEW_REQUIRED"
    status = "PASS" if not errors else "REVIEW_REQUIRED"

    with path.open("w") as fh:
        fh.write("LABEL=TX_EGRESS_CONNECTED_LEAF_ASSEMBLY\n")
        fh.write(f"STATUS={status}\n")
        fh.write(f"RESULT={result}\n")
        fh.write("SIGNOFF_READY=NO\n")
        fh.write(f"REPO_HEAD={repo_head(repo_root)}\n")
        fh.write(f"PLAN_ROOT={plan_root}\n")
        if smoke_root:
            fh.write(f"SMOKE_ROOT={smoke_root}\n")
        fh.write(f"TOP_MODULE={TOP_MODULE}\n")
        fh.write(f"ASSEMBLY_RTL={assembly_rtl}\n")
        fh.write(f"LEAF_BLACKBOX_RTL={blackboxes}\n")
        fh.write(f"GENUS_FILELIST={filelist}\n")
        fh.write(f"CONNECTION_MANIFEST={connection_manifest}\n")
        fh.write("LEAF_POLICY=BLACKBOX_FIXED_ABSTRACTS\n")
        fh.write("GLUE_LOGIC_STATUS=PRESERVED_FROM_SPADMIC_TX_EGRESS_CORE\n")
        fh.write("ROUTE_STATUS=NOT_RUN\n")
        fh.write("PG_CONNECTIVITY_STATUS=DEFERRED_TOP_LEVEL_HOOKUP\n")
        fh.write("PVS_STATUS=DEFERRED\n")
        fh.write("LVS_STATUS=DEFERRED\n")
        fh.write("PEX_STATUS=DEFERRED\n")
        fh.write("MMMC_STATUS=DEFERRED\n")
        if errors:
            fh.write("ERRORS=" + " | ".join(errors) + "\n")


def write_readme(path: Path, status_path: Path, filelist: Path, assembly_rtl: Path, blackboxes: Path, connection_manifest: Path) -> None:
    now = dt.datetime.now(dt.timezone.utc).isoformat()
    path.write_text(
        "\n".join(
            [
                "# TX Egress Connected Fixed-Leaf Assembly",
                "",
                f"Created: {now}",
                "",
                "This package preserves the small `spadmic_tx_egress_core` glue logic",
                "and instances the four validated TX leaves as black boxes for the next",
                "Genus glue-synthesis and Innovus fixed-leaf assembly gate.",
                "",
                "Generated files:",
                "",
                f"- `{assembly_rtl.name}`",
                f"- `{blackboxes.name}`",
                f"- `{filelist.name}`",
                f"- `{connection_manifest.name}`",
                f"- `{status_path.name}`",
                "",
                "This is not route, PG hookup, PVS, LVS, PEX, MMMC, or signoff.",
                "The next gate is to synthesize only the glue around the fixed leaf",
                "abstracts, then import the resulting assembly netlist with the same",
                "placement Tcl that passed the macro smoke.",
                "",
            ]
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan-root", required=True, type=Path)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--repo-root", default=Path.cwd(), type=Path)
    parser.add_argument("--smoke-root", type=Path)
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    plan_root = args.plan_root.resolve()
    out_dir = args.out_dir.resolve()
    smoke_root = args.smoke_root.resolve() if args.smoke_root else None
    out_dir.mkdir(parents=True, exist_ok=True)

    errors: list[str] = []
    require_file(plan_root / "tx_egress_leaf_assembly_status.rpt", errors, "assembly plan status")
    require_file(plan_root / "tx_egress_leaf_assembly_place.tcl", errors, "assembly placement Tcl")
    if smoke_root:
        require_file(smoke_root / "reports/tx_egress_leaf_assembly_smoke_status.rpt", errors, "assembly smoke status")

    assembly_rtl = out_dir / "tx_egress_leaf_connected_assembly.sv"
    blackboxes = out_dir / "tx_egress_leaf_blackboxes.sv"
    filelist = out_dir / "tx_egress_leaf_connected_assembly.f"
    connection_manifest = out_dir / "tx_egress_leaf_connected_assembly_connections.csv"
    status_path = out_dir / "tx_egress_leaf_connected_assembly_status.rpt"

    write_assembly_rtl(assembly_rtl, repo_root)
    write_blackboxes(blackboxes, repo_root)
    write_filelist(filelist, repo_root, blackboxes, assembly_rtl)
    write_connection_manifest(connection_manifest)
    write_status(
        status_path,
        repo_root,
        plan_root,
        smoke_root,
        filelist,
        assembly_rtl,
        blackboxes,
        connection_manifest,
        errors,
    )
    write_readme(out_dir / "README.md", status_path, filelist, assembly_rtl, blackboxes, connection_manifest)

    status = read_status(status_path)
    print(f"CONNECTED_ASSEMBLY_ROOT={out_dir}")
    print(f"CONNECTED_ASSEMBLY_STATUS={status_path}")
    print(f"CONNECTED_ASSEMBLY_FILELIST={filelist}")
    print(f"CONNECTED_ASSEMBLY_RTL={assembly_rtl}")
    print(f"CONNECTED_ASSEMBLY_BLACKBOXES={blackboxes}")
    print(f"CONNECTED_ASSEMBLY_CONNECTIONS={connection_manifest}")
    print(f"CONNECTED_ASSEMBLY_RESULT={status.get('RESULT', 'UNKNOWN')}")
    rc = 0 if status.get("STATUS") == "PASS" else 8
    print(f"CONNECTED_ASSEMBLY_RC={rc}")
    sys.exit(rc)


if __name__ == "__main__":
    main()
