# ####################################################################

#  Created by Genus(TM) Synthesis Solution 22.13-s093_1 on Tue May 12 16:18:10 CEST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design mptdc_top_asic

create_clock -name "clk_sys" -period 6.25 -waveform {0.0 3.125} [get_ports clk_sys]
create_clock -name "clk_osc_slow" -period 1.0 -waveform {0.0 0.5} [get_pins {u_core_u_osc_slow_u_stub/phase[0]}]
create_clock -name "clk_osc_fast" -period 0.9 -waveform {0.0 0.45} [get_pins {u_core_u_osc_fast_u_stub/phase[0]}]
set_clock_transition 0.15 [get_clocks clk_sys]
set_load -pin_load 0.01 [get_ports csr_ready_o]
set_load -pin_load 0.01 [get_ports csr_rvalid_o]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[31]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[30]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[29]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[28]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[27]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[26]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[25]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[24]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[23]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[22]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[21]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[20]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[19]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[18]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[17]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[16]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[15]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[14]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[13]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[12]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[11]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[10]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[9]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[8]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[7]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[6]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[5]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[4]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[3]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[2]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[1]}]
set_load -pin_load 0.01 [get_ports {csr_rdata_o[0]}]
set_load -pin_load 0.01 [get_ports narrow_valid_o]
set_load -pin_load 0.01 [get_ports {narrow_data_o[15]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[14]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[13]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[12]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[11]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[10]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[9]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[8]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[7]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[6]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[5]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[4]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[3]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[2]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[1]}]
set_load -pin_load 0.01 [get_ports {narrow_data_o[0]}]
set_load -pin_load 0.01 [get_ports acq_valid_o]
set_load -pin_load 0.01 [get_ports {acq_data_o[49]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[48]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[47]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[46]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[45]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[44]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[43]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[42]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[41]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[40]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[39]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[38]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[37]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[36]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[35]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[34]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[33]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[32]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[31]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[30]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[29]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[28]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[27]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[26]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[25]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[24]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[23]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[22]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[21]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[20]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[19]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[18]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[17]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[16]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[15]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[14]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[13]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[12]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[11]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[10]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[9]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[8]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[7]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[6]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[5]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[4]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[3]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[2]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[1]}]
set_load -pin_load 0.01 [get_ports {acq_data_o[0]}]
set_load -pin_load 0.01 [get_ports fifo_full_o]
set_false_path -from [list \
  [get_ports start_spad_async_i]  \
  [get_ports stop_spad_async_i]  \
  [get_ports cal_start_async_i]  \
  [get_ports cal_stop_async_i]  \
  [get_ports async_rst_n] ]
set_max_delay 6.25 -from [list \
  [get_clocks clk_osc_slow]  \
  [get_clocks clk_osc_fast] ] -to [get_clocks clk_sys]
set_max_delay 0.9 -from [get_clocks clk_sys] -to [get_clocks clk_osc_fast]
set_clock_groups -name "clock_groups_clk_sys_to_clk_osc_slow_to_clk_osc_fast" -asynchronous -group [get_clocks clk_sys] -group [get_clocks clk_osc_slow] -group [get_clocks clk_osc_fast]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports input_sel_override_en_i]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {input_sel_override_i[0]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports out_mode_override_en_i]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {out_mode_override_i[1]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {out_mode_override_i[0]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports csr_valid_i]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports csr_write_i]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_addr_i[5]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_addr_i[4]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_addr_i[3]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_addr_i[2]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_addr_i[1]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_addr_i[0]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[31]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[30]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[29]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[28]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[27]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[26]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[25]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[24]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[23]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[22]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[21]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[20]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[19]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[18]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[17]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[16]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[15]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[14]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[13]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[12]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[11]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[10]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[9]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[8]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[7]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[6]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[5]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[4]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[3]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[2]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[1]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_wdata_i[0]}]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports narrow_ready_i]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports shared_readout_en_i]
set_input_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports acq_ready_i]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports csr_ready_o]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports csr_rvalid_o]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[31]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[30]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[29]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[28]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[27]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[26]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[25]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[24]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[23]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[22]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[21]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[20]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[19]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[18]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[17]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[16]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[15]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[14]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[13]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[12]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[11]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[10]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[9]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[8]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[7]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[6]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[5]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[4]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[3]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[2]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[1]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {csr_rdata_o[0]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports narrow_valid_o]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[15]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[14]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[13]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[12]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[11]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[10]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[9]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[8]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[7]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[6]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[5]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[4]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[3]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[2]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[1]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {narrow_data_o[0]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports acq_valid_o]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[49]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[48]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[47]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[46]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[45]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[44]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[43]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[42]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[41]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[40]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[39]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[38]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[37]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[36]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[35]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[34]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[33]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[32]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[31]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[30]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[29]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[28]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[27]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[26]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[25]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[24]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[23]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[22]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[21]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[20]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[19]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[18]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[17]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[16]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[15]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[14]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[13]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[12]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[11]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[10]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[9]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[8]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[7]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[6]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[5]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[4]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[3]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[2]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[1]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports {acq_data_o[0]}]
set_output_delay -clock [get_clocks clk_sys] -add_delay 0.5 [get_ports fifo_full_o]
set_max_fanout 20.000 [current_design]
set_max_transition 0.5 [current_design]
set_input_transition 0.1 [get_ports async_rst_n]
set_input_transition 0.1 [get_ports start_spad_async_i]
set_input_transition 0.1 [get_ports stop_spad_async_i]
set_input_transition 0.1 [get_ports cal_start_async_i]
set_input_transition 0.1 [get_ports cal_stop_async_i]
set_input_transition 0.1 [get_ports input_sel_override_en_i]
set_input_transition 0.1 [get_ports {input_sel_override_i[0]}]
set_input_transition 0.1 [get_ports out_mode_override_en_i]
set_input_transition 0.1 [get_ports {out_mode_override_i[1]}]
set_input_transition 0.1 [get_ports {out_mode_override_i[0]}]
set_input_transition 0.1 [get_ports csr_valid_i]
set_input_transition 0.1 [get_ports csr_write_i]
set_input_transition 0.1 [get_ports {csr_addr_i[5]}]
set_input_transition 0.1 [get_ports {csr_addr_i[4]}]
set_input_transition 0.1 [get_ports {csr_addr_i[3]}]
set_input_transition 0.1 [get_ports {csr_addr_i[2]}]
set_input_transition 0.1 [get_ports {csr_addr_i[1]}]
set_input_transition 0.1 [get_ports {csr_addr_i[0]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[31]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[30]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[29]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[28]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[27]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[26]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[25]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[24]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[23]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[22]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[21]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[20]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[19]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[18]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[17]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[16]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[15]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[14]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[13]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[12]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[11]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[10]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[9]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[8]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[7]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[6]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[5]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[4]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[3]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[2]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[1]}]
set_input_transition 0.1 [get_ports {csr_wdata_i[0]}]
set_input_transition 0.1 [get_ports narrow_ready_i]
set_input_transition 0.1 [get_ports shared_readout_en_i]
set_input_transition 0.1 [get_ports acq_ready_i]
set_ideal_network [get_ports clk_sys]
set_ideal_network [get_ports async_rst_n]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFR2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFR2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFR4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFR4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFR8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFR8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQ2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQ2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQ4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQ4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQ8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQ8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRR2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRR2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRR4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRR4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRR8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRR8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQ2HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQ2HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQ4HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQ4HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQ8HDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQ8HDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFRQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFFSQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRRQSSHDX4]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQSSHDX0]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQSSHDX1]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQSSHDX2]
set_dont_use true [get_lib_cells D_CELLS_HD_LPMOS_slow_1_62V_125C/SDFRSQSSHDX4]
set_clock_uncertainty -setup 0.3 [get_clocks clk_sys]
set_clock_uncertainty -hold 0.3 [get_clocks clk_sys]
set_clock_uncertainty -setup 0.05 [get_clocks clk_osc_slow]
set_clock_uncertainty -hold 0.05 [get_clocks clk_osc_slow]
set_clock_uncertainty -setup 0.05 [get_clocks clk_osc_fast]
set_clock_uncertainty -hold 0.05 [get_clocks clk_osc_fast]
