#!/usr/bin/env bash
# =============================================================================
# SPADMIC TOP -- Genus glue synthesis for TX egress connected fixed-leaf assembly
# =============================================================================
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  TOP/syn/scripts/run_genus_tx_egress_connected_assembly.sh <CONNECTED_ASSEMBLY_ROOT> [RUN_ID]

This synthesizes only the TX egress assembly glue around the four fixed leaf
black boxes generated by run_tx_egress_connected_assembly.sh. It does not
implement the leaf internals, route, hook PG, run PVS/LVS/PEX/MMMC, or claim
signoff.
USAGE
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
  usage >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOP_SYN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TOP_ROOT="$(cd "$TOP_SYN_DIR/.." && pwd)"
REPO_ROOT="$(cd "$TOP_ROOT/.." && pwd)"
MPTDC_ROOT="$REPO_ROOT/MPTDC"

CONNECTED_ROOT="$1"
RUN_ID="${2:-genus_tx_egress_connected_assembly_$(date +%Y%m%d_%H%M)}"
WORK_ROOT="${SPADMIC_WORK_ROOT:-/sim/ksabra/SPADMIC_work}"
RUN_ROOT="$WORK_ROOT/genus/$RUN_ID"
BLOCK_NAME="tx_egress_connected_assembly"
TOP_MODULE="spadmic_tx_egress_leaf_assembly"
COMMON_SDC="$TOP_SYN_DIR/constraints/ooc/spadmic_tx_egress_core.sdc"

export MPTDC_XH018_STACK="${MPTDC_XH018_STACK:-xx31}"
export MPTDC_STDCELL_FAMILY="${MPTDC_STDCELL_FAMILY:-JIHD}"
export MPTDC_PNR_ROUTE_LAYER_NAMES="${MPTDC_PNR_ROUTE_LAYER_NAMES:-MET1 MET2 MET3 METTP}"
export MPTDC_PNR_SIGNAL_TOP_LAYER="${MPTDC_PNR_SIGNAL_TOP_LAYER:-MET3}"
export MPTDC_PNR_EFFECTIVE_TOP_FLOOR_LAYER="${MPTDC_PNR_EFFECTIVE_TOP_FLOOR_LAYER:-METTP}"
export MPTDC_PNR_POWER_LAYER="${MPTDC_PNR_POWER_LAYER:-METTP}"
export MPTDC_PNR_PHASE_TOP_LAYER="${MPTDC_PNR_PHASE_TOP_LAYER:-METTP}"

STATUS_RPT="$CONNECTED_ROOT/tx_egress_leaf_connected_assembly_status.rpt"
CONNECTED_FILELIST="$CONNECTED_ROOT/tx_egress_leaf_connected_assembly.f"

fail_summary() {
  local rc="$1"
  local reason="$2"
  mkdir -p "$RUN_ROOT"
  {
    echo "# TX Egress Connected Assembly Genus Glue"
    echo
    echo "- Run ID: \`$RUN_ID\`"
    echo "- Run root: \`$RUN_ROOT\`"
    echo "- Connected root: \`$CONNECTED_ROOT\`"
    echo "- Result: \`FAIL\`"
    echo "- First error: \`$reason\`"
    echo
    echo "This run did not claim signoff."
  } > "$RUN_ROOT/SUMMARY.md"
  cat "$RUN_ROOT/SUMMARY.md"
  echo "TX_CONNECTED_GENUS_RC=$rc"
  echo "TX_CONNECTED_GENUS_RUN_ID=$RUN_ID"
  echo "TX_CONNECTED_GENUS_ROOT=$RUN_ROOT"
  exit "$rc"
}

[[ -d "$CONNECTED_ROOT" ]] || fail_summary 2 "connected assembly root missing: $CONNECTED_ROOT"
[[ -s "$STATUS_RPT" ]] || fail_summary 2 "connected assembly status missing: $STATUS_RPT"
[[ -s "$CONNECTED_FILELIST" ]] || fail_summary 2 "connected assembly filelist missing: $CONNECTED_FILELIST"
grep -qx 'STATUS=PASS' "$STATUS_RPT" || fail_summary 2 "connected assembly status is not PASS"
grep -qx 'RESULT=CONNECTED_LEAF_ASSEMBLY_READY_FOR_GENUS_GLUE_SYNTH' "$STATUS_RPT" || fail_summary 2 "connected assembly result is not ready for Genus glue synthesis"
[[ ! -e "$RUN_ROOT" ]] || fail_summary 2 "run directory already exists: $RUN_ROOT"

mkdir -p "$RUN_ROOT/filelists" "$RUN_ROOT/logs"

TOP_FILELIST="$RUN_ROOT/filelists/tx_egress_connected_assembly.f"
EMPTY_FILELIST="$RUN_ROOT/filelists/empty.f"
cp "$CONNECTED_FILELIST" "$TOP_FILELIST"
: > "$EMPTY_FILELIST"

while IFS= read -r file; do
  [[ -z "$file" || "$file" =~ ^[[:space:]]*// ]] && continue
  [[ -f "$file" ]] || fail_summary 4 "missing source file in connected filelist: $file"
done < "$TOP_FILELIST"

{
  echo "RUN_ID=$RUN_ID"
  echo "DATE_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "REPO_ROOT=$REPO_ROOT"
  echo "TOP_ROOT=$TOP_ROOT"
  echo "MPTDC_ROOT=$MPTDC_ROOT"
  echo "RUN_ROOT=$RUN_ROOT"
  echo "CONNECTED_ROOT=$CONNECTED_ROOT"
  echo "BLOCK_NAME=$BLOCK_NAME"
  echo "TOP_MODULE=$TOP_MODULE"
  echo "CONNECTED_FILELIST=$CONNECTED_FILELIST"
  echo "COMMON_SDC=$COMMON_SDC"
  echo "LEAF_POLICY=BLACKBOX_FIXED_ABSTRACTS"
  echo "MPTDC_XH018_STACK=$MPTDC_XH018_STACK"
  echo "MPTDC_STDCELL_FAMILY=$MPTDC_STDCELL_FAMILY"
  echo "MPTDC_PNR_ROUTE_LAYER_NAMES=$MPTDC_PNR_ROUTE_LAYER_NAMES"
  echo "BRANCH=$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || echo unknown)"
  echo "HEAD=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
  echo "STATUS_SHORT_BEGIN"
  git -C "$REPO_ROOT" status --short 2>/dev/null || true
  echo "STATUS_SHORT_END"
} > "$RUN_ROOT/run_manifest.txt"
git -C "$REPO_ROOT" status --short > "$RUN_ROOT/git_status_short.txt" 2>/dev/null || true

if ! command -v genus >/dev/null 2>&1; then
  fail_summary 5 "genus not found in PATH; source /eda/cadence/eda_2023-2024"
fi

block_dir="$RUN_ROOT/$BLOCK_NAME"
mkdir -p "$block_dir/logs"
log="$block_dir/logs/genus.log"

echo "=== Genus glue synthesis: $BLOCK_NAME ($TOP_MODULE) ==="
set +e
SPADMIC_REPO_ROOT="$REPO_ROOT" \
SPADMIC_TOP_ROOT="$TOP_ROOT" \
SPADMIC_MPTDC_ROOT="$MPTDC_ROOT" \
GENUS_RUN_DIR="$block_dir" \
GENUS_TOP_MODULE="$TOP_MODULE" \
GENUS_BLOCK_NAME="$BLOCK_NAME" \
GENUS_MPTDC_FILELIST="$EMPTY_FILELIST" \
GENUS_TOP_FILELIST="$TOP_FILELIST" \
GENUS_COMMON_SDC="$COMMON_SDC" \
  genus -files "$SCRIPT_DIR/run_genus_matrix_block.tcl" -log "$log" > "$block_dir/logs/genus.stdout.log" 2>&1
genus_rc=$?
set -e

if [[ "$genus_rc" -ne 0 ]]; then
  tail -120 "$block_dir/logs/genus.stdout.log" > "$block_dir/logs/failure.tail" || true
  {
    echo "# TX Egress Connected Assembly Genus Glue"
    echo
    echo "- Run ID: \`$RUN_ID\`"
    echo "- Run root: \`$RUN_ROOT\`"
    echo "- Connected root: \`$CONNECTED_ROOT\`"
    echo "- Block: \`$BLOCK_NAME\`"
    echo "- Top module: \`$TOP_MODULE\`"
    echo "- Result: \`FAIL\`"
    echo "- Genus exit code: \`$genus_rc\`"
    echo "- Failure tail: \`$block_dir/logs/failure.tail\`"
    echo
    echo "No route handoff was declared."
  } > "$RUN_ROOT/SUMMARY.md"
  cat "$RUN_ROOT/SUMMARY.md"
  echo "TX_CONNECTED_GENUS_RC=$genus_rc"
  echo "TX_CONNECTED_GENUS_RUN_ID=$RUN_ID"
  echo "TX_CONNECTED_GENUS_ROOT=$RUN_ROOT"
  exit "$genus_rc"
fi

NETLIST="$block_dir/outputs/$BLOCK_NAME.postsyn.v"
SDC="$block_dir/outputs/$BLOCK_NAME.postsyn.sdc"
[[ -s "$NETLIST" ]] || fail_summary 6 "Genus netlist missing after PASS: $NETLIST"
[[ -s "$SDC" ]] || fail_summary 6 "Genus SDC missing after PASS: $SDC"

{
  echo "LABEL=TX_EGRESS_CONNECTED_ASSEMBLY_GENUS_GLUE"
  echo "STATUS=PASS"
  echo "RESULT=CONNECTED_ASSEMBLY_GLUE_SYNTH_READY_FOR_INNOVUS_ROUTE"
  echo "SIGNOFF_READY=NO"
  echo "RUN_ID=$RUN_ID"
  echo "RUN_ROOT=$RUN_ROOT"
  echo "CONNECTED_ROOT=$CONNECTED_ROOT"
  echo "BLOCK_RUN_ROOT=$block_dir"
  echo "TOP_MODULE=$TOP_MODULE"
  echo "NETLIST=$NETLIST"
  echo "SDC=$SDC"
  echo "LEAF_POLICY=BLACKBOX_FIXED_ABSTRACTS"
  echo "ROUTE_STATUS=NOT_RUN"
  echo "PG_CONNECTIVITY_STATUS=DEFERRED_TOP_LEVEL_HOOKUP"
  echo "PVS_STATUS=DEFERRED"
  echo "LVS_STATUS=DEFERRED"
  echo "PEX_STATUS=DEFERRED"
  echo "MMMC_STATUS=DEFERRED"
} > "$RUN_ROOT/tx_egress_connected_assembly_genus_status.rpt"

{
  echo "# TX Egress Connected Assembly Genus Glue"
  echo
  echo "- Run ID: \`$RUN_ID\`"
  echo "- Run root: \`$RUN_ROOT\`"
  echo "- Connected root: \`$CONNECTED_ROOT\`"
  echo "- Block: \`$BLOCK_NAME\`"
  echo "- Top module: \`$TOP_MODULE\`"
  echo "- Result: \`CONNECTED_ASSEMBLY_GLUE_SYNTH_READY_FOR_INNOVUS_ROUTE\`"
  echo "- Netlist: \`$NETLIST\`"
  echo "- SDC: \`$SDC\`"
  echo
  echo "This is typical-only glue synthesis around fixed black-box leaves. It is not"
  echo "route, PG hookup, PVS, LVS, PEX, MMMC, or signoff."
} > "$RUN_ROOT/SUMMARY.md"

cat "$RUN_ROOT/SUMMARY.md"
echo "TX_CONNECTED_GENUS_RC=0"
echo "TX_CONNECTED_GENUS_RUN_ID=$RUN_ID"
echo "TX_CONNECTED_GENUS_ROOT=$RUN_ROOT"
echo "TX_CONNECTED_GENUS_STATUS=$RUN_ROOT/tx_egress_connected_assembly_genus_status.rpt"
echo "TX_CONNECTED_GENUS_NETLIST=$NETLIST"
echo "TX_CONNECTED_GENUS_SDC=$SDC"

exit 0
