#!/usr/bin/env bash
# Run the immutable MPTDC RO6 PVS preparation, DRC, and LVS evidence chain.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
REPO_ROOT="${MPTDC_RECOVERY_REPO_ROOT:-$DEFAULT_REPO_ROOT}"
PUBLISHER="${MPTDC_RECOVERY_PUBLISHER:-$REPO_ROOT/MPTDC/ci/publish_mptdc_server_snapshot.sh}"
PREP_SCRIPT="${MPTDC_RECOVERY_PVS_PREP:-$SCRIPT_DIR/00_prepare_pvs_inputs_from_checkpoint.sh}"
AUDIT_SCRIPT="${MPTDC_RECOVERY_PVS_AUDIT:-$SCRIPT_DIR/01_audit_pvs_templates.sh}"
DRC_SCRIPT="${MPTDC_RECOVERY_PVS_DRC:-$SCRIPT_DIR/02_replay_pvs_drc_from_template.sh}"
LVS_SCRIPT="${MPTDC_RECOVERY_PVS_LVS:-$SCRIPT_DIR/03_replay_pvs_lvs_from_template.sh}"
INNOVUS_WORK="${MPTDC_INNOVUS_WORK:-/sim/ksabra/SPADMIC_work/innovus}"
DEFAULT_RO_GDS="/sim/ksabra/SPADMIC_work/innovus/20260701_mptdc_211109_falsepath_nfast_risk_235618/drygds_oa_20260702_001608/merge_libs/RO_tune6_from_OA.gds"

PNR_RUN_ID=""
PVS_RUN_ID=""
EXPECTED_HEAD_VALUE="${EXPECTED_HEAD:-}"
RO_GDS="${MPTDC_PVS_RO_GDS:-$DEFAULT_RO_GDS}"

usage() {
  cat <<'USAGE'
Usage:
  server_run_mptdc_ro6_recovery_pvs.sh --pnr-run-id <id> [options]

Options:
  --pnr-run-id <id>      Published strict-clean or exact-PG-candidate physical
                         PnR run id with closed TC timing/DRV and audited halos.
  --run-id <id>          PVS result directory name. A unique id is generated by default.
  --expected-head <sha>  Require the checked-out repository HEAD.
  --ro-gds <path>        Explicit real-OA RO_tune6 GDS.
  --innovus-work <path>  Innovus/PVS result root.
  -h, --help             Show this help.

The command runs preparation, template audit, base DRC, density DRC, and LVS in
order. Each launched step writes an operator gate and publishes a bounded text
snapshot. The chain stops at the first failed gate or failed evidence push.
USAGE
}

report_value() {
  local report="$1"
  local key="$2"
  local value
  value="$(sed -n "s/^${key}=//p" "$report" 2>/dev/null | tail -1)"
  if [[ -n "$value" ]]; then printf '%s\n' "$value"; else printf 'MISSING\n'; fi
}

numeric_ge() {
  local actual="$1"
  local minimum="$2"
  awk -v actual="$actual" -v minimum="$minimum" \
    'BEGIN {exit !(actual ~ /^[-+]?[0-9]+([.][0-9]+)?$/ && actual + 0 >= minimum + 0)}'
}

expected_pg_wire_end_fingerprint() {
  printf '%s\n' \
    'VDD|MET3|221.750|681.160' \
    'VDD|MET3|48.000|681.160' \
    'VDD|MET3|221.750|201.160' \
    'VDD|MET3|48.000|201.160' \
    'VDD|METTP|121.160|233.620' \
    'VDD|METTP|121.160|648.320' \
    'VSS|MET3|221.750|685.160' \
    'VSS|MET3|48.000|685.160' \
    'VSS|MET3|221.750|205.160' \
    'VSS|MET3|48.000|205.160' \
    'VSS|METTP|205.160|158.320' \
    'VSS|METTP|125.160|721.750' \
    'VSS|METTP|125.160|648.320' \
    'VSS|METTP|125.160|233.620' \
    'VSS|METTP|125.160|158.320' | sort
}

actual_pg_wire_end_fingerprint() {
  local report="$1"
  awk '
    /^Net (VDD|VSS): dangling Wire at / {
      net=$2; sub(/:$/, "", net)
      x1=$6; y1=$7; x2=$8; y2=$9
      gsub(/[(),]/, "", x1); gsub(/[(),]/, "", y1)
      gsub(/[(),]/, "", x2); gsub(/[(),]/, "", y2)
      if ((x1 + 0) != (x2 + 0) || (y1 + 0) != (y2 + 0)) {
        print "INVALID_NON_POINT_WIRE_END"
      } else {
        printf "%s|%s|%.3f|%.3f\n", net, $12, x1, y1
      }
    }
  ' "$report" 2>/dev/null | sort
}

tracked_candidate_fingerprint_passes() {
  local gate="$1"
  local reports_dir detail status rel summary_count detail_count other_count
  local other_problem_count
  reports_dir="$(dirname "$gate")"
  detail="$reports_dir/route_connectivity_special_detailed.rpt"
  status="$reports_dir/route_pg_pvs_candidate_status.rpt"
  for path in "$detail" "$status"; do
    rel="${path#"$REPO_ROOT"/}"
    git -C "$REPO_ROOT" ls-files --error-unmatch "$rel" >/dev/null 2>&1 || return 1
    [[ -s "$path" ]] || return 1
  done
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_PROFILE)" == HALO10_PNRLEF_15 ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_EXPECTED_COUNT)" == 15 ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_ACTUAL_COUNT)" == 15 ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_SUMMARY_COUNT)" == 15 ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_EXACT_MATCH)" == 1 ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_OTHER_NET_LINE_COUNT)" == 0 ]] || return 1
  [[ "$(report_value "$status" ROUTE_PG_PVS_CANDIDATE_OTHER_PROBLEM_LINE_COUNT)" == 0 ]] || return 1
  summary_count="$(sed -nE 's/^[[:space:]]*([0-9]+) Problem\(s\) \(IMPVFC-94\):.*/\1/p' "$detail" | tail -1)"
  detail_count="$(grep -Ec '^Net (VDD|VSS): dangling Wire at ' "$detail" 2>/dev/null || true)"
  other_count="$(grep -E '^Net (VDD|VSS):' "$detail" 2>/dev/null | grep -Evc ': dangling Wire at ' || true)"
  other_problem_count="$(grep -E 'Problem\(s\).*\(IMPVFC-' "$detail" 2>/dev/null \
    | grep -Evc '\(IMPVFC-94\):[[:space:]]+The net has dangling wire\(s\)' || true)"
  [[ "$summary_count" == 15 && "$detail_count" == 15 && "$other_count" == 0 && \
     "$other_problem_count" == 0 ]] || return 1
  [[ "$(actual_pg_wire_end_fingerprint "$detail")" == "$(expected_pg_wire_end_fingerprint)" ]]
}

load_cadence_env() {
  local env_file="$1"
  local source_rc=0

  echo "CADENCE_ENV=$env_file"
  if [[ ! -r "$env_file" ]]; then
    echo "CADENCE_ENV_RC=0"
    echo "CADENCE_ENV_STATUS=SKIPPED_NOT_READABLE"
    return 0
  fi

  # Site setup files are written for interactive shells and may read unset
  # variables. Keep the recovery driver's nounset policy outside this boundary.
  set +u
  set +e
  # shellcheck disable=SC1090
  source "$env_file" >/dev/null 2>&1
  source_rc=$?
  set +e
  set -u
  set -o pipefail

  echo "CADENCE_ENV_RC=$source_rc"
  if [[ "$source_rc" -eq 0 ]]; then
    echo "CADENCE_ENV_STATUS=PASS"
    return 0
  fi

  echo "CADENCE_ENV_STATUS=FAIL"
  return "$source_rc"
}

tracked_physical_gate_passes() {
  local report="$1"
  local rel="${report#"$REPO_ROOT"/}"
  local route_status mode decision special_bad special_raw
  git -C "$REPO_ROOT" ls-files --error-unmatch "$rel" >/dev/null 2>&1 || return 1
  [[ -s "$report" ]] || return 1
  [[ "$(report_value "$report" STEP)" == PHYSICAL_PNR ]] || return 1
  [[ "$(report_value "$report" PNR_RC)" == 0 ]] || return 1
  [[ "$(report_value "$report" INNOVUS_VERIFY_DRC_STATUS)" == PASS ]] || return 1
  for key in GEOMETRY_DRC_VIOLATIONS SHORTS REGULAR_NET_CONNECTIVITY_BAD \
    SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES UNROUTED_NETS \
    RO_HALO_TOTAL_INTRUSION_COUNT RO_HALO_INVALID_INSTANCE_BBOX_COUNT; do
    [[ "$(report_value "$report" "$key")" == 0 ]] || return 1
  done
  [[ "$(report_value "$report" signal_top_layer)" == MET3 ]] || return 1
  [[ "$(report_value "$report" router_command_top_layer)" == METTP ]] || return 1
  [[ "$(report_value "$report" ROUTE_COMMAND_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" SIGNAL_TOP_ROUTE_BLOCKAGE_TEMPORARY)" == 1 ]] || return 1
  [[ "$(report_value "$report" SIGNAL_TOP_ROUTE_BLOCKAGE_CREATE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" SIGNAL_TOP_ROUTE_BLOCKAGE_REMOVE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" SIGNAL_TOP_ROUTE_BLOCKAGE_STATUS)" == REMOVED ]] || return 1
  [[ "$(report_value "$report" PRE_ROUTE_SROUTE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" PRE_ROUTE_DANGLING_MAX)" == 35 ]] || return 1
  [[ "$(report_value "$report" PRE_ROUTE_DANGLING_FATAL_COUNT)" == 0 ]] || return 1
  [[ "$(report_value "$report" PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT)" == 0 ]] || return 1
  [[ "$(report_value "$report" PNR_LEF_SUMMARY_BINDING_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" PNR_LEF_PATH_MATCH_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" PNR_LEF_EVIDENCE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" PNR_LEF_GATE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" PNR_LEF_REQUESTED_SHA256)" == \
      "$(report_value "$report" PNR_LEF_ACTUAL_SHA256)" ]] || return 1
  [[ "$(report_value "$report" PNR_LEF_ACTUAL_SHA256)" == \
      "$(report_value "$report" PNR_LEF_EXPECTED_SHA256)" ]] || return 1
  [[ "$(report_value "$report" RO_HALOS_REQUESTED)" == 1 ]] || return 1
  [[ "$(report_value "$report" RO_HALO_ENABLED)" == 1 ]] || return 1
  [[ "$(report_value "$report" RO_HALO_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" RO_HALO_COUNT)" == 2 ]] || return 1
  [[ "$(report_value "$report" SLOW_HALO_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" FAST_HALO_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" RO_HALO_OCCUPANCY_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" RO_HALO_AUDITED_RO_COUNT)" == 2 ]] || return 1
  [[ "$(report_value "$report" RO_PHASE_PLACEMENT_STATUS)" == PASS ]] || return 1
  numeric_ge "$(report_value "$report" RO_HALO_CLEARANCE_UM)" 10.0 || return 1
  numeric_ge "$(report_value "$report" RO_PHASE_MIN_CLEARANCE_UM)" 10.0 || return 1
  [[ "$(report_value "$report" EXTRACTION_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" SETUP_STATUS_TC)" == PASS ]] || return 1
  [[ "$(report_value "$report" TC_HOLD_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" DRV_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" POWER_REPORT_CAPTURE_STATUS)" == PASS ]] || return 1
  [[ "$(report_value "$report" IO_PIN_PLACEMENT_STATUS)" == OK ]] || return 1
  [[ "$(report_value "$report" ro_slow_tap0_o_SOUTH_MET3_PLAN_COUNT)" == 1 ]] || return 1
  [[ "$(report_value "$report" ro_fast_tap0_o_SOUTH_MET3_PLAN_COUNT)" == 1 ]] || return 1
  [[ "$(report_value "$report" ro_slow_tap0_o_COUNT)" == 1 ]] || return 1
  [[ "$(report_value "$report" ro_fast_tap0_o_COUNT)" == 1 ]] || return 1
  [[ "$(report_value "$report" RO_TAP_OBSERVABILITY_PIN_COUNT)" == 2 ]] || return 1
  [[ "$(report_value "$report" COMMON_PHYSICAL_GATE)" == 1 ]] || return 1

  route_status="$(report_value "$report" ROUTE_STATUS)"
  mode="$(report_value "$report" PHYSICAL_GATE_MODE)"
  decision="$(report_value "$report" DECISION)"
  special_bad="$(report_value "$report" SPECIAL_NET_CONNECTIVITY_BAD)"
  special_raw="$(report_value "$report" SPECIAL_NET_CONNECTIVITY_RAW_BAD)"
  if [[ "$route_status" == PASS && "$mode" == STRICT_CLEAN && \
        "$decision" == PASS_CONTINUE && "$special_bad" == 0 && "$special_raw" == 0 ]]; then
    return 0
  fi
  [[ "$route_status" == PVS_CANDIDATE && \
     "$mode" == PVS_CANDIDATE_EXACT_PG_WIRE_ENDS && \
     "$decision" == PVS_CANDIDATE_CONTINUE && "$special_bad" == 1 && \
     "$special_raw" == 1 && \
     "$(report_value "$report" ALLOW_EXACT_PG_PVS_CANDIDATE)" == 1 && \
     "$(report_value "$report" ROUTE_PG_PVS_CANDIDATE_STATUS)" == PASS && \
     "$(report_value "$report" ROUTE_PG_PVS_CANDIDATE_EXACT_MATCH)" == 1 ]] || return 1
  tracked_candidate_fingerprint_passes "$report"
}

publish_stage() {
  local snapshot_id="$1"
  local step_label="$2"
  MPTDC_SNAPSHOT_MAX_TEXT_BYTES=2097152 \
    bash "$PUBLISHER" pvs "$snapshot_id" "$PVS_DIR" "$step_label"
  local rc=$?
  EXPECTED_HEAD_VALUE="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null)"
  return "$rc"
}

run_logged() {
  local log="$1"
  shift
  set +e
  "$@" 2>&1 | tee "$log"
  local rc=${PIPESTATUS[0]}
  set +e
  return "$rc"
}

stop_after_stage() {
  local step="$1"
  local decision="$2"
  local publish_rc="$3"
  echo "PVS_RECOVERY_STAGE=$step"
  echo "DECISION=$decision"
  echo "PUBLISH_RC=$publish_rc"
  echo "PVS_RUN_ID=$PVS_RUN_ID"
  echo "NEXT_EXPECTED_HEAD=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null)"
  echo "NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pnr-run-id) PNR_RUN_ID="${2:?missing --pnr-run-id value}"; shift 2 ;;
    --run-id) PVS_RUN_ID="${2:?missing --run-id value}"; shift 2 ;;
    --expected-head) EXPECTED_HEAD_VALUE="${2:?missing --expected-head value}"; shift 2 ;;
    --ro-gds) RO_GDS="${2:?missing --ro-gds value}"; shift 2 ;;
    --innovus-work) INNOVUS_WORK="${2:?missing --innovus-work value}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERROR: unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ -n "$PNR_RUN_ID" ]] || { echo "ERROR: --pnr-run-id is required" >&2; usage >&2; exit 2; }
[[ "$PNR_RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "ERROR: unsafe PnR run id" >&2; exit 2; }
if [[ -z "$PVS_RUN_ID" ]]; then
  PVS_RUN_ID="${PNR_RUN_ID}_realro_pvs_$(date +%Y%m%d_%H%M%S)"
fi
[[ "$PVS_RUN_ID" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "ERROR: unsafe PVS run id" >&2; exit 2; }

PNR_DIR="$INNOVUS_WORK/$PNR_RUN_ID"
SOURCE_CKPT="$PNR_DIR/checkpoints/04_route.enc.dat"
PVS_DIR="$INNOVUS_WORK/$PVS_RUN_ID"
PHYSICAL_GATE="$REPO_ROOT/MPTDC/docs/server_snapshots/innovus/$PNR_RUN_ID/reports/operator_gate_physical_pnr.rpt"

cd "$REPO_ROOT" || exit 3
ACTUAL_HEAD="$(git rev-parse HEAD 2>/dev/null)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
ORIGIN_HEAD="$(git rev-parse refs/remotes/origin/SPADMIC_test 2>/dev/null || true)"
EXPECTED_HEAD_VALUE="${EXPECTED_HEAD_VALUE:-${ORIGIN_HEAD:-$ACTUAL_HEAD}}"
TRACKED_STATUS="$(git status --short --untracked-files=no 2>/dev/null)"

echo "PNR_RUN_ID=$PNR_RUN_ID"
echo "PNR_DIR=$PNR_DIR"
echo "SOURCE_CKPT=$SOURCE_CKPT"
echo "PVS_RUN_ID=$PVS_RUN_ID"
echo "PVS_DIR=$PVS_DIR"
echo "RO_GDS=$RO_GDS"
echo "BRANCH=$BRANCH"
echo "ACTUAL_HEAD=$ACTUAL_HEAD"
echo "ORIGIN_HEAD=${ORIGIN_HEAD:-MISSING}"
echo "EXPECTED_HEAD=$EXPECTED_HEAD_VALUE"

PREFLIGHT=PASS
[[ "$BRANCH" == SPADMIC_test ]] || { echo "STOP: branch must be SPADMIC_test"; PREFLIGHT=FAIL; }
[[ "$ACTUAL_HEAD" == "$EXPECTED_HEAD_VALUE" ]] || { echo "STOP: HEAD mismatch"; PREFLIGHT=FAIL; }
[[ -z "$TRACKED_STATUS" ]] || { echo "$TRACKED_STATUS"; echo "STOP: tracked working tree is dirty"; PREFLIGHT=FAIL; }
tracked_physical_gate_passes "$PHYSICAL_GATE" || { echo "STOP: tracked accepted physical-PnR snapshot is missing or failed"; PREFLIGHT=FAIL; }
[[ -d "$SOURCE_CKPT" ]] || { echo "STOP: accepted route checkpoint missing: $SOURCE_CKPT"; PREFLIGHT=FAIL; }
[[ -s "$RO_GDS" ]] || { echo "STOP: real RO GDS missing or empty: $RO_GDS"; PREFLIGHT=FAIL; }
[[ ! -e "$PVS_DIR" ]] || { echo "STOP: PVS result directory already exists: $PVS_DIR"; PREFLIGHT=FAIL; }
for script in "$PUBLISHER" "$PREP_SCRIPT" "$AUDIT_SCRIPT" "$DRC_SCRIPT" "$LVS_SCRIPT"; do
  [[ -f "$script" ]] || { echo "STOP: required script missing: $script"; PREFLIGHT=FAIL; }
done

echo "PVS_RECOVERY_PREFLIGHT=$PREFLIGHT"
if [[ "$PREFLIGHT" != PASS ]]; then
  echo "DECISION=FAIL_STOP"
  exit 4
fi

CADENCE_ENV="${MPTDC_CADENCE_ENV:-/eda/cadence/eda_2023-2024}"
if ! load_cadence_env "$CADENCE_ENV"; then
  echo "STOP: failed to source Cadence environment: $CADENCE_ENV"
  echo "DECISION=FAIL_STOP"
  exit 5
fi
sha256sum "$RO_GDS"

set +e
bash "$PREP_SCRIPT" \
  --checkpoint "$SOURCE_CKPT" \
  --run-id "$PVS_RUN_ID" \
  --innovus-work "$INNOVUS_WORK" \
  --ro-gds "$RO_GDS" \
  --strict-attribution \
  --expected-head "$EXPECTED_HEAD_VALUE"
PREP_RC=$?
set +e

PREP_REPORT="$PVS_DIR/reports/pvs_prepared_inputs.rpt"
TAP_REPORT="$PVS_DIR/reports/tap_pin_contract.rpt"
HASH_REPORT="$PVS_DIR/manifests/pvs_input_hashes.rpt"
PREP_STATUS="$(report_value "$PREP_REPORT" PVS_PREP_INPUT_STATUS)"
TAP_STATUS="$(report_value "$TAP_REPORT" TAP_PIN_CONTRACT_STATUS)"
TAP_COUNT="$(report_value "$TAP_REPORT" RO_TAP_OBSERVABILITY_PIN_COUNT)"
STRICT_ATTRIBUTION="$(report_value "$HASH_REPORT" STRICT_ATTRIBUTION)"
HASH_PRESENT=0
[[ -s "$HASH_REPORT" ]] && HASH_PRESENT=1
PREP_DECISION=FAIL_STOP
if [[ "$PREP_RC" -eq 0 && "$PREP_STATUS" == PASS && "$TAP_STATUS" == PASS && \
      "$TAP_COUNT" == 2 && "$STRICT_ATTRIBUTION" == 1 && "$HASH_PRESENT" == 1 ]]; then
  PREP_DECISION=PASS_CONTINUE
fi
PREP_PUBLISH_RC=99
if [[ -d "$PVS_DIR" ]]; then
  mkdir -p "$PVS_DIR/reports" "$PVS_DIR/logs"
  {
    echo "STEP=PVS_PREPARATION"
    echo "PREP_RC=$PREP_RC"
    echo "PVS_PREP_INPUT_STATUS=$PREP_STATUS"
    echo "TAP_PIN_CONTRACT_STATUS=$TAP_STATUS"
    echo "RO_TAP_OBSERVABILITY_PIN_COUNT=$TAP_COUNT"
    echo "STRICT_ATTRIBUTION=$STRICT_ATTRIBUTION"
    echo "HASH_MANIFEST_PRESENT=$HASH_PRESENT"
    echo "DECISION=$PREP_DECISION"
  } | tee "$PVS_DIR/reports/operator_gate_pvs_prepare.rpt"
  publish_stage "${PVS_RUN_ID}_01_prepare" PVS_PREPARATION
  PREP_PUBLISH_RC=$?
fi
if [[ "$PREP_DECISION" != PASS_CONTINUE || "$PREP_PUBLISH_RC" -ne 0 ]]; then
  stop_after_stage PVS_PREPARATION "$PREP_DECISION" "$PREP_PUBLISH_RC"
  exit 1
fi

run_logged "$PVS_DIR/logs/operator_template_audit.log" \
  bash "$AUDIT_SCRIPT" --result-dir "$PVS_DIR" --expected-head "$EXPECTED_HEAD_VALUE"
AUDIT_RC=$?
AUDIT_STATUS="$(report_value "$PVS_DIR/manifests/pvs_template_audit.status" PVS_TEMPLATE_AUDIT_STATUS)"
AUDIT_DECISION=FAIL_STOP
[[ "$AUDIT_RC" -eq 0 && "$AUDIT_STATUS" == PASS ]] && AUDIT_DECISION=PASS_CONTINUE
{
  echo "STEP=PVS_TEMPLATE_AUDIT"
  echo "AUDIT_RC=$AUDIT_RC"
  echo "PVS_TEMPLATE_AUDIT_STATUS=$AUDIT_STATUS"
  echo "DECISION=$AUDIT_DECISION"
} | tee "$PVS_DIR/reports/operator_gate_pvs_template_audit.rpt"
publish_stage "${PVS_RUN_ID}_02_template_audit" PVS_TEMPLATE_AUDIT
AUDIT_PUBLISH_RC=$?
if [[ "$AUDIT_DECISION" != PASS_CONTINUE || "$AUDIT_PUBLISH_RC" -ne 0 ]]; then
  stop_after_stage PVS_TEMPLATE_AUDIT "$AUDIT_DECISION" "$AUDIT_PUBLISH_RC"
  exit 1
fi

run_drc_stage() {
  local variant="$1"
  local upper="$2"
  local snapshot_suffix="$3"
  local report="$PVS_DIR/reports/pvs_drc_${variant}_status.rpt"
  local log="$PVS_DIR/logs/operator_drc_${variant}.log"
  local rc status gate report_variant primary expanded decision publish_rc

  run_logged "$log" bash "$DRC_SCRIPT" --prepared-dir "$PVS_DIR" \
    --variant "$variant" --expected-head "$EXPECTED_HEAD_VALUE"
  rc=$?
  status="$(report_value "$report" STATUS)"
  gate="$(report_value "$report" PVS_DRC_STATUS)"
  report_variant="$(report_value "$report" PVS_DRC_VARIANT)"
  primary="$(report_value "$report" DRC_TOTAL_PRIMARY)"
  expanded="$(report_value "$report" DRC_TOTAL_EXPANDED)"
  decision=FAIL_STOP
  if [[ "$rc" -eq 0 && "$status" == PASS && "$gate" == PASS && \
        "$report_variant" == "$upper" && "$primary" == 0 && "$expanded" == 0 ]]; then
    decision=PASS_CONTINUE
  fi
  {
    echo "STEP=PVS_DRC_$upper"
    echo "DRC_${upper}_RC=$rc"
    echo "STATUS=$status"
    echo "PVS_DRC_STATUS=$gate"
    echo "PVS_DRC_VARIANT=$report_variant"
    echo "DRC_TOTAL_PRIMARY=$primary"
    echo "DRC_TOTAL_EXPANDED=$expanded"
    echo "DECISION=$decision"
  } | tee "$PVS_DIR/reports/operator_gate_pvs_drc_${variant}.rpt"
  publish_stage "${PVS_RUN_ID}_${snapshot_suffix}" "PVS_DRC_$upper"
  publish_rc=$?
  LAST_DRC_DECISION="$decision"
  LAST_DRC_PUBLISH_RC="$publish_rc"
  LAST_DRC_RC="$rc"
  [[ "$decision" == PASS_CONTINUE && "$publish_rc" -eq 0 ]]
}

run_drc_stage base BASE 03_drc_base
BASE_CHAIN_RC=$?
if [[ "$BASE_CHAIN_RC" -ne 0 ]]; then
  stop_after_stage PVS_DRC_BASE "$LAST_DRC_DECISION" "$LAST_DRC_PUBLISH_RC"
  exit 1
fi

run_drc_stage density DENSITY 04_drc_density
DENSITY_CHAIN_RC=$?
if [[ "$DENSITY_CHAIN_RC" -ne 0 ]]; then
  stop_after_stage PVS_DRC_DENSITY "$LAST_DRC_DECISION" "$LAST_DRC_PUBLISH_RC"
  exit 1
fi

run_logged "$PVS_DIR/logs/operator_lvs.log" \
  bash "$LVS_SCRIPT" --prepared-dir "$PVS_DIR" --expected-head "$EXPECTED_HEAD_VALUE"
LVS_RC=$?
LVS_REPORT="$PVS_DIR/reports/pvs_lvs_status.rpt"
LVS_STATUS="$(report_value "$LVS_REPORT" STATUS)"
LVS_GATE="$(report_value "$LVS_REPORT" PVS_LVS_STATUS)"
LVS_TOOL_RC="$(report_value "$LVS_REPORT" PVS_RC)"
LVS_DECISION=FAIL_STOP
if [[ "$LVS_RC" -eq 0 && "$LVS_STATUS" == PASS && "$LVS_GATE" == MATCH && "$LVS_TOOL_RC" == 0 ]]; then
  LVS_DECISION=PASS_CONTINUE
fi
{
  echo "STEP=PVS_LVS"
  echo "LVS_RC=$LVS_RC"
  echo "STATUS=$LVS_STATUS"
  echo "PVS_LVS_STATUS=$LVS_GATE"
  echo "PVS_RC=$LVS_TOOL_RC"
  echo "DECISION=$LVS_DECISION"
} | tee "$PVS_DIR/reports/operator_gate_pvs_lvs.rpt"
publish_stage "${PVS_RUN_ID}_05_lvs" PVS_LVS
LVS_PUBLISH_RC=$?
if [[ "$LVS_DECISION" != PASS_CONTINUE || "$LVS_PUBLISH_RC" -ne 0 ]]; then
  stop_after_stage PVS_LVS "$LVS_DECISION" "$LVS_PUBLISH_RC"
  exit 1
fi

echo "PVS_RECOVERY_STATUS=PASS"
echo "PVS_RUN_ID=$PVS_RUN_ID"
echo "PVS_PREPARATION=PASS"
echo "PVS_TEMPLATE_AUDIT=PASS"
echo "PVS_DRC_BASE=PASS"
echo "PVS_DRC_DENSITY=PASS"
echo "PVS_LVS=MATCH"
echo "MPTDC_TC_PVS_CLOSED=YES"
echo "FINAL_DECISION=MPTDC_TC_PVS_CLOSED_NOT_MMMC_SIGNOFF"
echo "NOT_MMMC_SIGNOFF=YES"
echo "FINAL_SIGNOFF=NO"
echo "READY_FOR_TAPEOUT=NO"
echo "DECISION=PASS_CONTINUE"
echo "PUBLISH_RC=$LVS_PUBLISH_RC"
echo "NEXT_EXPECTED_HEAD=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null)"
echo "NEXT_STAGE=TC_BLOCK_COMPLETE_REVIEW_MMMC_SCOPE"
