#!/usr/bin/env bash
# shellcheck shell=bash
#
# Canonical Genus policy for the MPTDC product-axis typical closure baseline.
# Source this file through run_genus_axis_core_typical_closed.sh. Edit only the
# purpose-named values below, then run the profile checker and a named Genus
# comparison. The legacy variables later in this file are an internal adapter
# for the existing O13/ABS/REPAIR backend and are not a command-line interface.
#
# Reference: fa66cc4d36936e2bf0d41e6b24f2f9486569e242,
# 20260618_111124_axis_core_genus_timing_close_on22x1_final_guarded.
# Result: WNS +0.3 ps, TNS -0.0 ps, zero setup violations, zero DRVs.
# Boundary: typical-only Genus closure; not MMMC or final signoff.

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "ERROR: source this profile from the canonical Genus wrapper." >&2
  exit 2
fi

# -----------------------------------------------------------------------------
# Validated policy. These are the handoff-owned values.
# -----------------------------------------------------------------------------
MPTDC_GENUS_BASELINE_PROFILE_ID="axis_core_typical_closed_on22_x1"
MPTDC_GENUS_BASELINE_SOURCE_COMMIT="fa66cc4d36936e2bf0d41e6b24f2f9486569e242"
MPTDC_GENUS_BASELINE_SOURCE_RUN="20260618_111124_axis_core_genus_timing_close_on22x1_final_guarded"

# Timing-first Genus optimization. Area/power recovery remains deferred until
# physical feasibility proves that the small positive margin survives.
MPTDC_GENUS_BASELINE_OPTIMIZATION_POLICY="timing_ultra"

# STRIDE2 selects safe teardown, empty-row skip, and two-column drain scanning.
# It changes synthesized drain latency/logic, so it is part of the baseline.
MPTDC_GENUS_BASELINE_DRAIN_RTL_POLICY="STRIDE2"

# Exact fast-tag policy. The full 1.333 ns budget is the proven safe value.
# Source-flop remapping is off because DFRRQJIHDX4 increased C-to-Q delay and
# harmed FAST_TAG_TO_PD_TS / LOCAL_FAST_TAG_SELF. The inactive target cells are
# retained only to make a copied experimental profile reproducible.
MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_CELL_REMAP_ENABLED=0
MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_REMAP_MODE="POLARITY_AWARE"
MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_RESET0_TARGET_CELL="DFRRQJIHDX4"
MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_SET1_TARGET_CELL="DFRSJIHDX2"
MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_REMAP_SKIP_UNSUPPORTED=1
MPTDC_GENUS_BASELINE_FAST_TAG_C_TO_D_BUDGET_NS="1.333"
MPTDC_GENUS_BASELINE_ALLOW_TIGHTER_FAST_TAG_BUDGET=0
MPTDC_GENUS_BASELINE_FAST_TAG_TAPS="0 1 2 3 4 5 6 7"
MPTDC_GENUS_BASELINE_FAST_TAG_BITS="0 5 6"
MPTDC_GENUS_BASELINE_FAST_TAG_MAX_FANOUT=2
MPTDC_GENUS_BASELINE_FAST_TAG_MAX_TRANSITION_NS="0.50"

# Broad PD hit-to-nfast timing pressure is off. The earlier broad max-delay and
# max-transition experiment contaminated optimization. Counts remain pinned for
# audit output even though that repair is disabled.
MPTDC_GENUS_BASELINE_BROAD_PD_HIT_TO_NFAST_REPAIR_ENABLED=0
MPTDC_GENUS_BASELINE_BROAD_PD_MAX_DELAY_NS=0
MPTDC_GENUS_BASELINE_BROAD_PD_MAX_TRANSITION_NS=0
MPTDC_GENUS_BASELINE_PD_DATA_BITS="0 1 2 3 4 5 6"
MPTDC_GENUS_BASELINE_PD_SOURCE_COUNT=64
MPTDC_GENUS_BASELINE_PD_ENDPOINT_COUNT=448

# Scoped local repair. Timing-report points contain the mapped instance in the
# first token (instance/output_pin). X2 is kept in the requested list to exercise
# the guard, but is blocked after its -80.6 ps LOCAL_FAST_TAG_SELF regression.
MPTDC_GENUS_BASELINE_PD_LOCAL_ON22_REPAIR_ENABLED=1
MPTDC_GENUS_BASELINE_PD_LOCAL_SOURCE_CELL="ON22JIHDX0"
MPTDC_GENUS_BASELINE_PD_LOCAL_CANDIDATE_TARGETS="ON22JIHDX1 ON22JIHDX2"
MPTDC_GENUS_BASELINE_PD_LOCAL_ALLOW_X2=0
MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_EFFECTIVE_TARGET="ON22JIHDX1"
MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_ENDPOINTS=448
MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_DRIVERS="AUTO"
MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_CELLS="AUTO"
MPTDC_GENUS_BASELINE_PD_LOCAL_DISCOVERY_METHOD="TIMING_REPORT"
MPTDC_GENUS_BASELINE_PD_LOCAL_TIMING_PATH_LIMIT=1000
MPTDC_GENUS_BASELINE_PD_LOCAL_APPLY_RESIZE=1

# Fail closed when an old experiment environment would alter policy. Work roots,
# PDK/library paths, and stable run labels are intentionally not rejected.
mptdc_genus_axis_core_typical_closed_reject_external_policy() {
  local name
  while IFS= read -r name; do
    case "$name" in
      MPTDC_O13_*|O13_*|MPTDC_OPT_MODE|MPTDC_STDCELL_FAMILY|\
      MPTDC_GENUS_CLOSURE_PROFILE|MPTDC_GENUS_AREA_RECOVERY|\
      MPTDC_GENUS_POWER_OPT|MPTDC_DESIGN_POWER_EFFORT|\
      MPTDC_GENUS_REPAIR*|MPTDC_FAST_TAG_REPAIR*|\
      MPTDC_PD_HIT_TO_NFAST*|MPTDC_PD_LOCAL_ON22*|\
      MPTDC_ALLOW_TIGHT_FAST_TAG_MAX_DELAY)
        echo "ERROR: $name is internal policy for the canonical closure flow." >&2
        echo "Edit the profile and revalidate instead of overriding the shell environment." >&2
        return 2
        ;;
    esac
  done < <(compgen -e)
}

mptdc_genus_axis_core_typical_closed_apply() {
  [[ $# -eq 1 ]] || {
    echo "ERROR: profile apply requires SYN_DIR." >&2
    return 2
  }

  local syn_dir="$1"
  local stable_filelist="$syn_dir/filelist_axis_core_typical_closed.f"
  local stable_sdc="$syn_dir/inputs/mptdc_axis_core_typical_closed.sdc"
  [[ -f "$stable_filelist" ]] || {
    echo "ERROR: missing canonical Genus filelist: $stable_filelist" >&2
    return 2
  }
  [[ -f "$stable_sdc" ]] || {
    echo "ERROR: missing canonical Genus SDC: $stable_sdc" >&2
    return 2
  }

  mptdc_genus_axis_core_typical_closed_reject_external_policy

  # Stable run identity and historical backend selection.
  export FINAL_SIGNOFF="NO"
  export MPTDC_STABLE_FLOW_LABEL="MPTDC_GENUS_AXIS_CORE_TYPICAL_CLOSED"
  export MPTDC_STABLE_CLOSURE_LABEL="MPTDC_TYPICAL_CLOSED_ON22_X1"
  export MPTDC_FINAL_PACKAGE_LABEL="TYPICAL_ONLY_INNOVUS_FEASIBILITY_INPUT"
  export MPTDC_SIGNOFF_BOUNDARY="TYPICAL_ONLY_NOT_MMMC"
  export MPTDC_O13_DEFAULT_MODE="O13_ABS5_PD_Q1_EXCEPTION_EXACT_MATCH"
  export MPTDC_O13_MODE="$MPTDC_O13_DEFAULT_MODE"
  export MPTDC_O13_VALIDATE_ONLY=0
  export MPTDC_O13_ABS3_CLOCK_CDC_REPAIR=1
  export MPTDC_O13_ABS4_PD_VERNIER_CLASSIFICATION=0
  export MPTDC_O13_ABS5_PD_Q1_EXCEPTION_EXACT=1
  export O13_FILELIST_PATH="$stable_filelist"
  export O13_SDC_PATH="$stable_sdc"

  # Timing-first/JIHD repair8 baseline, pinned against future backend defaults.
  export MPTDC_OPT_MODE="$MPTDC_GENUS_BASELINE_DRAIN_RTL_POLICY"
  export MPTDC_STDCELL_FAMILY="JIHD"
  export MPTDC_GENUS_CLOSURE_PROFILE="$MPTDC_GENUS_BASELINE_OPTIMIZATION_POLICY"
  export O13_GENUS_EFFORT="closure"
  export MPTDC_GENUS_AREA_RECOVERY=0
  export MPTDC_GENUS_POWER_OPT=0
  export O13_ENABLE_CLOCK_GATING=0
  export MPTDC_DESIGN_POWER_EFFORT="none"
  export MPTDC_GENUS_REPAIR_FAST_TAG_PD=1
  export MPTDC_GENUS_REPAIR_DRV_TRANSITION=0
  export MPTDC_GENUS_REPAIR4_EXACT_FAST_TAG_SOURCE_DRIVE=1
  export MPTDC_GENUS_REPAIR5_EXACT_FAST_TAG_CLOSE=1
  export MPTDC_GENUS_REPAIR6_LOCALTAG_PRESERVE_CLOSE=0
  export MPTDC_GENUS_REPAIR7_POLARITY_AWARE_FAST_TAG_SOURCE_UPGRADE=0
  export MPTDC_GENUS_REPAIR8_JIHD_EXACT_FAST_TAG_CLOSE=1
  export MPTDC_GENUS_REPAIR_STRONG_FAST_TAG_FLOPS=0
  export MPTDC_GENUS_REPAIR_STRONG_CONTROL_DRV=0
  export MPTDC_GENUS_REPAIR_CONTROL_CELL_BIAS_STAGE="none"
  export MPTDC_GENUS_REPAIR_CONTROL_AVOID_INHDX8=0
  export MPTDC_GENUS_REPAIR_EXACT_CONTROL_ROOTS=0
  export MPTDC_GENUS_REPAIR_APPLY_BROAD_CONTROL_NETS=0
  export MPTDC_GENUS_REPAIR_APPLY_DESIGN_DRV=0
  export MPTDC_GENUS_RELAX_FAST_TAG_PRESERVE=0
  export MPTDC_GENUS_REPAIR_ENDPOINT_TRANSITION_TIGHT=0

  # Exact fast-tag constraints and source-remap guard.
  export MPTDC_FAST_TAG_REPAIR_APPLY_Q_CONSTRAINTS=0
  export MPTDC_FAST_TAG_REPAIR_EXACT_DATA_PATHS=1
  export MPTDC_FAST_TAG_REPAIR_EXACT_TAPS="$MPTDC_GENUS_BASELINE_FAST_TAG_TAPS"
  export MPTDC_FAST_TAG_REPAIR_EXACT_BITS="$MPTDC_GENUS_BASELINE_FAST_TAG_BITS"
  export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_FANOUT="$MPTDC_GENUS_BASELINE_FAST_TAG_MAX_FANOUT"
  export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_TRANSITION_NS="$MPTDC_GENUS_BASELINE_FAST_TAG_MAX_TRANSITION_NS"
  export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_DELAY_REQUESTED_NS="$MPTDC_GENUS_BASELINE_FAST_TAG_C_TO_D_BUDGET_NS"
  export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_DELAY_NS="$MPTDC_GENUS_BASELINE_FAST_TAG_C_TO_D_BUDGET_NS"
  export MPTDC_FAST_TAG_REPAIR_ENABLE_EXACT_MAX_DELAY=1
  export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_DELAY_ENABLE=1
  export MPTDC_ALLOW_TIGHT_FAST_TAG_MAX_DELAY="$MPTDC_GENUS_BASELINE_ALLOW_TIGHTER_FAST_TAG_BUDGET"
  case "$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_CELL_REMAP_ENABLED" in
    0)
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_CELL_DISABLE=1
      unset MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_CELL_MODE
      unset MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_CELL
      unset MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_RESET0_CELL
      unset MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_SET1_CELL
      unset MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_SKIP_UNSUPPORTED
      ;;
    1)
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_CELL_DISABLE=0
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_CELL_MODE="$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_REMAP_MODE"
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_CELL="$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_REMAP_MODE"
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_RESET0_CELL="$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_RESET0_TARGET_CELL"
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_SET1_CELL="$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_SET1_TARGET_CELL"
      export MPTDC_FAST_TAG_REPAIR_EXACT_SOURCE_SKIP_UNSUPPORTED="$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_REMAP_SKIP_UNSUPPORTED"
      ;;
    *)
      echo "ERROR: FAST_TAG_SOURCE_CELL_REMAP_ENABLED must be 0 or 1." >&2
      return 2
      ;;
  esac

  # Broad PD repair remains off; scoped timing-report ON22 repair remains on.
  export MPTDC_GENUS_REPAIR_PD_HIT_TO_NFAST_LOCAL="$MPTDC_GENUS_BASELINE_BROAD_PD_HIT_TO_NFAST_REPAIR_ENABLED"
  export MPTDC_PD_HIT_TO_NFAST_MAX_DELAY_NS="$MPTDC_GENUS_BASELINE_BROAD_PD_MAX_DELAY_NS"
  export MPTDC_PD_HIT_TO_NFAST_MAX_TRANSITION_NS="$MPTDC_GENUS_BASELINE_BROAD_PD_MAX_TRANSITION_NS"
  export MPTDC_PD_HIT_TO_NFAST_BITS="$MPTDC_GENUS_BASELINE_PD_DATA_BITS"
  export MPTDC_PD_HIT_TO_NFAST_EXPECTED_SOURCES="$MPTDC_GENUS_BASELINE_PD_SOURCE_COUNT"
  export MPTDC_PD_HIT_TO_NFAST_EXPECTED_ENDPOINTS="$MPTDC_GENUS_BASELINE_PD_ENDPOINT_COUNT"
  export MPTDC_GENUS_REPAIR_PD_LOCAL_ON22="$MPTDC_GENUS_BASELINE_PD_LOCAL_ON22_REPAIR_ENABLED"
  export MPTDC_PD_LOCAL_ON22_SOURCE_CELL="$MPTDC_GENUS_BASELINE_PD_LOCAL_SOURCE_CELL"
  export MPTDC_PD_LOCAL_ON22_TARGET_CELLS="$MPTDC_GENUS_BASELINE_PD_LOCAL_CANDIDATE_TARGETS"
  export MPTDC_PD_LOCAL_ON22_BITS="$MPTDC_GENUS_BASELINE_PD_DATA_BITS"
  export MPTDC_PD_LOCAL_ON22_EXPECTED_ENDPOINTS="$MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_ENDPOINTS"
  export MPTDC_PD_LOCAL_ON22_EXPECTED_DRIVERS="$MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_DRIVERS"
  export MPTDC_PD_LOCAL_ON22_EXPECTED_CELLS="$MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_CELLS"
  export MPTDC_PD_LOCAL_ON22_DISCOVERY_MODE="$MPTDC_GENUS_BASELINE_PD_LOCAL_DISCOVERY_METHOD"
  export MPTDC_PD_LOCAL_ON22_TIMING_MAX_PATHS="$MPTDC_GENUS_BASELINE_PD_LOCAL_TIMING_PATH_LIMIT"
  export MPTDC_PD_LOCAL_ON22_APPLY_REPAIR="$MPTDC_GENUS_BASELINE_PD_LOCAL_APPLY_RESIZE"
  export MPTDC_PD_LOCAL_ON22_ALLOW_X2="$MPTDC_GENUS_BASELINE_PD_LOCAL_ALLOW_X2"
}

mptdc_genus_axis_core_typical_closed_print() {
  cat <<EOF_MANIFEST
PROFILE_ID=$MPTDC_GENUS_BASELINE_PROFILE_ID
PROFILE_BASELINE_COMMIT=$MPTDC_GENUS_BASELINE_SOURCE_COMMIT
PROFILE_BASELINE_RUN=$MPTDC_GENUS_BASELINE_SOURCE_RUN
PROFILE_SIGNOFF_BOUNDARY=$MPTDC_SIGNOFF_BOUNDARY
PROFILE_FILELIST=$O13_FILELIST_PATH
PROFILE_SDC=$O13_SDC_PATH
PROFILE_OPTIMIZATION_POLICY=$MPTDC_GENUS_CLOSURE_PROFILE
PROFILE_DRAIN_RTL_POLICY=$MPTDC_OPT_MODE
PROFILE_STDCELL_FAMILY=$MPTDC_STDCELL_FAMILY
PROFILE_FAST_TAG_SOURCE_CELL_REMAP_ENABLED=$MPTDC_GENUS_BASELINE_FAST_TAG_SOURCE_CELL_REMAP_ENABLED
PROFILE_FAST_TAG_C_TO_D_BUDGET_NS=$MPTDC_FAST_TAG_REPAIR_EXACT_MAX_DELAY_NS
PROFILE_FAST_TAG_ALLOW_TIGHTER_BUDGET=$MPTDC_ALLOW_TIGHT_FAST_TAG_MAX_DELAY
PROFILE_BROAD_PD_HIT_TO_NFAST_REPAIR_ENABLED=$MPTDC_GENUS_REPAIR_PD_HIT_TO_NFAST_LOCAL
PROFILE_BROAD_PD_MAX_DELAY_NS=$MPTDC_PD_HIT_TO_NFAST_MAX_DELAY_NS
PROFILE_BROAD_PD_MAX_TRANSITION_NS=$MPTDC_PD_HIT_TO_NFAST_MAX_TRANSITION_NS
PROFILE_PD_LOCAL_ON22_REPAIR_ENABLED=$MPTDC_GENUS_REPAIR_PD_LOCAL_ON22
PROFILE_PD_LOCAL_SOURCE_CELL=$MPTDC_PD_LOCAL_ON22_SOURCE_CELL
PROFILE_PD_LOCAL_REQUESTED_TARGETS=$MPTDC_PD_LOCAL_ON22_TARGET_CELLS
PROFILE_PD_LOCAL_ALLOW_X2=$MPTDC_PD_LOCAL_ON22_ALLOW_X2
PROFILE_PD_LOCAL_EXPECTED_EFFECTIVE_TARGET=$MPTDC_GENUS_BASELINE_PD_LOCAL_EXPECTED_EFFECTIVE_TARGET
PROFILE_PD_LOCAL_EXPECTED_ENDPOINTS=$MPTDC_PD_LOCAL_ON22_EXPECTED_ENDPOINTS
PROFILE_PD_LOCAL_EXPECTED_DRIVERS=$MPTDC_PD_LOCAL_ON22_EXPECTED_DRIVERS
PROFILE_PD_LOCAL_EXPECTED_CELLS=$MPTDC_PD_LOCAL_ON22_EXPECTED_CELLS
PROFILE_PD_LOCAL_DISCOVERY_METHOD=$MPTDC_PD_LOCAL_ON22_DISCOVERY_MODE
PROFILE_PD_LOCAL_TIMING_PATH_LIMIT=$MPTDC_PD_LOCAL_ON22_TIMING_MAX_PATHS
PROFILE_PD_LOCAL_APPLY_RESIZE=$MPTDC_PD_LOCAL_ON22_APPLY_REPAIR
EOF_MANIFEST
}
