# =============================================================================
# Project  : SPAD_MPTDC — Vernier Time-to-Digital Converter
# File     : mptdc.sdc
# Purpose  : Synopsys Design Constraints for Cadence Genus synthesis
# Author   : Karim Sabra
# =============================================================================
# Target   : XFAB XH018 (180 nm)
# Clocks   : clk_sys 160 MHz, osc_slow ~1 GHz, osc_fast ~1.11 GHz
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# 1. PRIMARY CLOCK DEFINITION
# ─────────────────────────────────────────────────────────────────────────────
# System clock: 160 MHz, 6.25 ns period, 50% duty cycle
create_clock -name clk_sys -period 6.25 [get_ports clk_sys]

# Clock uncertainty (jitter + skew budget for 180 nm)
set_clock_uncertainty 0.3 [get_clocks clk_sys]

# Clock transition constraint
set_clock_transition 0.15 [get_clocks clk_sys]

# ─────────────────────────────────────────────────────────────────────────────
# 2. OSCILLATOR CLOCKS (VIRTUAL — generated by analog macro, not synthesized)
# ─────────────────────────────────────────────────────────────────────────────
# These clocks exist in the real design but come from analog oscillator macros.
# For synthesis, the oscillator stubs provide static outputs, so we define
# virtual clocks to enable timing analysis of the oscillator-domain logic.
#
# osc_slow: ~1.0 GHz (1.0 ns period, 9 taps × ~111 ps)
# osc_fast: ~1.11 GHz (0.9 ns period, 9 taps × ~100 ps)

create_clock -name clk_osc_slow -period 1.0 \
    [get_pins u_core/u_osc_slow/u_stub/phase[0]] -add

create_clock -name clk_osc_fast -period 0.9 \
    [get_pins u_core/u_osc_fast/u_stub/phase[0]] -add

# Higher uncertainty for oscillator clocks (analog jitter + process variation)
set_clock_uncertainty 0.05 [get_clocks clk_osc_slow]
set_clock_uncertainty 0.05 [get_clocks clk_osc_fast]

# ─────────────────────────────────────────────────────────────────────────────
# 3. CLOCK DOMAIN CROSSING CONSTRAINTS
# ─────────────────────────────────────────────────────────────────────────────
# All three clocks are asynchronous to each other.
# CDC is handled by structural synchronizers (gray_cnt_sync, pulse_sync).

set_clock_groups -asynchronous \
    -group [get_clocks clk_sys] \
    -group [get_clocks clk_osc_slow] \
    -group [get_clocks clk_osc_fast]

# ─────────────────────────────────────────────────────────────────────────────
# 4. ASYNCHRONOUS INPUT CONSTRAINTS (START / STOP)
# ─────────────────────────────────────────────────────────────────────────────
# START and STOP are truly asynchronous pulses from SPAD detectors or
# calibration injection. They have no timing relationship to any clock.
# The async_frontend uses SR latches to capture them — no setup/hold.

set_false_path -from [get_ports start_spad_async_i]
set_false_path -from [get_ports stop_spad_async_i]
set_false_path -from [get_ports cal_start_async_i]
set_false_path -from [get_ports cal_stop_async_i]

# ─────────────────────────────────────────────────────────────────────────────
# 5. ASYNCHRONOUS RESET
# ─────────────────────────────────────────────────────────────────────────────
# async_rst_n is an asynchronous active-low reset. It asserts immediately
# (gate delay) and deasserts through reset synchronizers in each domain.

set_false_path -from [get_ports async_rst_n]

# ─────────────────────────────────────────────────────────────────────────────
# 6. CDC SYNCHRONIZER DONT_TOUCH
# ─────────────────────────────────────────────────────────────────────────────
# Protect 2-FF synchronizer chains from optimization. The tool must not
# merge, replicate, or retime these flops — they are metastability barriers.

# Reset synchronizers (3 instances: sys, fast, slow domains)
set_dont_touch [get_cells -hierarchical *u_rst_sync*/sync_q_reg*] true

# Gray-code counter synchronizers
set_dont_touch [get_cells -hierarchical *gray_cont_ff1*] true
set_dont_touch [get_cells -hierarchical *gray_cont_ff2*] true
set_dont_touch [get_cells -hierarchical *gray_snap_ff1*] true
set_dont_touch [get_cells -hierarchical *gray_snap_ff2*] true

# Pulse synchronizer chains
set_dont_touch [get_cells -hierarchical *u_pulse_sync*/sync_ff1*] true
set_dont_touch [get_cells -hierarchical *u_pulse_sync*/sync_ff2*] true

# Context drain synchronizer flops (in mptdc_core)
set_dont_touch [get_cells -hierarchical *ctx_drain_sync_ff*] true

# ─────────────────────────────────────────────────────────────────────────────
# 7. CDC MAX DELAY CONSTRAINTS
# ─────────────────────────────────────────────────────────────────────────────
# For CDC paths through synchronizers, constrain the combinational delay
# between the source flop and the first synchronizer flop to be less than
# one destination clock period. This ensures the synchronizer resolves
# metastability within the expected time.

# Gray-code CDC: osc_domain → sys_clk (max 1 sys period = 6.25 ns)
set_max_delay 6.25 -from [get_clocks clk_osc_slow] \
                    -to   [get_clocks clk_sys] \
                    -datapath_only

set_max_delay 6.25 -from [get_clocks clk_osc_fast] \
                    -to   [get_clocks clk_sys] \
                    -datapath_only

# Pulse sync: sys → osc_fast (max 1 fast period = 0.9 ns)
set_max_delay 0.9  -from [get_clocks clk_sys] \
                    -to   [get_clocks clk_osc_fast] \
                    -datapath_only

# ─────────────────────────────────────────────────────────────────────────────
# 8. INPUT DELAY CONSTRAINTS (CSR BUS)
# ─────────────────────────────────────────────────────────────────────────────
# CSR bus is synchronous to clk_sys. Assume external logic provides data
# with ~2 ns setup margin (conservative for 180 nm).

set_input_delay  2.0 -clock clk_sys [get_ports {csr_valid_i csr_write_i}]
set_input_delay  2.0 -clock clk_sys [get_ports {csr_addr_i[*]}]
set_input_delay  2.0 -clock clk_sys [get_ports {csr_wdata_i[*]}]

# Narrow output consumer ready signal
set_input_delay  2.0 -clock clk_sys [get_ports narrow_ready_i]

# ─────────────────────────────────────────────────────────────────────────────
# 9. OUTPUT DELAY CONSTRAINTS
# ─────────────────────────────────────────────────────────────────────────────
# CSR read outputs and narrow data output. Allow ~2 ns for external routing.

set_output_delay 2.0 -clock clk_sys [get_ports {csr_ready_o csr_rvalid_o}]
set_output_delay 2.0 -clock clk_sys [get_ports {csr_rdata_o[*]}]
set_output_delay 2.0 -clock clk_sys [get_ports {narrow_valid_o}]
set_output_delay 2.0 -clock clk_sys [get_ports {narrow_data_o[*]}]

# ─────────────────────────────────────────────────────────────────────────────
# 10. DRIVING CELL AND LOAD
# ─────────────────────────────────────────────────────────────────────────────
# Use generic values for trial synthesis. Replace with actual XFAB pad
# cell characteristics for final synthesis.

# Conservative: 50 fF output load on all outputs
set_load 0.05 [all_outputs]

# Conservative: 0.1 ns input transition
set_input_transition 0.1 [all_inputs]

# ─────────────────────────────────────────────────────────────────────────────
# 11. DESIGN RULE CONSTRAINTS
# ─────────────────────────────────────────────────────────────────────────────
# Maximum fanout — prevent long combinational chains
set_max_fanout 20 [current_design]

# Maximum transition — prevent slow edges (noise/power)
set_max_transition 0.5 [current_design]

# ─────────────────────────────────────────────────────────────────────────────
# 12. OPERATING CONDITIONS
# ─────────────────────────────────────────────────────────────────────────────
# Typical corner for trial synthesis. For signoff, run all PVT corners.
# Uncomment and set to your XFAB library's operating condition name:
# set_operating_conditions -library <xfab_lib> <typical_condition>
