# AUTO-GENERATED by TOP/scripts/generate_csr_map.py.
# Source: TOP/rtl/spadmic_csr_map_pkg.sv
# Do not edit this file directly.
from dataclasses import dataclass

I2C_ADDRESS = 0x42
CSR_ABI_VERSION = 0x00010000

@dataclass(frozen=True)
class Register:
    address: int
    access: str
    reset: int
    page: str
    description: str

@dataclass(frozen=True)
class Field:
    lsb: int
    width: int
    access: str
    reset: int
    description: str

    @property
    def mask(self) -> int:
        return ((1 << self.width) - 1) << self.lsb

    def prep(self, value: int) -> int:
        if value < 0 or value >= (1 << self.width):
            raise ValueError(f'value {value} does not fit in {self.width} bits')
        return (value << self.lsb) & self.mask

    def get(self, register_value: int) -> int:
        return (register_value & self.mask) >> self.lsb

REGISTERS = {
    'CHIP_ID': Register(0x0000, 'RO', 0x53504D54, 'System', 'SPADMIC matrix-top identity'),
    'ABI_VERSION': Register(0x0004, 'RO', 0x00010000, 'System', 'CSR ABI major and minor version'),
    'GLOBAL_CTRL': Register(0x0008, 'RW', 0x000000F0, 'System', 'Atomic enable mode normal-axis-mask and auto-reset control'),
    'GLOBAL_STATUS': Register(0x000C, 'RO', 0x00000000, 'System', 'Active mode axis and global idle status'),
    'GLOBAL_FAULT': Register(0x0010, 'RO', 0x00000000, 'System', 'OR summary of sticky page faults'),
    'MAINT_CMD': Register(0x0014, 'WO', 0x00000000, 'System', 'Disabled-idle maintenance commands'),
    'TDC_SHARED_CFG': Register(0x0018, 'RW', 0x0000000F, 'System', 'Shared max-hits and RO tuning codes'),
    'TDC_SHARED_CMD': Register(0x001C, 'WO', 0x00000000, 'System', 'Shared soft-reset and FIFO-clear pulses'),
    'CALIB_AXIS_MASK': Register(0x0020, 'RW', 0x00000007, 'System', 'Nonzero calibration-only axis mask'),
    'ACCESS_STATUS': Register(0x0024, 'RO', 0x00000000, 'System', 'Last access validity and operation summary'),
    'ACCESS_FAULT': Register(0x0028, 'W1C', 0x00000000, 'System', 'Sticky access-protocol fault bits'),
    'ACCESS_LAST_INFO': Register(0x002C, 'RO', 0x00000000, 'System', 'Last failing address cause and operation'),
    'ACCESS_LAST_WDATA': Register(0x0030, 'RO', 0x00000000, 'System', 'Last failing write payload'),
    'ACCESS_ERROR_COUNT': Register(0x0034, 'RO', 0x00000000, 'System', 'Saturating invalid-access counter'),
    'TDC_R_STATUS': Register(0x1000, 'RO', 0x00000000, 'TDC R', 'R-axis readiness activity and FIFO status'),
    'TDC_R_FAULT': Register(0x1004, 'W1C', 0x00000000, 'TDC R', 'R-axis sticky FIFO-full fault'),
    'TDC_R_ERROR_COUNT': Register(0x1008, 'RO', 0x00000000, 'TDC R', 'R-axis saturating FIFO-full counter'),
    'TDC_Y_STATUS': Register(0x2000, 'RO', 0x00000000, 'TDC Y', 'Y-axis readiness activity and FIFO status'),
    'TDC_Y_FAULT': Register(0x2004, 'W1C', 0x00000000, 'TDC Y', 'Y-axis sticky FIFO-full fault'),
    'TDC_Y_ERROR_COUNT': Register(0x2008, 'RO', 0x00000000, 'TDC Y', 'Y-axis saturating FIFO-full counter'),
    'TDC_B_STATUS': Register(0x3000, 'RO', 0x00000000, 'TDC B', 'B-axis readiness activity and FIFO status'),
    'TDC_B_FAULT': Register(0x3004, 'W1C', 0x00000000, 'TDC B', 'B-axis sticky FIFO-full fault'),
    'TDC_B_ERROR_COUNT': Register(0x3008, 'RO', 0x00000000, 'TDC B', 'B-axis saturating FIFO-full counter'),
    'POSITION_CFG': Register(0x4000, 'RW', 0x00000104, 'Position', 'Cluster/raw mode gap and minimum-span controls'),
    'POSITION_STATUS': Register(0x4004, 'RO', 0x00000000, 'Position', 'Packet pending busy and snapshot-captured status'),
    'POSITION_FAULT': Register(0x4008, 'W1C', 0x00000000, 'Position', 'Sticky packet-drop fault'),
    'POSITION_DROP_COUNT': Register(0x400C, 'RO', 0x00000000, 'Position', 'Saturating packet-drop counter'),
    'EVENT_STATUS': Register(0x5000, 'RO', 0x00000000, 'Event', 'Event identifier and lifecycle status'),
    'EVENT_MASK_STATUS': Register(0x5004, 'RO', 0x00000000, 'Event', 'Required completed and reset-ack masks'),
    'SNAPSHOT_CFG': Register(0x5008, 'RW', 0x00400002, 'Event', 'Snapshot settle and watchdog cycles'),
    'RESET_CFG': Register(0x500C, 'RW', 0x00000000, 'Event', 'Automatic matrix-reset pulse width'),
    'SNAPSHOT_RESET_STATUS': Register(0x5010, 'RO', 0x00000000, 'Event', 'Snapshot and reset controller status'),
    'EVENT_FAULT': Register(0x5014, 'W1C', 0x00000000, 'Event', 'Sticky reject timeout overlap and disabled-reset faults'),
    'EVENT_REJECT_COUNT': Register(0x5018, 'RO', 0x00000000, 'Event', 'Saturating event-not-ready reject counter'),
    'SNAPSHOT_TIMEOUT_COUNT': Register(0x501C, 'RO', 0x00000000, 'Event', 'Saturating snapshot-timeout counter'),
    'SNAPSHOT_OVERLAP_COUNT': Register(0x5020, 'RO', 0x00000000, 'Event', 'Saturating snapshot-overlap counter'),
    'SNAPSHOT_REJECT_COUNT': Register(0x5024, 'RO', 0x00000000, 'Event', 'Saturating snapshot-reject counter'),
    'RESET_DISABLED_COUNT': Register(0x5028, 'RO', 0x00000000, 'Event', 'Saturating disabled-reset counter'),
    'EVENT_CMD': Register(0x502C, 'WO', 0x00000000, 'Event', 'Snapshot clear command pulse'),
    'SNAPSHOT_R_LO': Register(0x5040, 'RO', 0x00000000, 'Event', 'R snapshot bits 31 to 0'),
    'SNAPSHOT_R_HI': Register(0x5044, 'RO', 0x00000000, 'Event', 'R snapshot bits 63 to 32'),
    'SNAPSHOT_Y_LO': Register(0x5048, 'RO', 0x00000000, 'Event', 'Y snapshot bits 31 to 0'),
    'SNAPSHOT_Y_HI': Register(0x504C, 'RO', 0x00000000, 'Event', 'Y snapshot bits 63 to 32'),
    'SNAPSHOT_B_LO': Register(0x5050, 'RO', 0x00000000, 'Event', 'B snapshot bits 31 to 0'),
    'SNAPSHOT_B_HI': Register(0x5054, 'RO', 0x00000000, 'Event', 'B snapshot bits 63 to 32'),
    'MATRIX_CMD': Register(0x6000, 'RW', 0x00000002, 'Matrix', 'Matrix configuration operation and start pulse'),
    'MATRIX_STATUS': Register(0x6004, 'RO', 0x00000000, 'Matrix', 'Matrix configuration and readback status'),
    'MATRIX_COLUMN': Register(0x6008, 'RW', 0x00000000, 'Matrix', 'Matrix column index'),
    'MATRIX_WDATA_LO': Register(0x600C, 'RW', 0x00000000, 'Matrix', 'Matrix command payload bits 31 to 0'),
    'MATRIX_WDATA_HI': Register(0x6010, 'RW', 0x00000000, 'Matrix', 'Matrix command payload bits 63 to 32'),
    'MATRIX_RDATA_LO': Register(0x6014, 'RO', 0x00000000, 'Matrix', 'Matrix readback bits 31 to 0'),
    'MATRIX_RDATA_HI': Register(0x6018, 'RO', 0x00000000, 'Matrix', 'Matrix readback bits 63 to 32'),
    'MATRIX_FAULT': Register(0x601C, 'W1C', 0x00000000, 'Matrix', 'Sticky command-reject and controller-error faults'),
    'MATRIX_REJECT_COUNT': Register(0x6020, 'RO', 0x00000000, 'Matrix', 'Saturating rejected-command counter'),
    'MATRIX_ERROR_COUNT': Register(0x6024, 'RO', 0x00000000, 'Matrix', 'Saturating controller-error counter'),
    'TX_BUNDLE_STATUS': Register(0x7000, 'RO', 0x00000000, 'TX', 'Bundle and output-path status'),
    'TX_FIFO_STATUS': Register(0x7004, 'RO', 0x00000000, 'TX', 'Output FIFO level and flags'),
    'TX_FIFO_GEOMETRY': Register(0x7008, 'RO', 0x01000081, 'TX', 'Fixed FIFO reserve threshold and depth'),
    'TX_DDR_STATUS': Register(0x700C, 'RO', 0x00000000, 'TX', 'DDR pairer status'),
    'TX_FAULT': Register(0x7010, 'W1C', 0x00000000, 'TX', 'Sticky missing-source and FIFO-overflow faults'),
    'TX_MISSING_SOURCE_COUNT': Register(0x7014, 'RO', 0x00000000, 'TX', 'Saturating missing-source counter'),
    'TX_FIFO_OVERFLOW_COUNT': Register(0x7018, 'RO', 0x00000000, 'TX', 'Saturating output-FIFO overflow counter'),
    'PLL_CTRL': Register(0x8000, 'RW', 0x00004000, 'PLL', 'PLL and clock-source controls'),
    'PLL_STATUS': Register(0x8004, 'RO', 0x00000000, 'PLL', 'PLL lock and active clock controls'),
    'PLL_FAULT': Register(0x8008, 'W1C', 0x00000000, 'PLL', 'Sticky lock-loss fault'),
    'PLL_LOCK_LOSS_COUNT': Register(0x800C, 'RO', 0x00000000, 'PLL', 'Saturating lock-loss counter'),
    'SLVS_CTRL': Register(0x9000, 'RW', 0x00000140, 'Analog', 'SLVS driver and active-low reference controls'),
    'RX_CTRL': Register(0x9004, 'RW', 0x00000000, 'Analog', 'Receiver select enable and termination controls'),
}

REGISTER_FIELDS = {
    'CHIP_ID': {
        'IDENTITY': Field(0, 32, 'RO', 0x53504D54, 'ASCII identity value 0x53504D54'),
    },
    'ABI_VERSION': {
        'MINOR': Field(0, 16, 'RO', 0x0, 'ABI minor version'),
        'MAJOR': Field(16, 16, 'RO', 0x1, 'ABI major version'),
    },
    'GLOBAL_CTRL': {
        'ENABLE': Field(0, 1, 'RW', 0x0, 'Global acquisition enable; must agree with MODE'),
        'MODE': Field(1, 3, 'RW', 0x0, '0 disabled, 1 TDC, 2 position, 3 both, 4 calibration'),
        'AXIS_MASK': Field(4, 3, 'RW', 0x7, 'Normal R Y B enable mask; TDC and both require 0x7'),
        'AUTO_RESET_ENABLE': Field(7, 1, 'RW', 0x1, 'Enable automatic matrix reset after an event'),
    },
    'GLOBAL_STATUS': {
        'ENABLE': Field(0, 1, 'RO', 0x0, 'Active global acquisition enable'),
        'MODE': Field(1, 3, 'RO', 0x0, 'Active operating mode encoding'),
        'AXIS_MASK': Field(4, 3, 'RO', 0x0, 'Active R Y B axis mask'),
        'SAFE_IDLE': Field(7, 1, 'RO', 0x0, 'All controlled datapaths are idle and configuration-safe'),
    },
    'GLOBAL_FAULT': {
        'ACCESS': Field(0, 1, 'RO', 0x0, 'System access-protocol fault summary'),
        'TDC': Field(1, 1, 'RO', 0x0, 'OR of R Y and B TDC fault summaries'),
        'POSITION': Field(2, 1, 'RO', 0x0, 'Position page fault summary'),
        'EVENT': Field(3, 1, 'RO', 0x0, 'Event page fault summary'),
        'MATRIX': Field(4, 1, 'RO', 0x0, 'Matrix page fault summary'),
        'TX': Field(5, 1, 'RO', 0x0, 'TX page fault summary'),
        'PLL': Field(6, 1, 'RO', 0x0, 'PLL page fault summary'),
    },
    'MAINT_CMD': {
        'CLEAR_ERROR_COUNTERS': Field(0, 1, 'WO', 0x0, 'Clear all saturating error counters while disabled and idle'),
    },
    'TDC_SHARED_CFG': {
        'MAX_HITS': Field(0, 4, 'RW', 0xF, 'Shared nonzero maximum hit count from 1 through 15'),
        'RO_SLOW_CODE': Field(8, 8, 'RW', 0x0, 'Shared slow-ring oscillator tuning code'),
        'RO_FAST_CODE': Field(16, 8, 'RW', 0x0, 'Shared fast-ring oscillator tuning code'),
    },
    'TDC_SHARED_CMD': {
        'SOFT_RESET': Field(0, 1, 'WO', 0x0, 'Pulse soft reset to all three TDC axes'),
        'FIFO_CLEAR': Field(1, 1, 'WO', 0x0, 'Pulse FIFO clear to all three TDC axes'),
    },
    'CALIB_AXIS_MASK': {
        'AXIS_MASK': Field(0, 3, 'RW', 0x7, 'Nonzero calibration mask; bit 0 R, bit 1 Y, bit 2 B'),
    },
    'ACCESS_STATUS': {
        'FAULT_PENDING': Field(0, 1, 'RO', 0x0, 'At least one ACCESS_FAULT bit is set'),
        'LAST_OPERATION_WRITE': Field(1, 1, 'RO', 0x0, 'Last failing access was a write'),
        'LAST_CAUSE': Field(8, 8, 'RO', 0x0, 'Cause code for the last failing access'),
    },
    'ACCESS_FAULT': {
        'MISALIGNED': Field(0, 1, 'W1C', 0x0, 'Misaligned 16-bit register pointer'),
        'UNMAPPED': Field(1, 1, 'W1C', 0x0, 'Unmapped register address'),
        'READ_ONLY_WRITE': Field(2, 1, 'W1C', 0x0, 'Write attempted to a read-only register'),
        'INVALID_VALUE': Field(3, 1, 'W1C', 0x0, 'Field encoding or value violated its contract'),
        'UNSAFE_WRITE': Field(4, 1, 'W1C', 0x0, 'Write attempted outside its disabled-idle window'),
        'INCOMPLETE_WRITE': Field(5, 1, 'W1C', 0x0, 'I2C STOP or repeated START discarded a partial data word'),
        'I2C_RESET_ABORT': Field(6, 1, 'W1C', 0x0, 'I2C transport reset discarded a partial data word'),
    },
    'ACCESS_LAST_INFO': {
        'ADDRESS': Field(0, 16, 'RO', 0x0, 'Register pointer for the last failing access'),
        'CAUSE': Field(16, 8, 'RO', 0x0, 'Cause code for the last failing access'),
        'WRITE': Field(24, 1, 'RO', 0x0, 'One for a failed write and zero for a failed read'),
    },
    'ACCESS_LAST_WDATA': {
        'WRITE_DATA': Field(0, 32, 'RO', 0x0, 'Payload assembled for the last failing write'),
    },
    'ACCESS_ERROR_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating count of invalid CSR and I2C accesses'),
    },
    'TDC_R_STATUS': {
        'READY': Field(0, 1, 'RO', 0x0, 'R-axis accepts a new event'),
        'BUSY': Field(1, 1, 'RO', 0x0, 'R-axis conversion is active'),
        'FIFO_FULL': Field(2, 1, 'RO', 0x0, 'R-axis local FIFO is full'),
        'STOP_ARMED': Field(3, 1, 'RO', 0x0, 'R-axis stop capture is armed'),
        'PACKET_ACTIVE': Field(4, 1, 'RO', 0x0, 'R-axis packet emission is active'),
        'PACKET_PENDING': Field(5, 1, 'RO', 0x0, 'R-axis packet is pending'),
        'PAGE_ID': Field(8, 4, 'RO', 0x0, 'Page discriminator value 1'),
    },
    'TDC_R_FAULT': {
        'FIFO_FULL': Field(0, 1, 'W1C', 0x0, 'Sticky R-axis FIFO-full edge'),
    },
    'TDC_R_ERROR_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating R-axis FIFO-full edge count'),
    },
    'TDC_Y_STATUS': {
        'READY': Field(0, 1, 'RO', 0x0, 'Y-axis accepts a new event'),
        'BUSY': Field(1, 1, 'RO', 0x0, 'Y-axis conversion is active'),
        'FIFO_FULL': Field(2, 1, 'RO', 0x0, 'Y-axis local FIFO is full'),
        'STOP_ARMED': Field(3, 1, 'RO', 0x0, 'Y-axis stop capture is armed'),
        'PACKET_ACTIVE': Field(4, 1, 'RO', 0x0, 'Y-axis packet emission is active'),
        'PACKET_PENDING': Field(5, 1, 'RO', 0x0, 'Y-axis packet is pending'),
        'PAGE_ID': Field(8, 4, 'RO', 0x0, 'Page discriminator value 2'),
    },
    'TDC_Y_FAULT': {
        'FIFO_FULL': Field(0, 1, 'W1C', 0x0, 'Sticky Y-axis FIFO-full edge'),
    },
    'TDC_Y_ERROR_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating Y-axis FIFO-full edge count'),
    },
    'TDC_B_STATUS': {
        'READY': Field(0, 1, 'RO', 0x0, 'B-axis accepts a new event'),
        'BUSY': Field(1, 1, 'RO', 0x0, 'B-axis conversion is active'),
        'FIFO_FULL': Field(2, 1, 'RO', 0x0, 'B-axis local FIFO is full'),
        'STOP_ARMED': Field(3, 1, 'RO', 0x0, 'B-axis stop capture is armed'),
        'PACKET_ACTIVE': Field(4, 1, 'RO', 0x0, 'B-axis packet emission is active'),
        'PACKET_PENDING': Field(5, 1, 'RO', 0x0, 'B-axis packet is pending'),
        'PAGE_ID': Field(8, 4, 'RO', 0x0, 'Page discriminator value 3'),
    },
    'TDC_B_FAULT': {
        'FIFO_FULL': Field(0, 1, 'W1C', 0x0, 'Sticky B-axis FIFO-full edge'),
    },
    'TDC_B_ERROR_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating B-axis FIFO-full edge count'),
    },
    'POSITION_CFG': {
        'MODE': Field(0, 1, 'RW', 0x0, '0 cluster mode and 1 raw mode'),
        'GAP_THRESHOLD': Field(1, 7, 'RW', 0x2, 'Maximum zero-run retained within one cluster; range 0 through 64'),
        'MIN_CLUSTER_SPAN': Field(8, 7, 'RW', 0x1, 'Minimum accepted cluster span; range 1 through 64'),
    },
    'POSITION_STATUS': {
        'PACKET_PENDING': Field(0, 1, 'RO', 0x0, 'A position packet is queued'),
        'PACKET_BUSY': Field(1, 1, 'RO', 0x0, 'Position packet emission is active'),
        'SNAPSHOT_CAPTURED': Field(2, 1, 'RO', 0x0, 'The current position snapshot was captured'),
    },
    'POSITION_FAULT': {
        'PACKET_DROP': Field(0, 1, 'W1C', 0x0, 'Sticky position packet-drop edge'),
    },
    'POSITION_DROP_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating position packet-drop edge count'),
    },
    'EVENT_STATUS': {
        'EVENT_ID': Field(0, 14, 'RO', 0x0, 'Identifier assigned to the active or most recent event'),
        'BUSY': Field(14, 1, 'RO', 0x0, 'Event coordinator is processing an event'),
    },
    'EVENT_MASK_STATUS': {
        'REQUIRED_PACKET_MASK': Field(0, 4, 'RO', 0x0, 'Sources required for the current event bundle'),
        'COMPLETED_PACKET_MASK': Field(4, 4, 'RO', 0x0, 'Sources that completed the current event bundle'),
        'REQUIRED_RESET_ACK_MASK': Field(8, 4, 'RO', 0x0, 'Sources required to acknowledge matrix reset'),
        'OBSERVED_RESET_ACK_MASK': Field(12, 4, 'RO', 0x0, 'Sources that acknowledged matrix reset'),
    },
    'SNAPSHOT_CFG': {
        'SETTLE_CYCLES': Field(0, 16, 'RW', 0x2, 'Cycles between event acceptance and position snapshot'),
        'WATCHDOG_CYCLES': Field(16, 16, 'RW', 0x40, 'Nonzero event-completion watchdog limit'),
    },
    'RESET_CFG': {
        'PULSE_WIDTH_CYCLES': Field(0, 16, 'RW', 0x0, 'Automatic matrix-reset pulse width; zero disables the pulse'),
    },
    'SNAPSHOT_RESET_STATUS': {
        'SNAPSHOT_VALID': Field(0, 1, 'RO', 0x0, 'A completed snapshot is available'),
        'SNAPSHOT_BUSY': Field(1, 1, 'RO', 0x0, 'Snapshot controller is active'),
        'SNAPSHOT_REARM_READY': Field(2, 1, 'RO', 0x0, 'Snapshot controller can accept the next event'),
        'RESET_BUSY': Field(3, 1, 'RO', 0x0, 'Automatic matrix-reset pulse is active'),
        'RESET_DONE': Field(4, 1, 'RO', 0x0, 'Automatic matrix reset completed'),
        'RESET_DISABLED': Field(5, 1, 'RO', 0x0, 'The completed event did not request automatic reset'),
    },
    'EVENT_FAULT': {
        'EVENT_REJECT': Field(0, 1, 'W1C', 0x0, 'Sticky event-not-ready rejection'),
        'SNAPSHOT_TIMEOUT': Field(1, 1, 'W1C', 0x0, 'Sticky snapshot watchdog timeout'),
        'SNAPSHOT_PROTOCOL': Field(2, 1, 'W1C', 0x0, 'Sticky snapshot overlap or rejection'),
        'RESET_DISABLED': Field(3, 1, 'W1C', 0x0, 'Sticky event completion without automatic reset'),
    },
    'EVENT_REJECT_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating event-not-ready rejection count'),
    },
    'SNAPSHOT_TIMEOUT_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating snapshot watchdog-timeout count'),
    },
    'SNAPSHOT_OVERLAP_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating overlapping snapshot-request count'),
    },
    'SNAPSHOT_REJECT_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating rejected snapshot-request count'),
    },
    'RESET_DISABLED_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating event completions without automatic reset'),
    },
    'EVENT_CMD': {
        'SNAPSHOT_CLEAR': Field(0, 1, 'WO', 0x0, 'Pulse snapshot clear'),
    },
    'SNAPSHOT_R_LO': {
        'DATA': Field(0, 32, 'RO', 0x0, 'R snapshot bits 31 through 0'),
    },
    'SNAPSHOT_R_HI': {
        'DATA': Field(0, 32, 'RO', 0x0, 'R snapshot bits 63 through 32'),
    },
    'SNAPSHOT_Y_LO': {
        'DATA': Field(0, 32, 'RO', 0x0, 'Y snapshot bits 31 through 0'),
    },
    'SNAPSHOT_Y_HI': {
        'DATA': Field(0, 32, 'RO', 0x0, 'Y snapshot bits 63 through 32'),
    },
    'SNAPSHOT_B_LO': {
        'DATA': Field(0, 32, 'RO', 0x0, 'B snapshot bits 31 through 0'),
    },
    'SNAPSHOT_B_HI': {
        'DATA': Field(0, 32, 'RO', 0x0, 'B snapshot bits 63 through 32'),
    },
    'MATRIX_CMD': {
        'START': Field(0, 1, 'WO', 0x0, 'Pulse the selected matrix configuration operation'),
        'OPERATION': Field(1, 3, 'RW', 0x1, '1 write column, 2 read column, 3 fill zero, 4 fill one'),
    },
    'MATRIX_STATUS': {
        'BUSY': Field(0, 1, 'RO', 0x0, 'Matrix configuration controller is active'),
        'DONE': Field(1, 1, 'RO', 0x0, 'Most recent matrix command completed'),
        'ERROR': Field(2, 1, 'RO', 0x0, 'Matrix configuration controller reports an error'),
        'LAST_ERROR': Field(3, 4, 'RO', 0x0, 'Most recent matrix controller error code'),
        'READBACK_VALID': Field(7, 1, 'RO', 0x0, 'MATRIX_RDATA contains valid readback data'),
        'CONFIG_VALID': Field(8, 1, 'RO', 0x0, 'Matrix configuration state is valid'),
    },
    'MATRIX_COLUMN': {
        'INDEX': Field(0, 6, 'RW', 0x0, 'Matrix column index from 0 through 43'),
    },
    'MATRIX_WDATA_LO': {
        'DATA': Field(0, 32, 'RW', 0x0, 'Matrix write payload bits 31 through 0'),
    },
    'MATRIX_WDATA_HI': {
        'DATA': Field(0, 32, 'RW', 0x0, 'Matrix write payload bits 63 through 32'),
    },
    'MATRIX_RDATA_LO': {
        'DATA': Field(0, 32, 'RO', 0x0, 'Matrix readback bits 31 through 0'),
    },
    'MATRIX_RDATA_HI': {
        'DATA': Field(0, 32, 'RO', 0x0, 'Matrix readback bits 63 through 32'),
    },
    'MATRIX_FAULT': {
        'COMMAND_REJECT': Field(0, 1, 'W1C', 0x0, 'Sticky unsafe or invalid matrix command'),
        'CONTROLLER_ERROR': Field(1, 1, 'W1C', 0x0, 'Sticky matrix controller error edge'),
        'LAST_ERROR': Field(4, 4, 'RO', 0x0, 'Live most recent matrix controller error code'),
    },
    'MATRIX_REJECT_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating rejected matrix-command count'),
    },
    'MATRIX_ERROR_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating matrix controller-error edge count'),
    },
    'TX_BUNDLE_STATUS': {
        'BUSY': Field(0, 1, 'RO', 0x0, 'Event-bundle transmitter is active'),
        'IDLE': Field(1, 1, 'RO', 0x0, 'Event-bundle transmitter is idle'),
        'MISSING_SOURCE': Field(2, 1, 'RO', 0x0, 'Current bundle completed without every required source'),
    },
    'TX_FIFO_STATUS': {
        'EMPTY': Field(0, 1, 'RO', 0x0, 'Output FIFO is empty'),
        'FULL': Field(1, 1, 'RO', 0x0, 'Output FIFO is full'),
        'ALMOST_FULL': Field(2, 1, 'RO', 0x0, 'Output FIFO reached the fixed reserve threshold'),
        'LEVEL': Field(4, 12, 'RO', 0x0, 'Number of occupied output FIFO words'),
        'FREE_WORDS': Field(16, 16, 'RO', 0x0, 'Number of free output FIFO words'),
    },
    'TX_FIFO_GEOMETRY': {
        'RESERVE_ENTRIES': Field(0, 16, 'RO', 0x81, 'Fixed event-bundle reserve threshold in words'),
        'DEPTH': Field(16, 16, 'RO', 0x100, 'Physical output FIFO depth in words'),
    },
    'TX_DDR_STATUS': {
        'EMPTY': Field(0, 1, 'RO', 0x0, 'DDR pairer has no pending word'),
        'BUSY': Field(1, 1, 'RO', 0x0, 'DDR pairer contains or emits a word pair'),
        'PAIR_VALID': Field(2, 1, 'RO', 0x0, 'DDR low and high words are valid'),
        'PADDED': Field(3, 1, 'RO', 0x0, 'Most recent pair used deterministic odd-word padding'),
    },
    'TX_FAULT': {
        'MISSING_SOURCE': Field(0, 1, 'W1C', 0x0, 'Sticky event-bundle missing-source edge'),
        'FIFO_OVERFLOW': Field(1, 1, 'W1C', 0x0, 'Sticky output FIFO overflow edge'),
    },
    'TX_MISSING_SOURCE_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating missing-source edge count'),
    },
    'TX_FIFO_OVERFLOW_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating output FIFO overflow edge count'),
    },
    'PLL_CTRL': {
        'FINT_SELECT': Field(0, 8, 'RW', 0x0, 'PLL fractional or integer selection code'),
        'RO_SWITCH': Field(8, 5, 'RW', 0x0, 'PLL ring-oscillator switch code'),
        'SELECT_PULSE_PFD': Field(13, 1, 'RW', 0x0, 'Select pulse input for the phase-frequency detector'),
        'ENABLE_DIVIDER': Field(14, 1, 'RW', 0x1, 'Enable PLL output divider'),
        'SELECT_40M': Field(15, 1, 'RW', 0x0, 'Select the 40 MHz PLL path'),
        'SELECT_EXTERNAL_160M': Field(16, 1, 'RW', 0x0, 'Select the external 160 MHz system clock'),
    },
    'PLL_STATUS': {
        'LOCKED': Field(0, 1, 'RO', 0x0, 'PLL lock indication'),
        'EXTERNAL_160M_SELECTED': Field(1, 1, 'RO', 0x0, 'External 160 MHz system clock is selected'),
        'DIVIDER_ENABLED': Field(2, 1, 'RO', 0x0, 'PLL output divider is enabled'),
    },
    'PLL_FAULT': {
        'LOCK_LOSS': Field(0, 1, 'W1C', 0x0, 'Sticky falling edge of PLL lock'),
    },
    'PLL_LOCK_LOSS_COUNT': {
        'COUNT': Field(0, 32, 'RO', 0x0, 'Saturating PLL lock-loss edge count'),
    },
    'SLVS_CTRL': {
        'DRIVE_STRENGTH': Field(0, 4, 'RW', 0x0, 'SLVS output-driver strength selection'),
        'EXTERNAL_VREF_ENABLE': Field(4, 1, 'RW', 0x0, 'Enable external SLVS reference input'),
        'DRIVER_ENABLE': Field(5, 1, 'RW', 0x0, 'Enable SLVS output driver'),
        'VREF_ADJUST_B': Field(6, 1, 'RW', 0x1, 'Active-low SLVS reference adjustment control'),
        'VREF_400MV_ENABLE': Field(7, 1, 'RW', 0x0, 'Enable internal 400 mV SLVS reference'),
        'REFERENCE_DRIVER_ENABLE_B': Field(8, 1, 'RW', 0x1, 'Active-low SLVS reference-driver enable'),
    },
    'RX_CTRL': {
        'SELECT': Field(0, 4, 'RW', 0x0, 'Receiver input selection code'),
        'ENABLE': Field(4, 1, 'RW', 0x0, 'Enable receiver'),
        'TERMINATION_ENABLE': Field(5, 1, 'RW', 0x0, 'Enable receiver termination'),
    },
}

BY_ADDRESS = {reg.address: (name, reg) for name, reg in REGISTERS.items()}
