#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PNR_SCRIPTS="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PNR_SCRIPTS/../../.." && pwd)"
PROFILE="$PNR_SCRIPTS/innovus_mptdc_free_placement_trial.tcl"
ATTEMPT="$PNR_SCRIPTS/server_run_mptdc_free_placement_attempt.sh"
PIPELINE="$PNR_SCRIPTS/server_run_mptdc_free_pnr_pipeline.sh"
CANONICAL="$PNR_SCRIPTS/server_run_innovus_mptdc_digital_signoff.sh"
PHYSICAL_EFFORT="$PNR_SCRIPTS/innovus_mptdc_physical_effort.tcl"
TIE_HELPERS="$PNR_SCRIPTS/innovus_mptdc_tie1_insertion_trial.tcl"
PVS_DRIVER="$REPO_ROOT/MPTDC/scripts/pvs/server_run_mptdc_free_trial_pvs.sh"
PVS_ECO_DRIVER="$PNR_SCRIPTS/server_run_mptdc_free_trial_pvs_eco.sh"
PVS_ECO_VALIDATOR="$PNR_SCRIPTS/validate_mptdc_free_pvs_eco_commands.py"
LVS_REPLAY="$REPO_ROOT/MPTDC/scripts/pvs/03_replay_pvs_lvs_from_template.sh"
COLLECTOR="$REPO_ROOT/MPTDC/ci/collect_mptdc_server_snapshot.sh"

bash -n "$ATTEMPT"
bash -n "$PIPELINE"
bash -n "$PVS_DRIVER"
bash -n "$PVS_ECO_DRIVER"
bash -n "$LVS_REPLAY"

grep -Fq 'MPTDC_INNOVUS_INIT_TCL' "$CANONICAL"
grep -Fq 'innovus -nowin -init "$INNOVUS_INIT_TCL"' "$CANONICAL"
grep -Fq 'MPTDC_TIE1_TRIAL_LIBRARY_ONLY' "$TIE_HELPERS"
grep -Fq 'MPTDC_DISABLE_ANTENNA_REPAIR' "$PHYSICAL_EFFORT"

grep -Fq 'MPTDC_PNR_FREE_ALL_INTERNAL_PLACEMENT 1' "$PROFILE"
grep -Fq 'MPTDC_PNR_PD_TILE_CONSTRAINT_MODE none' "$PROFILE"
grep -Fq 'MPTDC_PNR_CREATE_RO_ROUTE_BLOCKAGES 0' "$PROFILE"
grep -Fq 'IO_POLICY=INPUTS_WEST_OUTPUTS_EAST_DETERMINISTIC_OVERFLOW' "$PROFILE"
grep -Fq 'TIE1_INSERTION_STAGE=PRE_CTS_PRE_FILLER' "$PROFILE"
grep -Fq 'MPTDC_POSTROUTE_SETUP_OPT_PASSES 2' "$PROFILE"
grep -Fq 'MPTDC_POSTROUTE_HOLD_OPT_PASSES 2' "$PROFILE"
grep -Fq 'MPTDC_PNR_FAST_TAG_TARGETED_ECO 0' "$PROFILE"
grep -Fq 'MPTDC_FILLER_ADD_FILLERS_WITH_DRC 0' "$PROFILE"
grep -Fq 'ANTENNA_REPAIR_ATTEMPTED=NO' "$PROFILE"
grep -Fq 'SIGNOFF_ELIGIBLE=NO' "$PROFILE"

grep -Fq -- '--utilization must be exactly 0.50 or 0.45' "$ATTEMPT"
grep -Fq 'FAILURE_CLASS=PLACEMENT_OR_CONGESTION' "$ATTEMPT"
grep -Fq 'FREE_RO_DOES_NOT_FIT_CORE' "$ATTEMPT"
grep -Fq 'ATTEMPT50_RC" -eq 20' "$PIPELINE"
grep -Fq 'PVS_BASE_DRC_THEN_FULL_LVS' "$ATTEMPT"

test -f "$REPO_ROOT/MPTDC/scripts/pvs/server_run_mptdc_free_trial_pvs.sh"
grep -Fq -- '--diagnostic-free-manager-scope' "$LVS_REPLAY"
grep -Fq 'BLACKBOXED_CELL_COUNT' "$PVS_DRIVER"
grep -Fq 'EXPECTED_CHECKPOINT_SHA256' "$PVS_DRIVER"
grep -Fq 'SOURCE_INPUT_READ_ONLY_STATUS' "$PVS_DRIVER"
grep -Fq 'ONE_ATTRIBUTED_PVS_ROUTING_ECO' "$PVS_DRIVER"
grep -Fq 'FAIL_STOP_PVS_ECO_LIMIT_REACHED' "$PVS_DRIVER"
grep -Fq 'EXACT_MPTDC_FREE_TRIAL_ONE_PVS_ROUTING_ECO' "$PVS_ECO_DRIVER"
grep -Fq 'mptdc_ckpt_assert_geometry_regular_clean' "$PVS_ECO_DRIVER"
grep -Fq 'mptdc_signoff_extract_and_sta' "$PVS_ECO_DRIVER"
test -x "$PVS_ECO_VALIDATOR"
grep -Fq 'MPTDC_SNAPSHOT_INCLUDE_MANAGER_IMAGES' "$PIPELINE"
grep -Fq 'rc=${PIPESTATUS[0]}' "$PIPELINE"
grep -Fq 'copy_manager_images "$SRC_DIR/manager"' "$COLLECTOR"
grep -Fq 'SOURCE_BASE_SCAN=' "$PVS_ECO_DRIVER"
grep -Fq 'SOURCE_INPUT_READ_ONLY_STATUS)" == PASS' "$PVS_ECO_DRIVER"
! grep -Eq '\|[[:space:]]*None' "$PVS_ECO_VALIDATOR" "$REPO_ROOT/MPTDC/scripts/pvs/07_classify_mptdc_free_trial_drc.py"
MPTDC_REPO_ROOT="$REPO_ROOT" MPTDC_FREE_PLACEMENT_LIBRARY_ONLY=1 tclsh "$PROFILE"
echo "FREE_PLACEMENT_PROFILE_STATIC_TEST=PASS"
