# =============================================================================
# Project  : SPAD_MPTDC — Vernier Time-to-Digital Converter
# File     : procedures.tcl
# Purpose  : Reusable helper procedures for synthesis and PnR flows
# Author   : Karim Sabra
# =============================================================================
# Inspired by enics-labs/rtl2gds-demo procedures.
# Provides: stage tracking, message formatting, timing report helpers,
#           cost group definitions, and debug utilities.
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Global stage tracking
# ─────────────────────────────────────────────────────────────────────────────
if {![info exists this_run]} {
    array set this_run {
        stage       "init"
        stage_count 0
        start_time  0
    }
    set this_run(start_time) [clock seconds]
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_start_stage — Mark the beginning of a flow stage
# ─────────────────────────────────────────────────────────────────────────────
# Usage: mptdc_start_stage "synthesis"
# Creates report subdirectory and prints a banner.
proc mptdc_start_stage {stage_name} {
    global this_run design

    incr this_run(stage_count)
    set this_run(stage) $stage_name

    set elapsed [expr {[clock seconds] - $this_run(start_time)}]
    set mins [expr {$elapsed / 60}]
    set secs [expr {$elapsed % 60}]

    puts ""
    puts "================================================================"
    puts " Stage $this_run(stage_count): [string toupper $stage_name]"
    puts " Elapsed: ${mins}m ${secs}s"
    puts "================================================================"

    # Create report subdirectory for this stage
    if {[info exists design(synthesis_reports)]} {
        file mkdir "$design(synthesis_reports)/$stage_name"
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_message — Formatted info/warning message
# ─────────────────────────────────────────────────────────────────────────────
# Usage: mptdc_message "Loading libraries" [low|medium|high]
proc mptdc_message {msg {level "medium"}} {
    set prefix "MPTDC_INFO"
    switch $level {
        low     { set prefix "MPTDC_DEBUG" }
        medium  { set prefix "MPTDC_INFO" }
        high    { set prefix "MPTDC_WARN" }
    }
    puts "$prefix: $msg"
}

proc mptdc_write_report_failure {rpt_file title err} {
    set fh [open $rpt_file w]
    puts $fh "$title could not be generated."
    puts $fh ""
    puts $fh $err
    close $fh
}

proc mptdc_run_report {cmd rpt_file title} {
    if {[catch {eval $cmd > $rpt_file} err]} {
        mptdc_write_report_failure $rpt_file $title $err
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_report_timing — Generate timing reports for current stage
# ─────────────────────────────────────────────────────────────────────────────
# Generates timing reports into the current stage directory using only
# report_timing options supported by the lab-server Genus 22.13 build.
proc mptdc_report_timing {report_dir} {
    global this_run

    set stage $this_run(stage)
    set dir "$report_dir/$stage"
    file mkdir $dir

    mptdc_message "Generating timing reports → $dir"

    # Worst paths in the active view (setup-oriented in the current MMMC setup).
    if {[catch { report_timing -max_paths 20 > "$dir/timing_setup.rpt" } err]} {
        mptdc_write_report_failure "$dir/timing_setup.rpt" "Setup timing report" $err
    }

    # This Genus build does not accept -early/-late on report_timing. Keep a
    # placeholder report so downstream checklisting remains deterministic.
    set fh [open "$dir/timing_hold.rpt" w]
    puts $fh "Hold report not generated by the checked-in bring-up helper."
    puts $fh "The active Genus 22.13 build rejects report_timing -early/-late."
    puts $fh "Use report_constraints or an interactive hold-specific query if"
    puts $fh "you need dedicated hold analysis while bring-up is still in progress."
    close $fh

    # Use QoR as a compact timing summary on this build.
    if {[catch { report_qor > "$dir/timing_summary.rpt" } err]} {
        mptdc_write_report_failure "$dir/timing_summary.rpt" "Timing summary report" $err
    }

    # Violations only: max_slack filters to paths with slack < 0.
    if {[catch { report_timing -max_paths 200 -max_slack 0.0 > "$dir/timing_violations.rpt" } err]} {
        mptdc_write_report_failure "$dir/timing_violations.rpt" "Timing violations report" $err
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_default_cost_groups — Define reg2reg, in2reg, reg2out, in2out
# ─────────────────────────────────────────────────────────────────────────────
# Cost groups help Genus focus optimization effort on critical path types.
proc mptdc_default_cost_groups {} {
    global design

    mptdc_message "Defining cost groups (reg2reg, in2reg, reg2out, in2out)"

    if {[llength [info commands create_cost_group]] == 0 || \
        [llength [info commands path_group]] == 0} {
        mptdc_message \
            "Genus build lacks create_cost_group/path_group; keeping default clock-derived cost groups" \
            high
        return
    }

    if {[catch {
        # Register-to-register (internal paths — usually the tightest)
        create_cost_group -name reg2reg
        path_group -from [all_registers] -to [all_registers] -group reg2reg

        # Input-to-register
        create_cost_group -name in2reg
        path_group -from [all_inputs] -to [all_registers] -group in2reg

        # Register-to-output
        create_cost_group -name reg2out
        path_group -from [all_registers] -to [all_outputs] -group reg2out

        # Input-to-output (combinational feedthrough)
        create_cost_group -name in2out
        path_group -from [all_inputs] -to [all_outputs] -group in2out
    } cost_group_err]} {
        mptdc_message \
            "Could not define custom cost groups ($cost_group_err); keeping default clock-derived cost groups" \
            high
    }
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_latch_audit — Check that only expected latches exist
# ─────────────────────────────────────────────────────────────────────────────
proc mptdc_write_latch_report {rpt_file} {
    set fh [open $rpt_file w]
    set latches [get_db insts -if {.base_cell.is_latch==true}]

    puts $fh "MPTDC latch report"
    puts $fh "=================="
    puts $fh "Count: [llength $latches]"
    puts $fh ""
    puts $fh [format "%-80s %s" "Instance" "Base cell"]
    puts $fh [string repeat "-" 120]

    foreach inst $latches {
        set inst_name [get_db $inst .name]
        set base_name [get_db $inst .base_cell.name]
        puts $fh [format "%-80s %s" $inst_name $base_name]
    }

    close $fh
    return [llength $latches]
}

proc mptdc_latch_audit {report_dir} {
    global design

    set rpt_file "$report_dir/latch_audit.rpt"
    mptdc_message "Latch audit → $rpt_file"

    # Count latches
    set latch_count [mptdc_write_latch_report $rpt_file]
    set expected $design(EXPECTED_LATCH_COUNT)

    if {$latch_count == $expected} {
        mptdc_message "LATCH AUDIT PASS: $latch_count latches (expected $expected)"
    } elseif {$latch_count > $expected} {
        mptdc_message "LATCH AUDIT FAIL: $latch_count latches found (expected $expected) — investigate!" high
    } else {
        mptdc_message "LATCH AUDIT WARNING: $latch_count latches (expected $expected) — some may have been optimized" high
    }

    return $latch_count
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_full_reports — Generate all post-synthesis reports
# ─────────────────────────────────────────────────────────────────────────────
proc mptdc_full_reports {report_dir} {
    global this_run design

    set stage $this_run(stage)
    set dir "$report_dir/$stage"
    file mkdir $dir

    mptdc_message "Generating full report set → $dir"

    mptdc_run_report "report_area" \
        "$dir/report_area.rpt" "report_area"
    mptdc_run_report "report_area -hierarchy" \
        "$dir/report_area_hier.rpt" "report_area -hierarchy"
    mptdc_run_report "report_gates" \
        "$dir/report_gates.rpt" "report_gates"
    mptdc_run_report "report_gates -hierarchy" \
        "$dir/report_gates_hier.rpt" "report_gates -hierarchy"
    mptdc_run_report "report_hierarchy" \
        "$dir/report_hierarchy.rpt" "report_hierarchy"
    mptdc_run_report "report_design_rules" \
        "$dir/report_design_rules.rpt" "report_design_rules"
    mptdc_run_report "report_qor" \
        "$dir/report_qor.rpt" "report_qor"

    # Power is vectorless unless a later flow reads switching activity.
    mptdc_run_report "report_power" \
        "$dir/report_power.rpt" "report_power"
    mptdc_run_report "report_power -by_hierarchy" \
        "$dir/report_power_hier.rpt" "report_power -by_hierarchy"

    mptdc_run_report "report_clocks" \
        "$dir/report_clocks.rpt" "report_clocks"
    mptdc_run_report "report_constraints" \
        "$dir/report_constraints.rpt" "report_constraints"

    # Latch audit
    mptdc_latch_audit $dir

    mptdc_write_qor_manifest $dir
}

proc mptdc_write_qor_manifest {dir} {
    global design tech tech_files paths METAL_STACK TRACKS
    global mptdc_optimization_goal mptdc_enable_clock_gating
    global ramstyle_note clock_gating_note

    set fh [open "$dir/run_manifest.rpt" w]
    puts $fh "MPTDC Genus run manifest"
    puts $fh "========================"
    puts $fh "Generated: [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S %Z}]"
    puts $fh ""

    puts $fh "Design"
    puts $fh "------"
    foreach key {
        TOPLEVEL FULLCHIP_OR_MACRO CLK_PERIOD OSC_SLOW_PERIOD OSC_FAST_PERIOD
        CLOCK_UNCERTAINTY OSC_CLOCK_UNCERTAINTY INPUT_DELAY_MACRO
        OUTPUT_DELAY_MACRO OUTPUT_LOAD_MACRO MAX_FANOUT MAX_TRANSITION
        EXPECTED_LATCH_COUNT selected_setup_analysis_views
        selected_hold_analysis_views
    } {
        if {[info exists design($key)]} {
            puts $fh [format "  %-32s %s" $key $design($key)]
        }
    }

    puts $fh ""
    puts $fh "Optimization"
    puts $fh "------------"
    foreach item {
        mptdc_optimization_goal mptdc_enable_clock_gating
        ramstyle_note clock_gating_note
    } {
        if {[info exists $item]} {
            puts $fh [format "  %-32s %s" $item [set $item]]
        }
    }

    puts $fh ""
    puts $fh "Technology"
    puts $fh "----------"
    foreach item {METAL_STACK TRACKS} {
        if {[info exists $item]} {
            puts $fh [format "  %-32s %s" $item [set $item]]
        }
    }
    foreach key {
        STANDARD_CELL_SITE STANDARD_CELL_VDD STANDARD_CELL_GND row_height
        grid_unit HAS_QRC_TECH cts_top_routing_layer_top
        cts_bottom_routing_layer_top
    } {
        if {[info exists tech($key)]} {
            puts $fh [format "  %-32s %s" $key $tech($key)]
        }
    }

    puts $fh ""
    puts $fh "Library and physical files"
    puts $fh "--------------------------"
    foreach key {
        PDK_ROOT SC_ROOT LIB_DIR TECH_LEF_DIR QRC_ROOT
    } {
        if {[info exists paths($key)]} {
            puts $fh [format "  %-32s %s" $key $paths($key)]
        }
    }
    foreach key {
        STDCELLS_BC_LIB STDCELLS_TC_LIB STDCELLS_WC_LIB TECHNOLOGY_LEF
        STDCELLS_LEF QRCTECH_BC QRCTECH_TC QRCTECH_WC
    } {
        if {[info exists tech_files($key)]} {
            puts $fh [format "  %-32s %s" $key $tech_files($key)]
        }
    }

    puts $fh ""
    puts $fh "Review checklist"
    puts $fh "----------------"
    puts $fh "  [ ] timing_violations.rpt contains no real violations"
    puts $fh "  [ ] report_area_hier.rpt identifies dominant blocks"
    puts $fh "  [ ] report_power.rpt/report_power_hier.rpt are understood as vectorless or activity-backed"
    puts $fh "  [ ] latch_audit.rpt matches the intentional async-frontend latch count"
    puts $fh "  [ ] report_design_rules.rpt has no critical transition/fanout/capacitance issues"
    close $fh
}

# ─────────────────────────────────────────────────────────────────────────────
# mptdc_print_summary — Print a final summary banner
# ─────────────────────────────────────────────────────────────────────────────
proc mptdc_print_summary {} {
    global this_run design

    set elapsed [expr {[clock seconds] - $this_run(start_time)}]
    set mins [expr {$elapsed / 60}]
    set secs [expr {$elapsed % 60}]

    puts ""
    puts "================================================================"
    puts " MPTDC SYNTHESIS COMPLETE"
    puts " Design:  $design(TOPLEVEL)"
    puts " Stages:  $this_run(stage_count)"
    puts " Runtime: ${mins}m ${secs}s"
    puts "================================================================"
    puts ""
    puts " Post-synthesis checklist:"
    puts "   [ ] timing_violations.rpt is empty"
    puts "   [ ] Latch audit: exactly $design(EXPECTED_LATCH_COUNT) latches"
    puts "   [ ] report_area_hier.rpt identifies the first area targets"
    puts "   [ ] run_manifest.rpt captures the exact PDK/MMMC/settings baseline"
    puts "   [ ] No critical DRV violations"
    puts "   [ ] Power report is tagged as vectorless or activity-backed"
    puts "================================================================"
}
