#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUN_ID="${1:-final_typical_genus_control_single_root_$(date +%Y%m%d_%H%M%S)}"

export MPTDC_STABLE_CLOSURE_LABEL="${MPTDC_STABLE_CLOSURE_LABEL:-MPTDC_FINAL_TYPICAL_GENUS_REPAIR_CONTROL_SINGLE_ROOT}"
export MPTDC_GENUS_REPAIR_FAST_TAG_PD="${MPTDC_GENUS_REPAIR_FAST_TAG_PD:-1}"
export MPTDC_GENUS_REPAIR_DRV_TRANSITION="${MPTDC_GENUS_REPAIR_DRV_TRANSITION:-1}"
export MPTDC_GENUS_REPAIR_STRONG_FAST_TAG_FLOPS=0
export MPTDC_GENUS_REPAIR_STRONG_CONTROL_DRV=0
export MPTDC_GENUS_REPAIR_CONTROL_CELL_BIAS_STAGE=none
export MPTDC_GENUS_REPAIR_CONTROL_AVOID_INHDX8=0
export MPTDC_GENUS_REPAIR_EXACT_CONTROL_ROOTS=1
export MPTDC_CONTROL_REPAIR_EXACT_MIN_FANOUT="${MPTDC_CONTROL_REPAIR_EXACT_MIN_FANOUT:-64}"
export MPTDC_CONTROL_REPAIR_EXACT_REQUIRE_PD_SINKS=1
export MPTDC_CONTROL_REPAIR_EXACT_ALLOW_RESET_ROOTS=0
export MPTDC_CONTROL_REPAIR_EXACT_DRIVER_REGEX="${MPTDC_CONTROL_REPAIR_EXACT_DRIVER_REGEX:-(^|/)g33116/Q$}"
export MPTDC_CONTROL_REPAIR_EXACT_MAX_ROOTS="${MPTDC_CONTROL_REPAIR_EXACT_MAX_ROOTS:-1}"
export MPTDC_GENUS_RELAX_FAST_TAG_PRESERVE=0
export MPTDC_GENUS_REPAIR_APPLY_DESIGN_DRV=0
export MPTDC_DESIGN_POWER_EFFORT="${MPTDC_DESIGN_POWER_EFFORT:-none}"

echo "# MPTDC Final Typical Genus Single Control Root Repair"
echo "Run mode: FINAL_TYPICAL_GENUS_REPAIR_CONTROL_SINGLE_ROOT"
echo "Strong control driver bias: $MPTDC_GENUS_REPAIR_STRONG_CONTROL_DRV"
echo "Control cell bias stage: $MPTDC_GENUS_REPAIR_CONTROL_CELL_BIAS_STAGE"
echo "Exact control root repair: $MPTDC_GENUS_REPAIR_EXACT_CONTROL_ROOTS"
echo "Exact control root minimum fanout: $MPTDC_CONTROL_REPAIR_EXACT_MIN_FANOUT"
echo "Exact control root requires PD sinks: $MPTDC_CONTROL_REPAIR_EXACT_REQUIRE_PD_SINKS"
echo "Exact control root allows reset roots: $MPTDC_CONTROL_REPAIR_EXACT_ALLOW_RESET_ROOTS"
echo "Exact control root driver regex: $MPTDC_CONTROL_REPAIR_EXACT_DRIVER_REGEX"
echo "Exact control root max roots: $MPTDC_CONTROL_REPAIR_EXACT_MAX_ROOTS"
echo "Strong fast-tag flop bias: $MPTDC_GENUS_REPAIR_STRONG_FAST_TAG_FLOPS"
echo "Relax fast-tag preserve define: $MPTDC_GENUS_RELAX_FAST_TAG_PRESERVE"
echo "Design-wide DRV repair: $MPTDC_GENUS_REPAIR_APPLY_DESIGN_DRV"

exec "$SCRIPT_DIR/server_run_genus_mptdc_final_typical_repair.sh" "$RUN_ID"
