#!/usr/bin/env bash
set -u -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MPTDC_DIR="$(cd "$SYN_DIR/.." && pwd)"
REPO_ROOT="$(cd "$MPTDC_DIR/.." && pwd)"

RUN_ID="${1:-$(date +%Y%m%d_%H%M%S)_o9_final_typical_r750_delta5}"
SNAPSHOT_TAG="genus_osc_pd_${RUN_ID}"
RESULT_DIR="$REPO_ROOT/results/genus_osc_pd/$RUN_ID"
SNAPSHOT_DIR="$MPTDC_DIR/lab_snapshots/$SNAPSHOT_TAG"
GENUS_LOG="$RESULT_DIR/genus_${RUN_ID}.log"
ENV_FILE="$MPTDC_DIR/analog_handoff/real_ro_tune4_abstract.env"
MODEL_FILE="$MPTDC_DIR/analog_handoff/ro_tune4_typical_from_screenshot.yaml"
FREQ_DEFINES="$SYN_DIR/inputs/mptdc_freq_modes.defines"
O9_SDC="${O9_SDC_PATH:-$SYN_DIR/inputs/mptdc_osc_typical_r750_delta5.sdc}"
O9_BASE_FILELIST="${O9_FILELIST_PATH:-$SYN_DIR/filelist_o5_pd_stdcell_closure.f}"
O9_CHAR_RESULT_DIR="${O9_CHARACTERIZATION_RESULT_DIR:-$REPO_ROOT/results/o9_char/20260604_o9_r750_delta5_overnight}"
DEFAULT_EXPORT_RUN_ID="${O1_RO_EXPORT_RUN_ID:-20260528_o1_export_ro_tune4_lef}"
DEFAULT_REAL_LEF="$REPO_ROOT/results/osc_pd/$DEFAULT_EXPORT_RUN_ID/real_abstract_lef/RO_tune4_real_abstract.lef"
DEFAULT_REAL_LIB="$SYN_DIR/macros/RO_tune4_real_abstract_shell.lib"
SC_ROOT_PATH="${SC_ROOT:-/data/pdk/xfab/xh018/diglibs/D_CELLS_HD/v6_0}"
STDCELL_TC_LIB="${SC_ROOT_PATH}/liberty_LPMOS/v6_0_0/PVT_1_80V_range/D_CELLS_HD_LPMOS_typ_1_80V_25C.lib"

case "$RUN_ID" in
  ""|"/"|".")
    echo "ERROR: unsafe RUN_ID: '$RUN_ID'" >&2
    exit 2
    ;;
  *"/"*|".."*)
    echo "ERROR: RUN_ID must be a simple directory name, got '$RUN_ID'" >&2
    exit 2
    ;;
esac

rm -rf "$RESULT_DIR"
mkdir -p "$RESULT_DIR" "$SYN_DIR/logs"

O9_FILELIST="$RESULT_DIR/filelist_${RUN_ID}.f"
if [[ -f "$O9_BASE_FILELIST" ]]; then
  {
    echo "// Generated by $(basename "$0") for O9_FINAL_TYPICAL_SYNTH_FOR_INNOVUS"
    echo "+define+MPTDC_FREQ_R750_DELTA5"
    sed '/^+define+MPTDC_FREQ_R750_DELTA5$/d;/^+define+MPTDC_FAST_TAG_GALOIS$/d;/^+define+MPTDC_RELAX_FAST_TAG_PRESERVE$/d' "$O9_BASE_FILELIST"
  } > "$O9_FILELIST"
fi

{
  echo "# O9 Final Typical R750 Delta5 Genus Run"
  echo "date: $(date -Iseconds)"
  echo "hostname: $(hostname)"
  echo "repo: $REPO_ROOT"
  echo "branch: $(git -C "$REPO_ROOT" branch --show-current 2>/dev/null || true)"
  echo "head: $(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"
  echo "run_id: $RUN_ID"
  echo "snapshot_tag: $SNAPSHOT_TAG"
  echo "mode: O9_R750_DELTA5"
  echo "flavor: O9_FINAL_TYPICAL_SYNTH_FOR_INNOVUS"
  echo "signoff_status: TYPICAL_ONLY_NOT_MMMC_NOT_FINAL_SIGNOFF"
  echo "nfast_encoding: raw_lfsr_tag"
  echo "packet_format_version: fixed_raw_features_v2_7"
  echo "characterization_result_dir: $O9_CHAR_RESULT_DIR"
  echo
  echo "git status --short:"
  git -C "$REPO_ROOT" status --short 2>/dev/null || true
  echo
} | tee "$RESULT_DIR/run_manifest.txt" | tee "$GENUS_LOG"

INPUT_RC=0
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$ENV_FILE"
else
  echo "ERROR: missing O1/O9 env file: $ENV_FILE" | tee -a "$GENUS_LOG"
  INPUT_RC=2
fi

REAL_LEF="${O1_RO_LEF_PATH:-$DEFAULT_REAL_LEF}"
REAL_LIB="${O1_RO_LIBERTY_PATH:-$DEFAULT_REAL_LIB}"

for required in "$REAL_LEF" "$REAL_LIB" "$O9_SDC" "$O9_FILELIST" "$MODEL_FILE" "$FREQ_DEFINES"; do
  if [[ ! -f "$required" ]]; then
    echo "ERROR: missing required O9 input: $required" | tee -a "$GENUS_LOG"
    INPUT_RC=2
  fi
done

if [[ ! -f "$O9_CHAR_RESULT_DIR/overnight_manifest.json" \
      && ! -f "$O9_CHAR_RESULT_DIR/characterization/characterization_manifest.json" \
      && "${O9_ALLOW_SYNTH_WITHOUT_CHAR:-0}" != "1" ]]; then
  {
    echo "ERROR: O9 characterization evidence not found under $O9_CHAR_RESULT_DIR"
    echo "Run the O9 R750 delta5 Xcelium characterization first, or set O9_CHARACTERIZATION_RESULT_DIR."
  } | tee -a "$GENUS_LOG"
  INPUT_RC=4
fi

MACRO_NAME="unknown"
if [[ "$INPUT_RC" == "0" ]]; then
  MACRO_NAME="$(awk '/^[[:space:]]*MACRO[[:space:]]+/ {print $2; exit}' "$REAL_LEF")"
  echo "O9 real LEF: $REAL_LEF" | tee -a "$GENUS_LOG"
  echo "O9 real LEF macro: $MACRO_NAME" | tee -a "$GENUS_LOG"
  if [[ "$MACRO_NAME" != "RO_tune4" ]]; then
    echo "ERROR: LEF macro '$MACRO_NAME' does not match expected RO_tune4" | tee -a "$GENUS_LOG"
    INPUT_RC=3
  fi
fi

if [[ "$INPUT_RC" == "0" ]] && ! command -v genus >/dev/null 2>&1; then
  echo "ERROR: genus not found in PATH; run on the lab server." | tee -a "$GENUS_LOG"
  INPUT_RC=127
fi

export MPTDC_TIMING_VIEW=tc_only
export MPTDC_TC_ONLY_VIEW=1
export MPTDC_FREQ_MODE=r750_delta5
export MPTDC_FREQ_MODE_DEFINES="$FREQ_DEFINES"
export O1_USE_REAL_RO_ABSTRACT=1
export O1_RO_LEF_PATH="$REAL_LEF"
export O1_RO_LIBERTY_PATH="$REAL_LIB"
export MPTDC_USE_RO_TUNE4_MACRO=1
export MPTDC_READ_HDL_LIST="$O9_FILELIST"
export MPTDC_OSC_PD_USE_PROVISIONAL=0
export MPTDC_OSC_PD_USE_PROVISIONAL_LIBERTY=0
export MPTDC_OSC_PD_SDC_OVERLAY="$O9_SDC"
export O1_RUN_FLAVOR="O9_FINAL_TYPICAL_SYNTH_FOR_INNOVUS"
export GENUS_EFFORT=closure
export MPTDC_OPT_GOAL="o9_final_typical_r750_delta5_closure"
export MPTDC_OSC_SLOW_PERIOD_NS="${O9_OSC_SLOW_PERIOD_NS:-1.430}"
export MPTDC_OSC_FAST_PERIOD_NS="${O9_OSC_FAST_PERIOD_NS:-1.333}"
export MPTDC_OSC_SLOW_TAP_STEP_NS="${O9_OSC_SLOW_TAP_STEP_NS:-0.079}"
export MPTDC_OSC_FAST_TAP_STEP_NS="${O9_OSC_FAST_TAP_STEP_NS:-0.074}"
export MPTDC_ENABLE_CLOCK_GATING="${O9_ENABLE_CLOCK_GATING:-0}"
export MPTDC_ALLOW_ICG_DONT_USE_OVERRIDE="${O9_ALLOW_ICG_DONT_USE_OVERRIDE:-0}"
export MPTDC_ALLOW_DISCRETE_CLOCK_GATING="${O9_ALLOW_DISCRETE_CLOCK_GATING:-0}"
export MPTDC_RELAX_PD_PRESERVE="${O9_RELAX_PD_PRESERVE:-1}"

{
  echo
  echo "O9 inputs:"
  echo "  MODEL_FILE=$MODEL_FILE"
  echo "  SOURCE_WARNING=screenshot-derived typical RO data; not CSV/Ocean signoff"
  echo "  STDCELL_TC_LIB=$STDCELL_TC_LIB"
  echo "  REAL_LEF=$REAL_LEF"
  echo "  REAL_LIB=$REAL_LIB"
  echo "  O9_SDC=$O9_SDC"
  echo "  O9_FILELIST=$O9_FILELIST"
  echo "  O9_BASE_FILELIST=$O9_BASE_FILELIST"
  echo "  MPTDC_FREQ_MODE=$MPTDC_FREQ_MODE"
  echo "  MPTDC_FREQ_MODE_DEFINES=$MPTDC_FREQ_MODE_DEFINES"
  echo "  GENUS_EFFORT=$GENUS_EFFORT"
  echo "  MPTDC_TIMING_VIEW=$MPTDC_TIMING_VIEW"
  echo "  MPTDC_OSC_SLOW_PERIOD_NS=$MPTDC_OSC_SLOW_PERIOD_NS"
  echo "  MPTDC_OSC_FAST_PERIOD_NS=$MPTDC_OSC_FAST_PERIOD_NS"
  echo "  MPTDC_OSC_SLOW_TAP_STEP_NS=$MPTDC_OSC_SLOW_TAP_STEP_NS"
  echo "  MPTDC_OSC_FAST_TAP_STEP_NS=$MPTDC_OSC_FAST_TAP_STEP_NS"
  echo "  OSC_TS_SLOW_PS=79"
  echo "  OSC_TS_FAST_PS=74"
  echo "  DELTA_STEP=5"
  echo "  DELTA_LSB=10"
  echo "  K_VERNIER=15"
  echo "  RO_SETUP_UNCERTAINTY_PS=10.0"
  echo "  RO_HOLD_UNCERTAINTY_PS=5.0"
  echo "  NFAST_ENCODING=raw_lfsr_tag"
  echo
} | tee -a "$RESULT_DIR/run_manifest.txt" | tee -a "$GENUS_LOG"

GENUS_RC="$INPUT_RC"
if [[ "$INPUT_RC" == "0" ]]; then
  echo "[GENUS_O9] Cleaning generated synthesis outputs/reports for a non-stale run" | tee -a "$GENUS_LOG"
  rm -rf "$SYN_DIR/reports/synthesis" "$SYN_DIR/outputs"
  mkdir -p "$SYN_DIR/reports" "$SYN_DIR/outputs" "$SYN_DIR/logs"

  echo "[GENUS_O9] Starting TC-only final typical closure flow" | tee -a "$GENUS_LOG"
  (
    cd "$SCRIPT_DIR"
    genus -files genus.tcl -log "../logs/genus_o9_final_typical_r750_delta5.log"
  ) 2>&1 | tee -a "$GENUS_LOG"
  GENUS_RC=${PIPESTATUS[0]}
fi

echo "[SNAPSHOT] Collecting Genus O9 snapshot into $SNAPSHOT_DIR" | tee -a "$GENUS_LOG"
SNAPSHOT_RC=0
if ! bash "$SCRIPT_DIR/collect_snapshot.sh" "$SNAPSHOT_TAG" >> "$GENUS_LOG" 2>&1; then
  SNAPSHOT_RC=$?
  echo "WARNING: collect_snapshot.sh failed with rc=$SNAPSHOT_RC" | tee -a "$GENUS_LOG"
fi

if [[ -d "$SNAPSHOT_DIR" ]]; then
  cp -a "$SNAPSHOT_DIR/." "$RESULT_DIR/"
fi
cp "$GENUS_LOG" "$RESULT_DIR/genus_${RUN_ID}.log" 2>/dev/null || true
cp "$O9_SDC" "$RESULT_DIR/final_sdc_overlay_used.sdc" 2>/dev/null || true
cp "$O9_FILELIST" "$RESULT_DIR/final_filelist_used.f" 2>/dev/null || true

for file in \
  report_clock_groups.rpt \
  report_exceptions.rpt \
  timing_osc_counter_hotspots.rpt \
  timing_pd_capture_hotspots.rpt \
  timing_clk_sys_violations.rpt \
  timing_fast_count_to_nfast_hit.rpt; do
  if [[ -f "$RESULT_DIR/synthesis_reports/post_synthesis/$file" && ! -f "$RESULT_DIR/$file" ]]; then
    cp "$RESULT_DIR/synthesis_reports/post_synthesis/$file" "$RESULT_DIR/$file"
  fi
done

POSTSYN_NETLIST="$RESULT_DIR/mptdc_top_asic.postsyn.v"
if [[ ! -f "$POSTSYN_NETLIST" ]]; then
  POSTSYN_NETLIST="$SYN_DIR/outputs/mptdc_top_asic.postsyn.v"
fi

CHECK_REPORT="$RESULT_DIR/o9_final_typical_r750_delta5_check.rpt"
{
  echo "# O9 Final Typical R750 Delta5 Check"
  echo
  echo "post_synth_netlist=$POSTSYN_NETLIST"
  echo
  if [[ -f "$POSTSYN_NETLIST" ]]; then
    echo "## RO_tune4 instance lines"
    grep -nE '^[[:space:]]*RO_tune4[[:space:]]+' "$POSTSYN_NETLIST" || true
    echo
    echo "## tag/PD references"
    grep -nE 'mptdc_fast_epoch_tag|u_fast_tag|gen_fast_tag_col|nfast_hit_latched_reg' "$POSTSYN_NETLIST" || true
    echo
    echo "## old oscillator/counter residue"
    grep -nE 'u_fast_cnt|u_slow_cnt|gray_src_cont_q|gray_snap_ff|dst_count_latched|mptdc_osc_stub' "$POSTSYN_NETLIST" || true
  else
    echo "ERROR: post-synthesis netlist not found"
  fi
} > "$CHECK_REPORT"

RO_COUNT=0
STUB_COUNT=0
OLD_FAST_COUNTER_RESIDUE_COUNT=0
OLD_SLOW_COUNTER_RESIDUE_COUNT=0
CLOCKS_ON_RO=0
FAST_TAG_REF_COUNT=0
DRV_COUNT="unknown"
if [[ -f "$POSTSYN_NETLIST" ]]; then
  RO_COUNT="$(grep -cE '^[[:space:]]*RO_tune4[[:space:]]+' "$POSTSYN_NETLIST" || true)"
  STUB_COUNT="$(grep -cE 'mptdc_osc_stub' "$POSTSYN_NETLIST" || true)"
  OLD_FAST_COUNTER_RESIDUE_COUNT="$(grep -cE 'u_fast_cnt|nfast_src_count.*u_pd' "$POSTSYN_NETLIST" || true)"
  OLD_SLOW_COUNTER_RESIDUE_COUNT="$(grep -cE 'u_slow_cnt|gray_src_cont_q|gray_snap_ff|dst_count_latched' "$POSTSYN_NETLIST" || true)"
  FAST_TAG_REF_COUNT="$(grep -cE 'mptdc_fast_epoch_tag|u_fast_tag|gen_fast_tag_col' "$POSTSYN_NETLIST" || true)"
fi
if [[ -f "$RESULT_DIR/report_clocks.rpt" ]]; then
  CLOCKS_ON_RO="$(grep -cE 'u_ro_tune4.*/?S\[[0-7]\]|u_ro_tune4.*S\[[0-7]\]' "$RESULT_DIR/report_clocks.rpt" || true)"
fi
if [[ -f "$RESULT_DIR/report_design_rules.rpt" ]]; then
  DRV_COUNT="$(grep -ciE 'violation|violated|max_transition|max transition' "$RESULT_DIR/report_design_rules.rpt" || true)"
fi

if command -v python3 >/dev/null 2>&1; then
  if [[ -f "$REPO_ROOT/tools/timing/parse_genus_summary.py" ]]; then
    python3 "$REPO_ROOT/tools/timing/parse_genus_summary.py" "$RESULT_DIR" \
      > "$RESULT_DIR/PARSED_SUMMARY.md" 2>/dev/null || true
  fi
  if [[ -f "$REPO_ROOT/tools/timing/classify_mptdc_timing_paths.py" ]]; then
    reports=()
    for rpt in \
      timing_violations.rpt \
      timing_osc_fast_full_clock.rpt \
      timing_pd_capture_hotspots.rpt \
      timing_osc_counter_hotspots.rpt \
      timing_fast_count_to_nfast_hit.rpt \
      timing_clk_sys_violations.rpt; do
      [[ -f "$RESULT_DIR/$rpt" ]] && reports+=("$RESULT_DIR/$rpt")
    done
    if [[ ${#reports[@]} -gt 0 ]]; then
      python3 "$REPO_ROOT/tools/timing/classify_mptdc_timing_paths.py" "${reports[@]}" \
        --out-csv "$RESULT_DIR/timing_path_classification.csv" \
        --out-summary "$RESULT_DIR/timing_path_classification_summary.md" || true
    fi
  fi
fi

STATUS="O9_SERVER_REVIEW_REQUIRED"
if [[ "$RO_COUNT" == "2" && "$STUB_COUNT" == "0" && "$OLD_FAST_COUNTER_RESIDUE_COUNT" == "0" && "$OLD_SLOW_COUNTER_RESIDUE_COUNT" == "0" ]]; then
  STATUS="O9_NETLIST_CANDIDATE"
fi

{
  echo "# Genus O9 Final Typical R750 Delta5 Summary"
  echo
  echo "- Run ID: \`$RUN_ID\`"
  echo "- Git HEAD: \`$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)\`"
  echo "- Frequency mode: \`O9_R750_DELTA5\`"
  echo "- Genus effort: \`$GENUS_EFFORT\`"
  echo "- Genus exit code: $GENUS_RC"
  echo "- Snapshot exit code: $SNAPSHOT_RC"
  echo "- Signoff status: \`TYPICAL_ONLY_NOT_MMMC_NOT_FINAL_SIGNOFF\`"
  echo "- Standard-cell Liberty: \`$STDCELL_TC_LIB\`"
  echo "- TC-only view: yes"
  echo "- MMMC BC/WC views created: no"
  echo "- Real LEF: \`$REAL_LEF\`"
  echo "- Real LEF macro: \`$MACRO_NAME\`"
  echo "- RO_tune4 Liberty shell: \`$REAL_LIB\`"
  echo "- SDC overlay: \`$O9_SDC\`"
  echo "- HDL filelist: \`$O9_FILELIST\`"
  echo "- RTL frequency define: \`+define+MPTDC_FREQ_R750_DELTA5\`"
  echo "- NFAST encoding: \`raw_lfsr_tag\`"
  echo "- Packet format: \`fixed_raw_features_v2_7\` unchanged"
  echo "- Characterization result link: \`$O9_CHAR_RESULT_DIR\`"
  echo "- Slow period ns: \`$MPTDC_OSC_SLOW_PERIOD_NS\`"
  echo "- Fast period ns: \`$MPTDC_OSC_FAST_PERIOD_NS\`"
  echo "- Slow tap step ns: \`$MPTDC_OSC_SLOW_TAP_STEP_NS\`"
  echo "- Fast tap step ns: \`$MPTDC_OSC_FAST_TAP_STEP_NS\`"
  echo "- DELTA_STEP ps: \`5\`"
  echo "- DELTA_LSB ps: \`10\`"
  echo "- K_VERNIER: \`15\`"
  echo "- Setup uncertainty ps: \`10.0\`"
  echo "- Hold uncertainty ps: \`5.0\`"
  echo "- RO_tune4 instance count: $RO_COUNT"
  echo "- mptdc_osc_stub residue count: $STUB_COUNT"
  echo "- old fast-counter residue count: $OLD_FAST_COUNTER_RESIDUE_COUNT"
  echo "- old slow-counter residue count: $OLD_SLOW_COUNTER_RESIDUE_COUNT"
  echo "- fast-tag reference count: $FAST_TAG_REF_COUNT"
  echo "- report_clocks RO_tune4/S match count: $CLOCKS_ON_RO"
  echo "- DRV rough report-design-rules match count: $DRV_COUNT"
  echo
  echo "O9_STATUS=$STATUS"
  echo "FINAL_SIGNOFF=NO"
  echo "INNOVUS_READY=REVIEW_TIMING_FIRST"
  echo
  echo "## Key Files"
  for file in \
    "genus_${RUN_ID}.log" \
    mptdc_top_asic.postsyn.v \
    mptdc_top_asic.postsyn.sdc \
    final_sdc_overlay_used.sdc \
    final_filelist_used.f \
    o9_final_typical_r750_delta5_check.rpt \
    run_manifest.txt \
    report_clocks.rpt \
    report_clocks_generated.rpt \
    report_clock_groups.rpt \
    report_exceptions.rpt \
    report_constraints.rpt \
    check_timing_intent.rpt \
    check_timing_intent_post_synth.rpt \
    timing_summary.rpt \
    timing_violations.rpt \
    timing_setup.rpt \
    timing_osc_fast_full_clock.rpt \
    timing_osc_counter_hotspots.rpt \
    timing_pd_capture_hotspots.rpt \
    timing_clk_sys_violations.rpt \
    timing_path_classification.csv \
    timing_path_classification_summary.md \
    latch_audit.rpt \
    cdc_manual_audit.rpt \
    report_design_rules.rpt \
    report_design_rules_verbose.rpt \
    report_high_fanout.rpt \
    report_area.rpt \
    report_area_hier.rpt \
    report_qor.rpt \
    report_power.rpt; do
    if [[ -f "$RESULT_DIR/$file" ]]; then
      echo "- present: \`$file\`"
    else
      echo "- missing: \`$file\`"
    fi
  done
} > "$RESULT_DIR/SUMMARY.md"

cat "$RESULT_DIR/SUMMARY.md"

if [[ "$GENUS_RC" != "0" ]]; then
  exit "$GENUS_RC"
fi
if [[ "$SNAPSHOT_RC" != "0" ]]; then
  exit "$SNAPSHOT_RC"
fi
[[ "$STATUS" == "O9_NETLIST_CANDIDATE" ]]
