#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUN_ID="${1:-final_typical_genus_jihd_tap0_micro_v2_$(date +%Y%m%d_%H%M%S)}"

export MPTDC_STABLE_CLOSURE_LABEL="${MPTDC_STABLE_CLOSURE_LABEL:-MPTDC_FINAL_TYPICAL_GENUS_REPAIR_JIHD_TAP0_MICRO_V2}"
export MPTDC_FAST_TAG_REPAIR_EXACT_TAPS="${MPTDC_FAST_TAG_REPAIR_EXACT_TAPS:-0}"
export MPTDC_FAST_TAG_REPAIR_EXACT_BITS="${MPTDC_FAST_TAG_REPAIR_EXACT_BITS:-5 6}"
export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_FANOUT="${MPTDC_FAST_TAG_REPAIR_EXACT_MAX_FANOUT:-2}"
export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_TRANSITION_NS="${MPTDC_FAST_TAG_REPAIR_EXACT_MAX_TRANSITION_NS:-0.30}"
export MPTDC_FAST_TAG_REPAIR_EXACT_MAX_DELAY_NS="${MPTDC_FAST_TAG_REPAIR_EXACT_MAX_DELAY_NS:-1.04}"

exec "$SCRIPT_DIR/server_run_genus_mptdc_final_typical_jihd_tap0_micro.sh" "$RUN_ID"
