#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRIVER="$(cd "$SCRIPT_DIR/.." && pwd)/server_run_mptdc_ro6_recovery_pvs.sh"
TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

REPO="$TMP_ROOT/repo"
WORK="$TMP_ROOT/work/innovus"
PNR_RUN=physical_fixture
PNR_DIR="$WORK/$PNR_RUN"
RO_GDS="$TMP_ROOT/RO_tune6_from_OA.gds"
mkdir -p "$REPO" "$PNR_DIR/checkpoints/04_route.enc.dat"
printf 'real ro fixture\n' > "$RO_GDS"
git init -q -b SPADMIC_test "$REPO"
git -C "$REPO" config user.name 'MPTDC PVS recovery test'
git -C "$REPO" config user.email 'mptdc-pvs-recovery@example.invalid'

tree_hash() {
  local root="$1"
  (
    cd "$root"
    find -L . -type f \
      ! -name '*.cdslck' ! -name '*.lock' ! -name '.*lock*' \
      -print0 |
      LC_ALL=C sort -z |
      while IFS= read -r -d '' file; do
        printf '%s\t' "$file"
        sha256sum "$file"
      done
  ) | sha256sum | awk '{print $1}'
}

PHYSICAL_GATE="$REPO/MPTDC/docs/server_snapshots/innovus/$PNR_RUN/reports/operator_gate_physical_pnr.rpt"
mkdir -p "$(dirname "$PHYSICAL_GATE")"
cat > "$PHYSICAL_GATE" <<'EOF'
STEP=PHYSICAL_PNR
PNR_RC=0
ROUTE_STATUS=PASS
INNOVUS_VERIFY_DRC_STATUS=PASS
GEOMETRY_DRC_VIOLATIONS=0
SHORTS=0
REGULAR_NET_CONNECTIVITY_BAD=0
SPECIAL_NET_CONNECTIVITY_BAD=0
SPECIAL_NET_CONNECTIVITY_RAW_BAD=0
SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES=0
UNROUTED_NETS=0
signal_top_layer=MET3
router_command_top_layer=METTP
ROUTE_COMMAND_STATUS=PASS
SIGNAL_TOP_ROUTE_BLOCKAGE_TEMPORARY=1
SIGNAL_TOP_ROUTE_BLOCKAGE_CREATE_STATUS=PASS
SIGNAL_TOP_ROUTE_BLOCKAGE_REMOVE_STATUS=PASS
SIGNAL_TOP_ROUTE_BLOCKAGE_STATUS=REMOVED
PRE_ROUTE_SROUTE_STATUS=PASS
PRE_ROUTE_DANGLING_MAX=35
PRE_ROUTE_DANGLING_FATAL_COUNT=0
PRE_ROUTE_PG_CROSS_NET_SHORT_COUNT=0
PNR_LEF_SUMMARY_BINDING_STATUS=PASS
PNR_LEF_PATH_MATCH_STATUS=PASS
PNR_LEF_EVIDENCE_STATUS=PASS
PNR_LEF_REQUESTED_SHA256=fixture_hash
PNR_LEF_ACTUAL_SHA256=fixture_hash
PNR_LEF_EXPECTED_SHA256=fixture_hash
PNR_LEF_GATE_STATUS=PASS
RO_HALOS_REQUESTED=1
RO_HALO_ENABLED=1
RO_HALO_STATUS=PASS
RO_HALO_COUNT=2
RO_HALO_CLEARANCE_UM=10.0
SLOW_HALO_STATUS=PASS
FAST_HALO_STATUS=PASS
RO_HALO_OCCUPANCY_STATUS=PASS
RO_HALO_TOTAL_INTRUSION_COUNT=0
RO_HALO_INVALID_INSTANCE_BBOX_COUNT=0
RO_HALO_AUDITED_RO_COUNT=2
RO_PHASE_PLACEMENT_STATUS=PASS
RO_PHASE_MIN_CLEARANCE_UM=17.42
EXTRACTION_STATUS=PASS
SETUP_STATUS_TC=PASS
TC_HOLD_STATUS=PASS
DRV_STATUS=PASS
POWER_REPORT_CAPTURE_STATUS=PASS
IO_PIN_PLACEMENT_STATUS=OK
ro_slow_tap0_o_SOUTH_MET3_PLAN_COUNT=1
ro_fast_tap0_o_SOUTH_MET3_PLAN_COUNT=1
ro_slow_tap0_o_COUNT=1
ro_fast_tap0_o_COUNT=1
RO_TAP_OBSERVABILITY_PIN_COUNT=2
COMMON_PHYSICAL_GATE=1
PHYSICAL_GATE_MODE=STRICT_CLEAN
DECISION=PASS_CONTINUE
EOF
cat > "$(dirname "$PHYSICAL_GATE")/filler_status.rpt" <<'EOF'
FILLER_CANDIDATES=FEED25JIHD FEED15JIHD FEED10JIHD FEED7JIHD FEED5JIHD FEED3JIHD FEED2JIHD FEED1JIHD
FILLER_COUNT=3
FILLER_INSERTION_STATUS=PASS
EOF
cat > "$(dirname "$PHYSICAL_GATE")/row_infra_insertion.rpt" <<'EOF'
FILLER_CANDIDATES=FEED25JIHD FEED15JIHD FEED10JIHD FEED7JIHD FEED5JIHD FEED3JIHD FEED2JIHD FEED1JIHD
TIE_HIGH_CANDIDATES=LOGIC1DJIHD LOGIC1LVJIHD
TIE_LOW_CANDIDATES=LOGIC0DJIHD LOGIC0LVJIHD
EOF
git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m fixtures
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"

FAKE_CADENCE_ENV="$TMP_ROOT/fake_cadence_env.sh"
cat > "$FAKE_CADENCE_ENV" <<'EOF'
: "$MPTDC_CADENCE_FIXTURE_UNSET"
export MPTDC_CADENCE_FIXTURE_LOADED=1
EOF
FAILING_CADENCE_ENV="$TMP_ROOT/failing_cadence_env.sh"
printf 'return 23\n' > "$FAILING_CADENCE_ENV"

FAKE_PREP="$TMP_ROOT/fake_prep.sh"
cat > "$FAKE_PREP" <<'EOF'
#!/usr/bin/env bash
set -eu
test "${MPTDC_CADENCE_FIXTURE_LOADED:-0}" = 1
run_id=""; work=""; checkpoint=""; filler_report=""; row_infra_report=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-id) run_id="$2"; shift 2 ;;
    --innovus-work) work="$2"; shift 2 ;;
    --checkpoint) checkpoint="$2"; shift 2 ;;
    --filler-report) filler_report="$2"; shift 2 ;;
    --row-infra-report) row_infra_report="$2"; shift 2 ;;
    *) shift ;;
  esac
done
test -d "$checkpoint"
test -s "$filler_report"
test -s "$row_infra_report"
if [[ -n "${EXPECTED_PREP_CHECKPOINT:-}" ]]; then
  test "$checkpoint" = "$EXPECTED_PREP_CHECKPOINT"
fi
dir="$work/$run_id"
mkdir -p "$dir/reports" "$dir/manifests" "$dir/logs"
printf 'PVS_PREP_INPUT_STATUS=PASS\n' > "$dir/reports/pvs_prepared_inputs.rpt"
printf 'TAP_PIN_CONTRACT_STATUS=PASS\nRO_TAP_OBSERVABILITY_PIN_COUNT=2\n' > "$dir/reports/tap_pin_contract.rpt"
printf 'STRICT_ATTRIBUTION=1\nMERGED_GDS_SHA256=fixture\n' > "$dir/manifests/pvs_input_hashes.rpt"
EOF

FAKE_AUDIT="$TMP_ROOT/fake_audit.sh"
cat > "$FAKE_AUDIT" <<'EOF'
#!/usr/bin/env bash
set -eu
dir=""
while [[ $# -gt 0 ]]; do
  case "$1" in --result-dir) dir="$2"; shift 2 ;; *) shift ;; esac
done
printf 'PVS_TEMPLATE_AUDIT_STATUS=PASS\n' > "$dir/manifests/pvs_template_audit.status"
EOF

FAKE_DRC="$TMP_ROOT/fake_drc.sh"
cat > "$FAKE_DRC" <<'EOF'
#!/usr/bin/env bash
set -eu
dir=""; variant=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prepared-dir) dir="$2"; shift 2 ;;
    --variant) variant="$2"; shift 2 ;;
    *) shift ;;
  esac
done
status=PASS; total=0; nonzero=0; pvs_rc=0; rc=0
if [[ "${FAKE_DRC_FAIL_VARIANT:-}" == "$variant" ]]; then
  status=FAIL; total=1; nonzero=0; pvs_rc=1; rc=8
elif [[ "${FAKE_DRC_NONZERO_VARIANT:-}" == "$variant" ]]; then
  status=FAIL; total=3; nonzero=1; pvs_rc=0; rc=9
fi
rule_report="$dir/reports/pvs_drc_${variant}_nonzero_rules.tsv"
printf 'rule\tprimary\texpanded\n' > "$rule_report"
if [[ "$nonzero" == 1 ]]; then
  printf 'M1.MIN.AREA\t3\t3\n' >> "$rule_report"
fi
rule_hash="$(sha256sum "$rule_report" | awk '{print $1}')"
cat > "$dir/reports/pvs_drc_${variant}_status.rpt" <<RPT
STATUS=$status
PVS_DRC_STATUS=$status
PVS_DRC_VARIANT=${variant^^}
PVS_RC=$pvs_rc
DRC_TOTAL_PRIMARY=$total
DRC_TOTAL_EXPANDED=$total
NONZERO_RULE_COUNT=$nonzero
NONZERO_RULE_REPORT=$rule_report
NONZERO_RULE_REPORT_SHA256=$rule_hash
RPT
if [[ -n "${DRC_CALLS:-}" ]]; then printf '%s\n' "$variant" >> "$DRC_CALLS"; fi
exit "$rc"
EOF

FAKE_LVS="$TMP_ROOT/fake_lvs.sh"
cat > "$FAKE_LVS" <<'EOF'
#!/usr/bin/env bash
set -eu
dir=""; diagnostic=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prepared-dir) dir="$2"; shift 2 ;;
    --diagnostic-allow-base-drc-debt) diagnostic=1; shift ;;
    *) shift ;;
  esac
done
if [[ "${EXPECT_DIAGNOSTIC_LVS:-0}" == 1 ]]; then
  test "$diagnostic" = 1
  grep -qx 'PVS_RUN_CLASS=DIAGNOSTIC_NOT_SIGNOFF' \
    "$dir/manifests/pvs_diagnostic_scope.rpt"
else
  test "$diagnostic" = 0
fi
if [[ -n "${LVS_CALLS:-}" ]]; then printf '%s\n' "$diagnostic" >> "$LVS_CALLS"; fi
if [[ "${FAKE_LVS_MISMATCH:-0}" == 1 ]]; then
  printf 'STATUS=FAIL\nPVS_LVS_STATUS=NOT_PROVEN\nPVS_RC=0\n' > "$dir/reports/pvs_lvs_status.rpt"
  exit 8
fi
printf 'STATUS=PASS\nPVS_LVS_STATUS=MATCH\nPVS_RC=0\n' > "$dir/reports/pvs_lvs_status.rpt"
EOF

FAKE_PUBLISHER="$TMP_ROOT/fake_publisher.sh"
cat > "$FAKE_PUBLISHER" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "$PUBLISH_CALLS"
echo 'EVIDENCE_PUSH_RC=0'
EOF
chmod +x "$FAKE_PREP" "$FAKE_AUDIT" "$FAKE_DRC" "$FAKE_LVS" "$FAKE_PUBLISHER"

run_driver() {
  local pvs_run="$1"
  local calls="$2"
  local pnr_run="$PNR_RUN"
  local extra_env=()
  local driver_args=()
  shift 2
  if [[ "${1:-}" == --test-pnr-run ]]; then
    pnr_run="$2"
    shift 2
  fi
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --diagnostic-deferred-minarea)
        driver_args+=("$1")
        ;;
      *)
        extra_env+=("$1")
        ;;
    esac
    shift
  done
  env \
    MPTDC_RECOVERY_REPO_ROOT="$REPO" \
    MPTDC_RECOVERY_PUBLISHER="$FAKE_PUBLISHER" \
    MPTDC_RECOVERY_PVS_PREP="$FAKE_PREP" \
    MPTDC_RECOVERY_PVS_AUDIT="$FAKE_AUDIT" \
    MPTDC_RECOVERY_PVS_DRC="$FAKE_DRC" \
    MPTDC_RECOVERY_PVS_LVS="$FAKE_LVS" \
    MPTDC_CADENCE_ENV="$FAKE_CADENCE_ENV" \
    MPTDC_INNOVUS_WORK="$WORK" \
    PUBLISH_CALLS="$calls" \
    "${extra_env[@]}" \
    bash "$DRIVER" --pnr-run-id "$pnr_run" --run-id "$pvs_run" \
      --expected-head "$HEAD_SHA" --ro-gds "$RO_GDS" "${driver_args[@]}"
}

write_exact_pg_wire_end_report() {
  local report="$1"
  cat > "$report" <<'EOF'
Net VDD: dangling Wire at (221.750, 681.160) (221.750, 681.160) on layer: MET3
Net VDD: dangling Wire at (48.000, 681.160) (48.000, 681.160) on layer: MET3
Net VDD: dangling Wire at (221.750, 201.160) (221.750, 201.160) on layer: MET3
Net VDD: dangling Wire at (48.000, 201.160) (48.000, 201.160) on layer: MET3
Net VDD: dangling Wire at (121.160, 233.620) (121.160, 233.620) on layer: METTP
Net VDD: dangling Wire at (121.160, 648.320) (121.160, 648.320) on layer: METTP
Net VSS: dangling Wire at (221.750, 685.160) (221.750, 685.160) on layer: MET3
Net VSS: dangling Wire at (48.000, 685.160) (48.000, 685.160) on layer: MET3
Net VSS: dangling Wire at (221.750, 205.160) (221.750, 205.160) on layer: MET3
Net VSS: dangling Wire at (48.000, 205.160) (48.000, 205.160) on layer: MET3
Net VSS: dangling Wire at (205.160, 158.320) (205.160, 158.320) on layer: METTP
Net VSS: dangling Wire at (125.160, 721.750) (125.160, 721.750) on layer: METTP
Net VSS: dangling Wire at (125.160, 648.320) (125.160, 648.320) on layer: METTP
Net VSS: dangling Wire at (125.160, 233.620) (125.160, 233.620) on layer: METTP
Net VSS: dangling Wire at (125.160, 158.320) (125.160, 158.320) on layer: METTP
    15 Problem(s) (IMPVFC-94): The net has dangling wire(s).
EOF
}

PASS_CALLS="$TMP_ROOT/pass.calls"
run_driver pvs_pass "$PASS_CALLS" > "$TMP_ROOT/pass.stdout"
grep -qx 'CADENCE_ENV_STATUS=PASS' "$TMP_ROOT/pass.stdout"
test "$(wc -l < "$PASS_CALLS")" -eq 5
grep -qx 'DECISION=PASS_CONTINUE' "$WORK/pvs_pass/reports/operator_gate_pvs_lvs.rpt"
grep -qx 'PVS_RECOVERY_STATUS=PASS' "$TMP_ROOT/pass.stdout"
grep -qx 'MPTDC_TC_PVS_CLOSED=YES' "$TMP_ROOT/pass.stdout"
grep -qx 'FINAL_DECISION=MPTDC_TC_PVS_CLOSED_NOT_MMMC_SIGNOFF' "$TMP_ROOT/pass.stdout"
grep -qx 'NOT_MMMC_SIGNOFF=YES' "$TMP_ROOT/pass.stdout"
grep -qx 'FINAL_SIGNOFF=NO' "$TMP_ROOT/pass.stdout"

ENV_FAIL_CALLS="$TMP_ROOT/env_fail.calls"
set +e
run_driver pvs_env_fail "$ENV_FAIL_CALLS" \
  MPTDC_CADENCE_ENV="$FAILING_CADENCE_ENV" > "$TMP_ROOT/env_fail.stdout"
ENV_FAIL_RC=$?
set -e
test "$ENV_FAIL_RC" -eq 5
grep -qx 'CADENCE_ENV_RC=23' "$TMP_ROOT/env_fail.stdout"
grep -qx 'CADENCE_ENV_STATUS=FAIL' "$TMP_ROOT/env_fail.stdout"
grep -qx 'DECISION=FAIL_STOP' "$TMP_ROOT/env_fail.stdout"
test ! -e "$WORK/pvs_env_fail"
test ! -e "$ENV_FAIL_CALLS"

FAIL_CALLS="$TMP_ROOT/fail.calls"
set +e
run_driver pvs_fail "$FAIL_CALLS" FAKE_DRC_FAIL_VARIANT=base > "$TMP_ROOT/fail.stdout"
FAIL_RC=$?
set -e
test "$FAIL_RC" -ne 0
test "$(wc -l < "$FAIL_CALLS")" -eq 3
grep -qx 'DECISION=FAIL_STOP' "$WORK/pvs_fail/reports/operator_gate_pvs_drc_base.rpt"
test ! -e "$WORK/pvs_fail/reports/operator_gate_pvs_drc_density.rpt"
test ! -e "$WORK/pvs_fail/reports/operator_gate_pvs_lvs.rpt"

sed -i \
  -e 's/^ROUTE_STATUS=PASS$/ROUTE_STATUS=PVS_CANDIDATE/' \
  -e 's/^SPECIAL_NET_CONNECTIVITY_BAD=0$/SPECIAL_NET_CONNECTIVITY_BAD=1/' \
  -e 's/^SPECIAL_NET_CONNECTIVITY_RAW_BAD=0$/SPECIAL_NET_CONNECTIVITY_RAW_BAD=1/' \
  -e 's/^PHYSICAL_GATE_MODE=STRICT_CLEAN$/PHYSICAL_GATE_MODE=PVS_CANDIDATE_EXACT_PG_WIRE_ENDS/' \
  -e 's/^DECISION=PASS_CONTINUE$/DECISION=PVS_CANDIDATE_CONTINUE/' \
  "$PHYSICAL_GATE"
cat >> "$PHYSICAL_GATE" <<'EOF'
ALLOW_EXACT_PG_PVS_CANDIDATE=1
ROUTE_PG_PVS_CANDIDATE_STATUS=PASS
ROUTE_PG_PVS_CANDIDATE_EXACT_MATCH=1
EOF
cat > "$(dirname "$PHYSICAL_GATE")/route_pg_pvs_candidate_status.rpt" <<'EOF'
ROUTE_PG_PVS_CANDIDATE_PROFILE=HALO10_PNRLEF_15
ROUTE_PG_PVS_CANDIDATE_EXPECTED_COUNT=15
ROUTE_PG_PVS_CANDIDATE_ACTUAL_COUNT=15
ROUTE_PG_PVS_CANDIDATE_SUMMARY_COUNT=15
ROUTE_PG_PVS_CANDIDATE_EXACT_MATCH=1
ROUTE_PG_PVS_CANDIDATE_OTHER_NET_LINE_COUNT=0
ROUTE_PG_PVS_CANDIDATE_OTHER_PROBLEM_LINE_COUNT=0
ROUTE_PG_PVS_CANDIDATE_STATUS=PASS
EOF
cat > "$(dirname "$PHYSICAL_GATE")/route_connectivity_special_detailed.rpt" <<'EOF'
Net VDD: dangling Wire at (221.750, 681.160) (221.750, 681.160) on layer: MET3
Net VDD: dangling Wire at (48.000, 681.160) (48.000, 681.160) on layer: MET3
Net VDD: dangling Wire at (221.750, 201.160) (221.750, 201.160) on layer: MET3
Net VDD: dangling Wire at (48.000, 201.160) (48.000, 201.160) on layer: MET3
Net VDD: dangling Wire at (121.160, 233.620) (121.160, 233.620) on layer: METTP
Net VDD: dangling Wire at (121.160, 648.320) (121.160, 648.320) on layer: METTP
Net VSS: dangling Wire at (221.750, 685.160) (221.750, 685.160) on layer: MET3
Net VSS: dangling Wire at (48.000, 685.160) (48.000, 685.160) on layer: MET3
Net VSS: dangling Wire at (221.750, 205.160) (221.750, 205.160) on layer: MET3
Net VSS: dangling Wire at (48.000, 205.160) (48.000, 205.160) on layer: MET3
Net VSS: dangling Wire at (205.160, 158.320) (205.160, 158.320) on layer: METTP
Net VSS: dangling Wire at (125.160, 721.750) (125.160, 721.750) on layer: METTP
Net VSS: dangling Wire at (125.160, 648.320) (125.160, 648.320) on layer: METTP
Net VSS: dangling Wire at (125.160, 233.620) (125.160, 233.620) on layer: METTP
Net VSS: dangling Wire at (125.160, 158.320) (125.160, 158.320) on layer: METTP
    15 Problem(s) (IMPVFC-94): The net has dangling wire(s).
EOF
git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m candidate-fixtures
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"

CANDIDATE_CALLS="$TMP_ROOT/candidate.calls"
run_driver pvs_candidate "$CANDIDATE_CALLS" > "$TMP_ROOT/candidate.stdout"
grep -qx 'PVS_RECOVERY_STATUS=PASS' "$TMP_ROOT/candidate.stdout"
grep -qx 'MPTDC_TC_PVS_CLOSED=YES' "$TMP_ROOT/candidate.stdout"
test "$(wc -l < "$CANDIDATE_CALLS")" -eq 5

sed -i 's/(221.750, 681.160)/(221.751, 681.160)/g' \
  "$(dirname "$PHYSICAL_GATE")/route_connectivity_special_detailed.rpt"
git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m altered-candidate-fixture
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"
ALTERED_CALLS="$TMP_ROOT/altered.calls"
set +e
run_driver pvs_altered_candidate "$ALTERED_CALLS" > "$TMP_ROOT/altered.stdout"
ALTERED_RC=$?
set -e
test "$ALTERED_RC" -eq 4
grep -qx 'PVS_RECOVERY_PREFLIGHT=FAIL' "$TMP_ROOT/altered.stdout"
grep -qx 'DECISION=FAIL_STOP' "$TMP_ROOT/altered.stdout"
test ! -e "$WORK/pvs_altered_candidate"
test ! -e "$ALTERED_CALLS"

MINAREA_SOURCE_RUN=minarea_source_fixture
MINAREA_FAILED_V6R_RUN=minarea_failed_v6r_fixture
MINAREA_ENDEXT_TRIAL_RUN=minarea_endext_trial_fixture
MINAREA_REPLAY_RUN=minarea_replay_fixture
MINAREA_SOURCE_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$MINAREA_SOURCE_RUN/reports"
MINAREA_FAILED_V6R_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$MINAREA_FAILED_V6R_RUN/reports"
MINAREA_ENDEXT_TRIAL_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$MINAREA_ENDEXT_TRIAL_RUN/reports"
MINAREA_REPLAY_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$MINAREA_REPLAY_RUN/reports"
MINAREA_FAILED_V6R_CKPT="$WORK/$MINAREA_FAILED_V6R_RUN/checkpoints/repaired_route.enc.dat"
MINAREA_REPLAY_CKPT="$WORK/$MINAREA_REPLAY_RUN/checkpoints/repaired_route.enc.dat"
mkdir -p "$MINAREA_SOURCE_REPORTS" "$MINAREA_FAILED_V6R_REPORTS" \
  "$MINAREA_ENDEXT_TRIAL_REPORTS" \
  "$MINAREA_REPLAY_REPORTS" "$MINAREA_FAILED_V6R_CKPT" "$MINAREA_REPLAY_CKPT"

cat > "$MINAREA_SOURCE_REPORTS/operator_gate_physical_pnr.rpt" <<'EOF'
STEP=PHYSICAL_PNR
PNR_RC=1
ROUTE_STATUS=FAIL
INNOVUS_VERIFY_DRC_STATUS=FAIL
GEOMETRY_DRC_VIOLATIONS=2
SHORTS=0
REGULAR_NET_CONNECTIVITY_BAD=0
SPECIAL_NET_CONNECTIVITY_BAD=1
SPECIAL_NET_CONNECTIVITY_RAW_BAD=1
SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES=0
RO_HALO_STATUS=PASS
RO_HALO_OCCUPANCY_STATUS=PASS
RO_HALO_TOTAL_INTRUSION_COUNT=0
ro_slow_tap0_o_COUNT=1
ro_fast_tap0_o_COUNT=1
RO_TAP_OBSERVABILITY_PIN_COUNT=2
DECISION=FAIL_STOP
EOF
cat > "$MINAREA_SOURCE_REPORTS/route_status.rpt" <<'EOF'
ROUTE_STATUS=FAIL
INNOVUS_VERIFY_DRC_STATUS=FAIL
GEOMETRY_DRC_VIOLATIONS=2
SHORTS=0
REGULAR_NET_CONNECTIVITY_BAD=0
SPECIAL_NET_CONNECTIVITY_BAD=1
SPECIAL_NET_CONNECTIVITY_RAW_BAD=1
SPECIAL_NET_CONNECTIVITY_NON_RO_FAILURES=0
ROUTE_GATE_FAILURE_CHECKPOINT_DAT_EXISTS=1
EOF
{
  printf 'idx\tmarker_handle\tbox\tlayer\ttype\tsubType\tmessage\n'
  printf '1\tm1\t{363.53 357.98 363.91 358.26}\tMET1\tGeometry\tMinimal_Area\tRegular Wire of Net u_core_n_57960 Actual: 0.10640000 Required: 0.20200000\n'
  printf '2\tm2\t{385.37 328.3 385.75 328.58}\tMET1\tGeometry\tMinimal_Area\tRegular Wire of Net u_core_n_57556 Actual: 0.10640000 Required: 0.20200000\n'
} > "$MINAREA_SOURCE_REPORTS/route_drc_markers.tsv"
write_exact_pg_wire_end_report "$MINAREA_SOURCE_REPORTS/route_connectivity_special_detailed.rpt"
cat > "$MINAREA_SOURCE_REPORTS/filler_status.rpt" <<'EOF'
FILLER_CANDIDATES=FEED25JIHD FEED15JIHD FEED10JIHD FEED7JIHD FEED5JIHD FEED3JIHD FEED2JIHD FEED1JIHD
FILLER_COUNT=3
FILLER_INSERTION_STATUS=PASS
EOF
cat > "$MINAREA_SOURCE_REPORTS/row_infra_insertion.rpt" <<'EOF'
FILLER_CANDIDATES=FEED25JIHD FEED15JIHD FEED10JIHD FEED7JIHD FEED5JIHD FEED3JIHD FEED2JIHD FEED1JIHD
TIE_HIGH_CANDIDATES=LOGIC1DJIHD LOGIC1LVJIHD
TIE_LOW_CANDIDATES=LOGIC0DJIHD LOGIC0LVJIHD
EOF

cat > "$MINAREA_FAILED_V6R_REPORTS/operator_gate_route_min_area_patch_trial.rpt" <<EOF
STEP=ROUTE_MIN_AREA_PATCH_TRIAL
SOURCE_PNR_RUN_ID=$MINAREA_SOURCE_RUN
SOURCE_PATCH_TRIAL_RUN_ID=NONE
REPAIR_RC=0
PATCH_STAGE_MODE=trial
REPAIR_METHOD=CALIBRATED_TWO_STUB_REGULAR_MET1_V6R
COMMAND_1_STATUS=FAIL
COMMAND_2_STATUS=MISSING
MANUAL_ECO_STATUS=FAIL
MANUAL_PRE_DRC=2
MANUAL_PRE_SHORTS=0
INITIAL_DRC=2
INITIAL_SHORTS=0
INITIAL_REGULAR_CONNECTIVITY_BAD=0
INITIAL_SPECIAL_CONNECTIVITY_BAD=1
INITIAL_SPECIAL_CONNECTIVITY_RAW_BAD=1
INITIAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=0
INITIAL_SPECIAL_DANGLING_COUNT=15
FINAL_DRC=1
FINAL_SHORTS=0
FINAL_REGULAR_CONNECTIVITY_BAD=0
FINAL_SPECIAL_CONNECTIVITY_BAD=1
FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=1
FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=0
FINAL_SPECIAL_DANGLING_COUNT=15
FINAL_UNROUTED_NETS=0
FINAL_REPORT_ROUTE_ZERO_STATUS=PASS
CHECKPOINT_REPAIR_STATUS=FAIL_COMMAND
FINAL_CHECKPOINT_DAT_EXISTS=1
SPECIAL_SIGNATURE_STATUS=PASS
TIMING_GATE_STATUS=NOT_RUN_PROOF_ONLY
ro_slow_tap0_o_COUNT=1
ro_fast_tap0_o_COUNT=1
RO_TAP_OBSERVABILITY_PIN_COUNT=2
PATCH_TRIAL_GATE_MODE=FAIL
DECISION=FAIL_STOP
EOF
write_exact_pg_wire_end_report \
  "$MINAREA_FAILED_V6R_REPORTS/01_after_command_verify_connectivity_special_detailed.rpt"
{
  printf 'idx\tmarker_handle\tbox\tlayer\ttype\tsubType\tmessage\n'
  printf '1\tm1\t{385.06 328.29 385.75 328.52}\tMET1\tGeometry\tMinimal_Area\tRegular Wire of Net u_core_n_57556 Actual: 0.17770000 Required: 0.20200000\n'
} > "$MINAREA_FAILED_V6R_REPORTS/01_after_command_verify_drc_markers.tsv"

cat > "$MINAREA_ENDEXT_TRIAL_REPORTS/operator_gate_route_min_area_endext_trial.rpt" <<EOF
STEP=ROUTE_MIN_AREA_ENDEXT_TRIAL
SOURCE_PNR_RUN_ID=$MINAREA_SOURCE_RUN
SOURCE_PATCH_TRIAL_RUN_ID=$MINAREA_FAILED_V6R_RUN
SOURCE_ENDEXT_TRIAL_RUN_ID=NONE
REPAIR_RC=0
PATCH_STAGE_MODE=trial
REPAIR_METHOD=CANONICAL_FIXED_MET1_FREE_END_EXTENSION_V8
COMMAND_1_STATUS=PASS
COMMAND_2_STATUS=MISSING
MANUAL_ECO_STATUS=PASS
V8_STAGE_MODE=trial
PRE_DRC=1
PRE_SHORTS=0
PRE_MINAREA_MARKER_STATUS=PASS
FIXED_WIRE_EXTENSION_STATUS=PASS
FIXED_WIRE_EXTENSION_METHOD=dbSet
FIXED_WIRE_EXTENSION_ATTRIBUTE=endExt
FIXED_WIRE_EXTENSION_PRE_UM=0.115
FIXED_WIRE_EXTENSION_POST_UM=0.255
N57556_END_EXT_CANONICAL_STUB_STATUS=PASS
N57556_END_EXT_CANONICAL_STUB_WIDTH=0.23
N57556_END_EXT_CANONICAL_STUB_LENGTH=0.385
N57556_END_EXT_FREE_END_EXTENSION_DELTA_UM=0.14
TARGET_WIRE_HANDLE_STATUS=UNCHANGED
TARGET_OTHER_ROUTE_OBJECT_STATUS=UNCHANGED
RESERVED_FILL_OBJECT_STATUS=UNCHANGED
N57556_LANDING_REPRESENTATION_STATUS=UNCHANGED
TARGET_VIA_FINGERPRINT_STATUS=UNCHANGED
POST_MINAREA_MARKER_COUNT=0
FINAL_DRC=0
FINAL_SHORTS=0
FINAL_REGULAR_CONNECTIVITY_BAD=0
FINAL_SPECIAL_CONNECTIVITY_BAD=1
FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=1
FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=0
FINAL_SPECIAL_DANGLING_COUNT=15
FINAL_UNROUTED_NETS=0
FINAL_REPORT_ROUTE_ZERO_STATUS=PASS
FINAL_ROUTE_GATE_PASS=0
CHECKPOINT_REPAIR_STATUS=PASS_GEOMETRY_REVIEW_CONNECTIVITY
FINAL_CHECKPOINT_DAT_EXISTS=1
SPECIAL_SIGNATURE_STATUS=PASS
TIMING_GATE_STATUS=NOT_RUN_PROOF_ONLY
ro_slow_tap0_o_COUNT=1
ro_fast_tap0_o_COUNT=1
RO_TAP_OBSERVABILITY_PIN_COUNT=2
ENDEXT_TRIAL_GATE_MODE=PASS_EXACT_PG_FINGERPRINT
DECISION=PASS_REPLAY
EOF
write_exact_pg_wire_end_report \
  "$MINAREA_ENDEXT_TRIAL_REPORTS/01_after_command_verify_connectivity_special_detailed.rpt"

cat > "$MINAREA_REPLAY_REPORTS/operator_gate_route_min_area_repair.rpt" <<EOF
STEP=ROUTE_MIN_AREA_REPAIR
SOURCE_PNR_RUN_ID=$MINAREA_SOURCE_RUN
SOURCE_PATCH_TRIAL_RUN_ID=$MINAREA_FAILED_V6R_RUN
SOURCE_ENDEXT_TRIAL_RUN_ID=$MINAREA_ENDEXT_TRIAL_RUN
REPAIR_RC=0
PATCH_STAGE_MODE=replay
REPAIR_METHOD=CANONICAL_FIXED_MET1_FREE_END_EXTENSION_V8
COMMAND_1_STATUS=PASS
COMMAND_2_STATUS=PASS
MANUAL_ECO_STATUS=PASS
V8_STAGE_MODE=replay
PRE_DRC=2
PRE_SHORTS=0
INTERMEDIATE_DRC=1
INTERMEDIATE_SHORTS=0
INTERMEDIATE_MINAREA_MARKER_STATUS=PASS
FIXED_WIRE_EXTENSION_STATUS=PASS
FIXED_WIRE_EXTENSION_METHOD=dbSet
FIXED_WIRE_EXTENSION_ATTRIBUTE=endExt
FIXED_WIRE_EXTENSION_PRE_UM=0.115
FIXED_WIRE_EXTENSION_POST_UM=0.255
N57556_END_EXT_CANONICAL_STUB_STATUS=PASS
N57556_END_EXT_CANONICAL_STUB_WIDTH=0.23
N57556_END_EXT_CANONICAL_STUB_LENGTH=0.385
N57556_END_EXT_FREE_END_EXTENSION_DELTA_UM=0.14
TARGET_WIRE_HANDLE_STATUS=UNCHANGED
TARGET_OTHER_ROUTE_OBJECT_STATUS=UNCHANGED
RESERVED_FILL_OBJECT_STATUS=UNCHANGED
N57556_LANDING_REPRESENTATION_STATUS=UNCHANGED
TARGET_VIA_FINGERPRINT_STATUS=UNCHANGED
POST_MINAREA_MARKER_COUNT=0
FINAL_DRC=0
FINAL_SHORTS=0
FINAL_REGULAR_CONNECTIVITY_BAD=0
FINAL_SPECIAL_CONNECTIVITY_BAD=1
FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=1
FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=0
FINAL_SPECIAL_DANGLING_COUNT=15
FINAL_UNROUTED_NETS=0
FINAL_REPORT_ROUTE_ZERO_STATUS=PASS
FINAL_ROUTE_GATE_PASS=0
CHECKPOINT_REPAIR_STATUS=PASS_GEOMETRY_REVIEW_CONNECTIVITY
FINAL_CHECKPOINT_DAT_EXISTS=1
SPECIAL_SIGNATURE_STATUS=PASS
SETUP_STATUS_TC=PASS
TC_HOLD_STATUS=PASS
DRV_STATUS=PASS
POWER_REPORT_CAPTURE_STATUS=PASS
TIMING_GATE_STATUS=PASS
ro_slow_tap0_o_COUNT=1
ro_fast_tap0_o_COUNT=1
RO_TAP_OBSERVABILITY_PIN_COUNT=2
MINAREA_REPAIR_GATE_MODE=PVS_CANDIDATE_EXACT_PG_WIRE_ENDS
DECISION=PVS_CANDIDATE_CONTINUE
EOF
write_exact_pg_wire_end_report \
  "$MINAREA_REPLAY_REPORTS/02_after_command_verify_connectivity_special_detailed.rpt"

TIE1_PROBE_RUN=tie1_probe_fixture
TIE1_FAILED_TRIAL_RUN=tie1_zero_effect_fixture
TIE1_CANDIDATE_RUN=tie1_filler_recycle_fixture
TIE1_PROBE_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$TIE1_PROBE_RUN/reports"
TIE1_FAILED_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$TIE1_FAILED_TRIAL_RUN/reports"
TIE1_FAILED_MANIFESTS="$REPO/MPTDC/docs/server_snapshots/innovus/$TIE1_FAILED_TRIAL_RUN/manifests"
TIE1_CANDIDATE_REPORTS="$REPO/MPTDC/docs/server_snapshots/innovus/$TIE1_CANDIDATE_RUN/reports"
TIE1_CANDIDATE_CKPT="$WORK/$TIE1_CANDIDATE_RUN/checkpoints/repaired_route.enc.dat"
mkdir -p "$TIE1_PROBE_REPORTS" "$TIE1_FAILED_REPORTS" \
  "$TIE1_FAILED_MANIFESTS" "$TIE1_CANDIDATE_REPORTS" "$TIE1_CANDIDATE_CKPT"
printf 'accepted tie1 filler recycle candidate\n' > "$TIE1_CANDIDATE_CKPT/design.bin"
TIE1_CANDIDATE_SHA="$(tree_hash "$TIE1_CANDIDATE_CKPT")"

cat > "$TIE1_PROBE_REPORTS/operator_gate_tie1_checkpoint_probe.rpt" <<EOF
STEP=TIE1_CHECKPOINT_PROBE
SOURCE_CHECKPOINT=$MINAREA_FAILED_V6R_CKPT
CADENCE_ENV_STATUS=PASS
INNOVUS_RC=0
PROBE_STATUS=PASS
RESTORE_STATUS=PASS
CORE_QUERY_STATUS=PASS
CORE_QUERY_ERROR_COUNT=0
TIE1_SOURCE_TOKEN_COUNT=0
TIE_MASTER_SOURCE_TOKEN_COUNT=0
TIE1_NET_COUNT=0
TIE1_INST_TERM_COUNT=0
TIE1_REGULAR_WIRE_COUNT=0
TIE1_SPECIAL_WIRE_COUNT=0
TIE1_VIA_COUNT=0
TIE_AVAILABLE_MASTER_COUNT=4
PHYSICAL_TIE_MASTER_COUNT=0
PHYSICAL_TIE_INSTANCE_COUNT=0
FLAGGED_TIE_HIGH_TERM_COUNT=91
FLAGGED_TIE_LOW_TERM_COUNT=0
SOURCE_CHECKPOINT_HASH_STATUS=PASS
SAFE_COPY_MATCH_STATUS=PASS
SAFE_CHECKPOINT_HASH_STATUS=PASS
BOUNDARY_EVIDENCE_HASH_STATUS=PASS
PHYSICAL_SOURCE_HASH_STATUS=PASS
RESTORE_COMMAND_COUNT=1
MUTATION_COMMAND_COUNT=0
DESIGN_OBJECT_COUNT_STATUS=PASS
DESIGN_MUTATION_COUNT=0
READ_ONLY_STATUS=PASS
SIGNOFF_ELIGIBLE=NO
DECISION=PASS_REVIEW_TIE1_EVIDENCE
NEXT_STAGE=REVIEW_TIE1_EVIDENCE_BEFORE_HASH_GUARDED_TRIAL
EOF

{
  for index in $(seq 1 91); do
    printf 'u_sink[%03d]/SN\n' "$index"
  done
} > "$TIE1_FAILED_MANIFESTS/tie1_instance_pin_targets.txt"
TIE1_TARGET_SHA="$(sha256sum "$TIE1_FAILED_MANIFESTS/tie1_instance_pin_targets.txt" | awk '{print $1}')"
cat > "$TIE1_FAILED_REPORTS/tie1_trial_baseline_check_place.rpt" <<'EOF'
*info: Placed = 39089
*info: Unplaced = 0
Placement Density: 100.00%(907533/907533)
EOF
cat > "$TIE1_FAILED_REPORTS/operator_gate_tie1_insertion_trial.rpt" <<EOF
STEP=TIE1_INSERTION_TRIAL
PROBE_RUN_ID=$TIE1_PROBE_RUN
SOURCE_CHECKPOINT=$MINAREA_FAILED_V6R_CKPT
AUTHORIZATION=EXACT_MPTDC_TIE1_HIGH_TRIAL
INNOVUS_RC=1
TIE1_INSERTION_TRIAL_STATUS=FAIL
ADD_TIE_SELECTION_MODE=EXACT_INSTANCE_PIN_FILE
INSTANCE_PIN_INPUT_GENERATION_STATUS=PASS
INSTANCE_PIN_TARGET_COUNT=91
INSTANCE_PIN_TARGET_UNIQUE_COUNT=91
INSTANCE_PIN_TARGET_INVALID_COUNT=0
INSTANCE_PIN_TARGET_MATCH_STATUS=PASS
SET_TIE_MODE_STATUS=PASS
ADD_TIE_STATUS=PASS
ADD_TIE_EFFECT_STATUS=FAIL
ADD_TIE_EFFECT_REASON=NO_ELIGIBLE_TARGET_WAS_CONNECTED
FINAL_CONNECTED_HIGH_TERM_COUNT=0
FINAL_DISCONNECTED_HIGH_TERM_COUNT=91
FINAL_TIE_NET_COUNT=0
FILLER_COUNT_AFTER=24797
BASELINE_DRC=1
BASELINE_SHORTS=0
BASELINE_REGULAR_CONNECTIVITY_BAD=0
BASELINE_SPECIAL_CONNECTIVITY_BAD=1
BASELINE_UNROUTED_NETS=0
SOURCE_CHECKPOINT_HASH_STATUS=PASS
SAFE_INPUT_READ_ONLY_STATUS=PASS
INSTANCE_PIN_INPUT_READ_ONLY_STATUS=PASS
INSTANCE_PIN_TARGET_SHA256_PRE=$TIE1_TARGET_SHA
INSTANCE_PIN_TARGET_SHA256_POST=$TIE1_TARGET_SHA
CANDIDATE_CHECKPOINT_STATUS=FAIL
SIGNOFF_ELIGIBLE=NO
DECISION=FAIL_STOP
NEXT_STAGE=STOP_AND_REVIEW_PUBLISHED_EVIDENCE
EOF

cat > "$TIE1_CANDIDATE_REPORTS/filler_status.rpt" <<'EOF'
FILLER_CANDIDATES=FEED25JIHD FEED15JIHD FEED10JIHD FEED7JIHD FEED5JIHD FEED3JIHD FEED2JIHD FEED1JIHD
FILLER_COUNT=24785
FILLER_DELETE_STATUS=PASS
FILLER_DELETE_EFFECT_STATUS=PASS
FILLER_REFILL_COMMAND_STATUS=PASS
FILLER_REFILL_STATUS=PASS
FILLER_INSERTION_STATUS=PASS
FILLER_ADJUSTMENT_POLICY=EXACT_DELETE_INSERT_ROUTE_REFILL_PRIVATE_COPY
FINAL_FILLER_MASTER_SET_STATUS=PASS
NONFILLER_FINGERPRINT_STATUS=PASS
FINAL_SITE_OCCUPANCY_STATUS=PASS
FINAL_PLACEMENT_SITE_OCCUPIED=907533
FINAL_PLACEMENT_SITE_CAPACITY=907533
EOF
cat > "$TIE1_CANDIDATE_REPORTS/row_infra_insertion.rpt" <<'EOF'
FILLER_CANDIDATES=FEED25JIHD FEED15JIHD FEED10JIHD FEED7JIHD FEED5JIHD FEED3JIHD FEED2JIHD FEED1JIHD
TIE_HIGH_CANDIDATES=LOGIC1DJIHD LOGIC1LVJIHD
TIE_LOW_CANDIDATES=LOGIC0DJIHD LOGIC0LVJIHD
EOF
cat > "$TIE1_CANDIDATE_REPORTS/operator_gate_tie1_insertion_trial.rpt" <<EOF
STEP=TIE1_INSERTION_TRIAL
PROBE_RUN_ID=$TIE1_PROBE_RUN
SOURCE_FAILED_TRIAL_RUN_ID=$TIE1_FAILED_TRIAL_RUN
SOURCE_PNR_RUN_ID=$MINAREA_SOURCE_RUN
SOURCE_CHECKPOINT=$MINAREA_FAILED_V6R_CKPT
CANDIDATE_CHECKPOINT=$TIE1_CANDIDATE_CKPT
CANDIDATE_CHECKPOINT_SHA256=$TIE1_CANDIDATE_SHA
AUTHORIZATION=EXACT_MPTDC_TIE1_FILLER_RECYCLE_TRIAL
HIGH_MASTER=LOGIC1DJIHD
LOW_MASTER=LOGIC0DJIHD
MAX_FANOUT=8
MAX_DISTANCE_UM=20
INNOVUS_RC=0
TIE1_INSERTION_TRIAL_STATUS=PASS
FILLER_RECYCLE_MODE=DELETE_INSERT_ROUTE_REFILL
FILLER_DELETE_STATUS=PASS
FILLER_DELETE_EFFECT_STATUS=PASS
FILLER_COUNT_POST_DELETE=0
POST_DELETE_NONFILLER_FINGERPRINT_STATUS=PASS
POST_DELETE_ROUTE_SIGNATURE_STATUS=PASS
ADD_TIE_SELECTION_MODE=EXACT_INSTANCE_PIN_FILE
INSTANCE_PIN_INPUT_GENERATION_STATUS=PASS
INSTANCE_PIN_TARGET_FILE_STATUS=PASS
INSTANCE_PIN_TARGET_COUNT=91
INSTANCE_PIN_TARGET_UNIQUE_COUNT=91
INSTANCE_PIN_TARGET_INVALID_COUNT=0
INSTANCE_PIN_TARGET_MATCH_STATUS=PASS
SET_TIE_MODE_STATUS=PASS
ADD_TIE_STATUS=PASS
ADD_TIE_EFFECT_STATUS=PASS
ADD_TIE_EFFECT_REASON=NONE
SELECTED_ROUTE_STATUS=PASS
FILLER_MODE_STATUS=PASS
FILLER_REFILL_COMMAND_STATUS=PASS
PG_CONNECTIVITY_REBIND_STATUS=PASS
FILLER_REFILL_STATUS=PASS
BASELINE_PLACEMENT_STATUS=PASS
FINAL_PLACEMENT_STATUS=PASS
FINAL_CONNECTED_HIGH_TERM_COUNT=91
FINAL_DISCONNECTED_HIGH_TERM_COUNT=0
FINAL_FLAGGED_LOW_TERM_COUNT=0
FINAL_TIE_NET_COUNT=12
TIE_NET_SOURCE_CONTRACT_STATUS=PASS
TIE_NET_ROUTE_STATUS=PASS
TIE_FANOUT_STATUS=PASS
MAX_OBSERVED_TIE_FANOUT=8
NUMERIC_GATE_STATUS=PASS
TIE_HIGH_INSTANCE_DELTA=12
TARGET_HIGH_INSTANCE_DELTA=12
ALTERNATE_TIE_MASTER_DELTA=0
TIE_LOW_INSTANCE_DELTA=0
FILLER_COUNT_AFTER=24785
FINAL_FILLER_MASTER_SET_STATUS=PASS
NONFILLER_FINGERPRINT_STATUS=PASS
BASELINE_SITE_OCCUPANCY_STATUS=PASS
BASELINE_PLACEMENT_SITE_OCCUPIED=907533
BASELINE_PLACEMENT_SITE_CAPACITY=907533
FINAL_SITE_OCCUPANCY_STATUS=PASS
FINAL_PLACEMENT_SITE_OCCUPIED=907533
FINAL_PLACEMENT_SITE_CAPACITY=907533
UNEXPLAINED_INSTANCE_DELTA=0
PHYSICAL_DEBT_PRESERVATION_STATUS=PASS
BASELINE_DRC=1
BASELINE_SHORTS=0
BASELINE_REGULAR_CONNECTIVITY_BAD=0
BASELINE_SPECIAL_CONNECTIVITY_BAD=1
BASELINE_UNROUTED_NETS=0
BASELINE_REPORT_ROUTE_ZERO_STATUS=PASS
BASELINE_DRC_MARKER_SIGNATURE_COUNT=1
FINAL_DRC=1
FINAL_SHORTS=0
FINAL_REGULAR_CONNECTIVITY_BAD=0
FINAL_SPECIAL_CONNECTIVITY_BAD=1
FINAL_SPECIAL_CONNECTIVITY_RAW_BAD=1
FINAL_SPECIAL_CONNECTIVITY_NON_RO_FAILURES=0
FINAL_UNROUTED_NETS=0
FINAL_REPORT_ROUTE_ZERO_STATUS=PASS
FINAL_DRC_MARKER_SIGNATURE_COUNT=1
DRC_MARKER_SIGNATURE_MATCH_STATUS=PASS
CHECKPOINT_SAVE_STATUS=PASS
SOURCE_CHECKPOINT_HASH_STATUS=PASS
SAFE_COPY_MATCH_STATUS=PASS
SAFE_INPUT_READ_ONLY_STATUS=PASS
PROBE_EVIDENCE_READ_ONLY_STATUS=PASS
SOURCE_FAILED_TRIAL_EVIDENCE_READ_ONLY_STATUS=PASS
TRIAL_TCL_READ_ONLY_STATUS=PASS
INSTANCE_PIN_INPUT_READ_ONLY_STATUS=PASS
INSTANCE_PIN_TARGET_SHA256_PRE=$TIE1_TARGET_SHA
INSTANCE_PIN_TARGET_SHA256_POST=$TIE1_TARGET_SHA
EXPECTED_INSTANCE_PIN_SHA256=$TIE1_TARGET_SHA
SOURCE_FAILED_TRIAL_TARGET_SHA256=$TIE1_TARGET_SHA
CANDIDATE_CHECKPOINT_STATUS=PASS
TIMING_STATUS=NOT_RUN_BY_DIAGNOSTIC_TRIAL_SCOPE
FOUNDRY_DRC_STATUS=NOT_RUN
LVS_STATUS=NOT_RUN
SIGNOFF_ELIGIBLE=NO
DECISION=PASS_TIE1_TRIAL_CONTINUE
NEXT_STAGE=DIAGNOSTIC_PHYSICAL_PVS_FROM_TIE1_TRIAL
EOF

git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m minarea-replay-fixtures
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"

FAILED_V6R_NORMAL_CALLS="$TMP_ROOT/failed_v6r_normal.calls"
set +e
run_driver pvs_failed_v6r_normal "$FAILED_V6R_NORMAL_CALLS" \
  --test-pnr-run "$MINAREA_FAILED_V6R_RUN" > "$TMP_ROOT/failed_v6r_normal.stdout"
FAILED_V6R_NORMAL_RC=$?
set -e
test "$FAILED_V6R_NORMAL_RC" -eq 4
grep -qx 'PVS_RUN_CLASS=SIGNOFF_CANDIDATE' "$TMP_ROOT/failed_v6r_normal.stdout"
grep -qx 'CANDIDATE_GATE_STATUS=FAIL' "$TMP_ROOT/failed_v6r_normal.stdout"
test ! -e "$FAILED_V6R_NORMAL_CALLS"

DIAGNOSTIC_CALLS="$TMP_ROOT/failed_v6r_diagnostic.calls"
DIAGNOSTIC_DRC_CALLS="$TMP_ROOT/failed_v6r_diagnostic.drc_calls"
DIAGNOSTIC_LVS_CALLS="$TMP_ROOT/failed_v6r_diagnostic.lvs_calls"
run_driver pvs_failed_v6r_diagnostic "$DIAGNOSTIC_CALLS" \
  --test-pnr-run "$MINAREA_FAILED_V6R_RUN" \
  EXPECTED_PREP_CHECKPOINT="$MINAREA_FAILED_V6R_CKPT" \
  FAKE_DRC_NONZERO_VARIANT=base EXPECT_DIAGNOSTIC_LVS=1 \
  DRC_CALLS="$DIAGNOSTIC_DRC_CALLS" LVS_CALLS="$DIAGNOSTIC_LVS_CALLS" \
  --diagnostic-deferred-minarea > "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PNR_CANDIDATE_KIND=FAILED_V6R_ONE_MINAREA_DIAGNOSTIC' \
  "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'CANDIDATE_GATE_STATUS=PASS' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PVS_RECOVERY_STATUS=DIAGNOSTIC_COMPLETE' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'DIAGNOSTIC_COLLECTION_STATUS=PASS' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PVS_DRC_BASE=FAIL' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PVS_DRC_BASE_EVIDENCE_STATUS=ATTRIBUTABLE' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PVS_DRC_DENSITY=NOT_RUN_BY_SCOPE' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PVS_LVS=MATCH' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'MPTDC_TC_PVS_CLOSED=NO' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'DECISION=DIAGNOSTIC_COMPLETE' "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'NEXT_STAGE=MANUAL_MINAREA_REPAIR_THEN_CANONICAL_SIGNOFF_REPLAY' \
  "$TMP_ROOT/failed_v6r_diagnostic.stdout"
grep -qx 'PVS_RUN_CLASS=DIAGNOSTIC_NOT_SIGNOFF' \
  "$WORK/pvs_failed_v6r_diagnostic/manifests/pvs_diagnostic_scope.rpt"
grep -qx 'DECISION=DIAGNOSTIC_CONTINUE' \
  "$WORK/pvs_failed_v6r_diagnostic/reports/operator_gate_pvs_drc_base.rpt"
grep -qx 'DIAGNOSTIC_COLLECTION_STATUS=PASS' \
  "$WORK/pvs_failed_v6r_diagnostic/reports/operator_gate_pvs_diagnostic_summary.rpt"
grep -qx 'MPTDC_TC_PVS_CLOSED=NO' \
  "$WORK/pvs_failed_v6r_diagnostic/reports/operator_gate_pvs_diagnostic_summary.rpt"
grep -qx 'NEXT_STAGE=MANUAL_MINAREA_REPAIR_THEN_CANONICAL_SIGNOFF_REPLAY' \
  "$WORK/pvs_failed_v6r_diagnostic/reports/operator_gate_pvs_diagnostic_summary.rpt"
test "$(wc -l < "$DIAGNOSTIC_CALLS")" -eq 4
test "$(cat "$DIAGNOSTIC_DRC_CALLS")" = base
test "$(cat "$DIAGNOSTIC_LVS_CALLS")" = 1
test ! -e "$WORK/pvs_failed_v6r_diagnostic/reports/pvs_drc_density_status.rpt"

TIE1_DIAGNOSTIC_CALLS="$TMP_ROOT/tie1_diagnostic.calls"
TIE1_DIAGNOSTIC_DRC_CALLS="$TMP_ROOT/tie1_diagnostic.drc_calls"
TIE1_DIAGNOSTIC_LVS_CALLS="$TMP_ROOT/tie1_diagnostic.lvs_calls"
run_driver pvs_tie1_diagnostic "$TIE1_DIAGNOSTIC_CALLS" \
  --test-pnr-run "$TIE1_CANDIDATE_RUN" \
  EXPECTED_PREP_CHECKPOINT="$TIE1_CANDIDATE_CKPT" \
  FAKE_DRC_NONZERO_VARIANT=base EXPECT_DIAGNOSTIC_LVS=1 \
  DRC_CALLS="$TIE1_DIAGNOSTIC_DRC_CALLS" LVS_CALLS="$TIE1_DIAGNOSTIC_LVS_CALLS" \
  --diagnostic-deferred-minarea > "$TMP_ROOT/tie1_diagnostic.stdout"
grep -qx 'PNR_CANDIDATE_KIND=TIE1_FILLER_RECYCLE_ONE_MINAREA_DIAGNOSTIC' \
  "$TMP_ROOT/tie1_diagnostic.stdout"
grep -qx 'CANDIDATE_GATE_STATUS=PASS' "$TMP_ROOT/tie1_diagnostic.stdout"
grep -qx 'CANDIDATE_CHECKPOINT_HASH_STATUS=PASS' "$TMP_ROOT/tie1_diagnostic.stdout"
grep -Fxqx "SOURCE_PNR_RUN_ID=$TIE1_CANDIDATE_RUN" "$TMP_ROOT/tie1_diagnostic.stdout"
grep -Fxqx "CANDIDATE_CHECKPOINT_EXPECTED_SHA256=$TIE1_CANDIDATE_SHA" \
  "$TMP_ROOT/tie1_diagnostic.stdout"
grep -Fxqx "CANDIDATE_CHECKPOINT_ACTUAL_SHA256=$TIE1_CANDIDATE_SHA" \
  "$TMP_ROOT/tie1_diagnostic.stdout"
grep -qx 'PVS_RECOVERY_STATUS=DIAGNOSTIC_COMPLETE' "$TMP_ROOT/tie1_diagnostic.stdout"
grep -qx 'PVS_LVS=MATCH' "$TMP_ROOT/tie1_diagnostic.stdout"
grep -qx 'PNR_CANDIDATE_KIND=TIE1_FILLER_RECYCLE_ONE_MINAREA_DIAGNOSTIC' \
  "$WORK/pvs_tie1_diagnostic/manifests/pvs_diagnostic_scope.rpt"
grep -qx 'CANDIDATE_CHECKPOINT_HASH_STATUS=PASS' \
  "$WORK/pvs_tie1_diagnostic/reports/operator_gate_pvs_prepare.rpt"
test "$(wc -l < "$TIE1_DIAGNOSTIC_CALLS")" -eq 4
test "$(cat "$TIE1_DIAGNOSTIC_DRC_CALLS")" = base
test "$(cat "$TIE1_DIAGNOSTIC_LVS_CALLS")" = 1

cp -p "$TIE1_CANDIDATE_CKPT/design.bin" "$TMP_ROOT/tie1_candidate.good.bin"
printf 'checkpoint drift\n' >> "$TIE1_CANDIDATE_CKPT/design.bin"
TIE1_HASH_DRIFT_CALLS="$TMP_ROOT/tie1_hash_drift.calls"
set +e
run_driver pvs_tie1_hash_drift "$TIE1_HASH_DRIFT_CALLS" \
  --test-pnr-run "$TIE1_CANDIDATE_RUN" \
  --diagnostic-deferred-minarea > "$TMP_ROOT/tie1_hash_drift.stdout"
TIE1_HASH_DRIFT_RC=$?
set -e
test "$TIE1_HASH_DRIFT_RC" -eq 4
grep -qx 'CANDIDATE_CHECKPOINT_HASH_STATUS=FAIL' "$TMP_ROOT/tie1_hash_drift.stdout"
grep -qx 'CANDIDATE_GATE_STATUS=FAIL' "$TMP_ROOT/tie1_hash_drift.stdout"
grep -qx 'PVS_RECOVERY_PREFLIGHT=FAIL' "$TMP_ROOT/tie1_hash_drift.stdout"
grep -qx 'DECISION=FAIL_STOP' "$TMP_ROOT/tie1_hash_drift.stdout"
test ! -e "$TIE1_HASH_DRIFT_CALLS"
test ! -e "$WORK/pvs_tie1_hash_drift"
cp -p "$TMP_ROOT/tie1_candidate.good.bin" "$TIE1_CANDIDATE_CKPT/design.bin"

DIAGNOSTIC_MISMATCH_CALLS="$TMP_ROOT/failed_v6r_diagnostic_mismatch.calls"
set +e
run_driver pvs_failed_v6r_diagnostic_mismatch "$DIAGNOSTIC_MISMATCH_CALLS" \
  --test-pnr-run "$MINAREA_FAILED_V6R_RUN" \
  EXPECTED_PREP_CHECKPOINT="$MINAREA_FAILED_V6R_CKPT" \
  FAKE_DRC_NONZERO_VARIANT=base EXPECT_DIAGNOSTIC_LVS=1 FAKE_LVS_MISMATCH=1 \
  --diagnostic-deferred-minarea > "$TMP_ROOT/failed_v6r_diagnostic_mismatch.stdout"
DIAGNOSTIC_MISMATCH_RC=$?
set -e
test "$DIAGNOSTIC_MISMATCH_RC" -ne 0
test "$(wc -l < "$DIAGNOSTIC_MISMATCH_CALLS")" -eq 4
grep -qx 'DIAGNOSTIC_COLLECTION_STATUS=FAIL' \
  "$WORK/pvs_failed_v6r_diagnostic_mismatch/reports/operator_gate_pvs_diagnostic_summary.rpt"
grep -qx 'FINAL_DECISION=DIAGNOSTIC_LVS_NOT_MATCHED' \
  "$WORK/pvs_failed_v6r_diagnostic_mismatch/reports/operator_gate_pvs_diagnostic_summary.rpt"
grep -qx 'NEXT_STAGE=LVS_TRIAGE_BEFORE_MANUAL_DRC_REPAIR' \
  "$TMP_ROOT/failed_v6r_diagnostic_mismatch.stdout"

mv "$MINAREA_FAILED_V6R_CKPT" "${MINAREA_FAILED_V6R_CKPT}.saved"
MISSING_DIAGNOSTIC_CALLS="$TMP_ROOT/missing_diagnostic_checkpoint.calls"
set +e
run_driver pvs_missing_diagnostic_checkpoint "$MISSING_DIAGNOSTIC_CALLS" \
  --test-pnr-run "$MINAREA_FAILED_V6R_RUN" \
  --diagnostic-deferred-minarea > "$TMP_ROOT/missing_diagnostic_checkpoint.stdout"
MISSING_DIAGNOSTIC_RC=$?
set -e
mv "${MINAREA_FAILED_V6R_CKPT}.saved" "$MINAREA_FAILED_V6R_CKPT"
test "$MISSING_DIAGNOSTIC_RC" -eq 4
grep -Fqx "STOP: accepted route checkpoint missing: $MINAREA_FAILED_V6R_CKPT" \
  "$TMP_ROOT/missing_diagnostic_checkpoint.stdout"
test ! -e "$MISSING_DIAGNOSTIC_CALLS"

sed -i 's/Actual: 0.17770000/Actual: 0.17780000/' \
  "$MINAREA_FAILED_V6R_REPORTS/01_after_command_verify_drc_markers.tsv"
git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m altered-failed-v6r-marker
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"
ALTERED_V6R_CALLS="$TMP_ROOT/altered_failed_v6r.calls"
set +e
run_driver pvs_altered_failed_v6r "$ALTERED_V6R_CALLS" \
  --test-pnr-run "$MINAREA_FAILED_V6R_RUN" \
  --diagnostic-deferred-minarea > "$TMP_ROOT/altered_failed_v6r.stdout"
ALTERED_V6R_RC=$?
set -e
test "$ALTERED_V6R_RC" -eq 4
grep -qx 'CANDIDATE_GATE_STATUS=FAIL' "$TMP_ROOT/altered_failed_v6r.stdout"
test ! -e "$ALTERED_V6R_CALLS"

sed -i 's/Actual: 0.17780000/Actual: 0.17770000/' \
  "$MINAREA_FAILED_V6R_REPORTS/01_after_command_verify_drc_markers.tsv"
git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m restore-failed-v6r-marker
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"

REPLAY_CALLS="$TMP_ROOT/replay.calls"
run_driver pvs_replay "$REPLAY_CALLS" --test-pnr-run "$MINAREA_REPLAY_RUN" \
  EXPECTED_PREP_CHECKPOINT="$MINAREA_REPLAY_CKPT" > "$TMP_ROOT/replay.stdout"
grep -qx 'PNR_CANDIDATE_KIND=MINAREA_V8_CANONICAL_REPLAY' "$TMP_ROOT/replay.stdout"
grep -qx 'CANDIDATE_GATE_STATUS=PASS' "$TMP_ROOT/replay.stdout"
grep -Fxqx "SOURCE_CKPT=$MINAREA_REPLAY_CKPT" "$TMP_ROOT/replay.stdout"
grep -qx 'PVS_RECOVERY_STATUS=PASS' "$TMP_ROOT/replay.stdout"
grep -qx 'MPTDC_TC_PVS_CLOSED=YES' "$TMP_ROOT/replay.stdout"
grep -qx 'PNR_CANDIDATE_KIND=MINAREA_V8_CANONICAL_REPLAY' \
  "$WORK/pvs_replay/reports/operator_gate_pvs_prepare.rpt"
grep -Fxqx "SOURCE_CHECKPOINT=$MINAREA_REPLAY_CKPT" \
  "$WORK/pvs_replay/reports/operator_gate_pvs_prepare.rpt"
test "$(wc -l < "$REPLAY_CALLS")" -eq 5

mv "$MINAREA_REPLAY_CKPT" "${MINAREA_REPLAY_CKPT}.saved"
MISSING_CKPT_CALLS="$TMP_ROOT/missing_replay_checkpoint.calls"
set +e
run_driver pvs_missing_replay_checkpoint "$MISSING_CKPT_CALLS" \
  --test-pnr-run "$MINAREA_REPLAY_RUN" > "$TMP_ROOT/missing_replay_checkpoint.stdout"
MISSING_CKPT_RC=$?
set -e
mv "${MINAREA_REPLAY_CKPT}.saved" "$MINAREA_REPLAY_CKPT"
test "$MISSING_CKPT_RC" -eq 4
grep -Fqx "STOP: accepted route checkpoint missing: $MINAREA_REPLAY_CKPT" \
  "$TMP_ROOT/missing_replay_checkpoint.stdout"
grep -qx 'DECISION=FAIL_STOP' "$TMP_ROOT/missing_replay_checkpoint.stdout"
test ! -e "$MISSING_CKPT_CALLS"

sed -i "s/^SOURCE_ENDEXT_TRIAL_RUN_ID=$MINAREA_ENDEXT_TRIAL_RUN$/SOURCE_ENDEXT_TRIAL_RUN_ID=untracked_trial/" \
  "$MINAREA_REPLAY_REPORTS/operator_gate_route_min_area_repair.rpt"
git -C "$REPO" add MPTDC
git -C "$REPO" commit -q -m broken-minarea-replay-ancestry
HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"
BROKEN_ANCESTRY_CALLS="$TMP_ROOT/broken_ancestry.calls"
set +e
run_driver pvs_broken_ancestry "$BROKEN_ANCESTRY_CALLS" \
  --test-pnr-run "$MINAREA_REPLAY_RUN" > "$TMP_ROOT/broken_ancestry.stdout"
BROKEN_ANCESTRY_RC=$?
set -e
test "$BROKEN_ANCESTRY_RC" -eq 4
grep -qx 'CANDIDATE_GATE_STATUS=FAIL' "$TMP_ROOT/broken_ancestry.stdout"
grep -qx 'PVS_RECOVERY_PREFLIGHT=FAIL' "$TMP_ROOT/broken_ancestry.stdout"
grep -qx 'DECISION=FAIL_STOP' "$TMP_ROOT/broken_ancestry.stdout"
test ! -e "$BROKEN_ANCESTRY_CALLS"

echo "MPTDC_RO6_RECOVERY_PVS_DRIVER_TEST=PASS"
